def m(data):
    return " ".join([f'P{i+1}: ACTION/PROPS="{a}" | TEXT="{t}"' for i, (a, t) in enumerate(data)])

themes = [
    ("和服美人ｘ春を感じるｘ満開の桜", [
        # Set 1: お花見の待ち合わせ・挨拶
        m([("kimono beauty waving under sakura", "おはようございます"),
           ("kimono beauty pointing at full bloom sakura", "満開ですね"),
           ("kimono beauty smiling with falling petals", "春ですね"),
           ("kimono beauty looking up happily", "わぁっ"),
           ("kimono beauty taking a selfie under sakura", "一緒に撮りましょ"),
           ("kimono beauty walking happily", "来れてよかった"),
           ("kimono beauty fixing her hair", "ちょっと待ってね"),
           ("kimono beauty looking excited", "楽しみです"),
           ("kimono beauty bowing gently", "よろしくお願いします")]),
        # Set 2: 感情表現
        m([("kimono beauty nodding with a soft smile", "はい"),
           ("kimono beauty clapping softly", "素敵です"),
           ("kimono beauty holding a petal closing eyes", "幸せ"),
           ("kimono beauty looking surprised", "えっ？"),
           ("kimono beauty hand on cheek over sakura", "ふふっ"),
           ("kimono beauty looking apologetic", "ごめんなさい"),
           ("kimono beauty holding hands in gratitude", "ありがとうございます"),
           ("kimono beauty showing empty hands playfully", "残念"),
           ("kimono beauty raising fist softly", "がんばって")]),
        # Set 3: 日常の返答
        m([("kimono beauty holding up OK sign", "OKです"),
           ("kimono beauty making a cross sign with arms", "ダメです"),
           ("kimono beauty thinking with finger on chin", "考え中です"),
           ("kimono beauty pointing to herself", "私ですか？"),
           ("kimono beauty offering an open hand", "どうぞ"),
           ("kimono beauty wiping a tear playfully", "ぴえん"),
           ("kimono beauty thumbs up", "いいね"),
           ("kimono beauty putting hands together", "お願い"),
           ("kimono beauty winking playfully", "ナイショです")]),
        # Set 4: 労いとお疲れ様
        m([("kimono beauty handing over a warm towel", "お疲れ様です"),
           ("kimono beauty patting shoulder gently", "無理しないでね"),
           ("kimono beauty giving an encouraging look", "応援してます"),
           ("kimono beauty offering green tea", "ひと休みしましょう"),
           ("kimono beauty pouring sake", "一杯どうぞ"),
           ("kimono beauty stretching gently", "疲れたー"),
           ("kimono beauty looking sleepy", "ふぁぁ"),
           ("kimono beauty bowing deeply", "お世話になります"),
           ("kimono beauty cheering with pom poms", "ファイト")]),
        # Set 5: リアクション
        m([("kimono beauty leaning forward intrigued", "それでそれで？"),
           ("kimono beauty laughing covering mouth", "あはは"),
           ("kimono beauty looking worried", "大丈夫？"),
           ("kimono beauty wide-eyed shock", "びっくり"),
           ("kimono beauty looking relieved", "よかった"),
           ("kimono beauty tilting head", "どういうこと？"),
           ("kimono beauty clapping excitedly", "すごい！"),
           ("kimono beauty looking disappointed", "がっかり"),
           ("kimono beauty striking a pose", "ジャーン")]),
        # Set 6: 別れと夜桜
        m([("kimono beauty waving goodbye under the moon", "またね"),
           ("kimono beauty bowing slightly in the evening", "お気をつけて"),
           ("kimono beauty looking back over shoulder", "また行きましょう"),
           ("kimono beauty looking sleepy rubbing eyes", "おやすみなさい"),
           ("kimono beauty pointing at the starry sky", "星が綺麗"),
           ("kimono beauty holding a lit lantern", "足元気をつけて"),
           ("kimono beauty looking slightly sad to leave", "もうこんな時間"),
           ("kimono beauty smiling with a gentle sigh", "楽しかったです"),
           ("kimono beauty holding kimono sleeve waving", "バイバイ")])
    ]),
    ("和服美人ｘ春を感じるｘ和菓子とお茶", [
        # Set 1: お茶の準備と誘い
        m([("kimono beauty presenting a beautiful wagashi", "お茶にしませんか"),
           ("kimono beauty pouring green tea gracefully", "どうぞ"),
           ("kimono beauty holding a matcha bowl", "いかがですか"),
           ("kimono beauty looking at colorful wagashi happily", "迷っちゃう"),
           ("kimono beauty offering a seat at the table", "座って座って"),
           ("kimono beauty waiting patiently", "待ってます"),
           ("kimono beauty carrying a tray of sweets", "お待たせ"),
           ("kimono beauty smiling with anticipation", "ワクワク"),
           ("kimono beauty pointing at wagashi", "美味しいよ")]),
        # Set 2: 実食と感想
        m([("kimono beauty taking a bite of wagashi, sparkling eyes", "美味しい！"),
           ("kimono beauty holding cheeks with both hands", "ほっぺが落ちそう"),
           ("kimono beauty sipping tea closing eyes", "ほっとします"),
           ("kimono beauty holding a half-eaten sakura mochi", "春の味ですね"),
           ("kimono beauty looking full and happy", "ごちそうさまでした"),
           ("kimono beauty wiping mouth gently", "満足"),
           ("kimono beauty pointing at the tea cup", "おかわりはいかが？"),
           ("kimono beauty putting hands together softly", "いただきます"),
           ("kimono beauty handing over a dango", "一口どうぞ")]),
        # Set 3: 感情表現
        m([("kimono beauty nodding happily", "はい"),
           ("kimono beauty shaking head gently", "ううん"),
           ("kimono beauty bowing politely", "ありがとうございます"),
           ("kimono beauty looking down with a blush", "ごめんなさい"),
           ("kimono beauty making OK sign with tea cup", "OK"),
           ("kimono beauty tilting head slightly", "え？"),
           ("kimono beauty clapping softly", "すごい"),
           ("kimono beauty covering mouth laughing", "ふふっ"),
           ("kimono beauty raising hand", "はーい")]),
        # Set 4: 状況や状況への反応
        m([("kimono beauty looking at a beautiful wagashi box", "素敵です"),
           ("kimono beauty pointing to the clock", "もうこんな時間"),
           ("kimono beauty resting head on hands slowly", "眠くなってきた"),
           ("kimono beauty looking out the window", "いいお天気"),
           ("kimono beauty offering an umbrella", "雨降ってきたね"),
           ("kimono beauty picking up a ringing phone", "もしもし"),
           ("kimono beauty writing on a notepad", "メモメモ"),
           ("kimono beauty using a calculator", "計算中"),
           ("kimono beauty looking confused", "どうしよう")]),
        # Set 5: 応援・気遣い
        m([("kimono beauty handing a wagashi as a present", "お土産です"),
           ("kimono beauty rubbing friend's back", "お疲れ様"),
           ("kimono beauty giving thumbs up", "がんばれー"),
           ("kimono beauty looking worried", "大丈夫かな"),
           ("kimono beauty offering medicine", "無理しないでね"),
           ("kimono beauty wiping sweat gracefully", "暑いですね"),
           ("kimono beauty wrapping a scarf", "冷えますね"),
           ("kimono beauty bringing a blanket", "あったかくしてね"),
           ("kimono beauty softly smiling", "いつでもどうぞ")]),
        # Set 6: 挨拶
        m([("kimono beauty bowing in morning light", "おはようございます"),
           ("kimono beauty politely bowing at desk", "お疲れ様です"),
           ("kimono beauty waving lightly at door", "いってらっしゃい"),
           ("kimono beauty opening the sliding door", "おかえりなさい"),
           ("kimono beauty holding a tea cup waving", "またね"),
           ("kimono beauty bowing deeply at entrance", "お気をつけて"),
           ("kimono beauty looking sleepy with tea", "おやすみなさい"),
           ("kimono beauty smiling gently", "こんにちは"),
           ("kimono beauty closing sliding door", "失礼します")])
    ]),
    ("和服美人ｘ春を感じるｘ日本の伝統色（淡いピンクや萌黄色）", [
        # Set 1: 色の美しさを楽しむ
        m([("kimono beauty showing off moegi-colored kimono", "見て見て"),
           ("kimono beauty picking pale pink flowers", "春色ですね"),
           ("kimono beauty twirling slightly in kimono", "似合うかな？"),
           ("kimono beauty looking at traditional color swatches", "素敵な色"),
           ("kimono beauty pointing at bright green leaves", "鮮やか"),
           ("kimono beauty fixing her matching hair pin", "お気に入りです"),
           ("kimono beauty taking a step carefully", "お出かけしましょう"),
           ("kimono beauty enjoying the sunshine", "ぽかぽかですね"),
           ("kimono beauty gently fixing obi", "準備OK")]),
        # Set 2: 挨拶・日常
        m([("kimono beauty bowing deeply in soft pink light", "おはよう"),
           ("kimono beauty waving gently", "こんにちは"),
           ("kimono beauty bowing with elegant posture", "ありがとうございます"),
           ("kimono beauty nodding with closed eyes", "はい"),
           ("kimono beauty looking apologetic in pale green", "ごめんなさい"),
           ("kimono beauty putting hands together", "お願い"),
           ("kimono beauty pointing at self softly", "私ですか？"),
           ("kimono beauty offering a gentle open hand", "どうぞ"),
           ("kimono beauty smiling with a tilt", "どうですか？")]),
        # Set 3: リアクション
        m([("kimono beauty clapping elegantly", "すごい！"),
           ("kimono beauty widely smiling", "やったね"),
           ("kimono beauty laughing covering mouth with sleeve", "ふふっ"),
           ("kimono beauty wiping a playful tear", "うれしい"),
           ("kimono beauty looking shocked", "えっ！"),
           ("kimono beauty thinking with hand on chin", "うーん"),
           ("kimono beauty giving thumbs up", "バッチリ"),
           ("kimono beauty making OK sign", "了解です"),
           ("kimono beauty holding an X sign", "違います")]),
        # Set 4: 労いと共感
        m([("kimono beauty offering warm tea", "おつかれさま"),
           ("kimono beauty holding hands close lovingly", "大丈夫？"),
           ("kimono beauty giving a warm smile", "応援してます"),
           ("kimono beauty gently patting", "よしよし"),
           ("kimono beauty looking sad lovingly", "大変でしたね"),
           ("kimono beauty nodding empathetically", "わかります"),
           ("kimono beauty handing over a soft towel", "ひと休みしてね"),
           ("kimono beauty looking relieved", "よかったー"),
           ("kimono beauty stepping closer", "お話ききますよ")]),
        # Set 5: 季節や天気
        m([("kimono beauty feeling a nice breeze", "いい風"),
           ("kimono beauty holding an elegant wagasa", "雨ですね"),
           ("kimono beauty looking up at moving clouds", "晴れるといいな"),
           ("kimono beauty rubbing arms lightly", "少し肌寒いね"),
           ("kimono beauty fanning herself gently", "あたたかい"),
           ("kimono beauty looking at a blooming flower", "咲きましたね"),
           ("kimono beauty pointing at the bright sun", "まぶしい"),
           ("kimono beauty looking at a puddle", "水たまりに注意"),
           ("kimono beauty enjoying a calm evening", "日が長くなりましたね")]),
        # Set 6: 終わり・夜
        m([("kimono beauty bowing gently in the dusk", "また明日"),
           ("kimono beauty waving with sleeve softly", "バイバイ"),
           ("kimono beauty looking sleepy with soft eyes", "ねむい…"),
           ("kimono beauty bowing graciously", "おやすみなさい"),
           ("kimono beauty looking back", "お気をつけて"),
           ("kimono beauty smiling gracefully", "楽しんでください"),
           ("kimono beauty putting away simple fan", "おしまい"),
           ("kimono beauty resting head softly", "ゆっくり休んでね"),
           ("kimono beauty closing eyes politely", "失礼いたします")])
    ]),
    ("和服美人ｘ春を感じるｘ縁側でのうたた寝", [
        # Set 1: のんびりとした時間
        m([("kimono beauty sitting on engawa looking relaxed", "のんびり"),
           ("kimono beauty pouring tea at engawa", "お茶どうぞ"),
           ("kimono beauty stretching arms gently", "気持ちいい"),
           ("kimono beauty patting the space next to her", "隣どうぞ"),
           ("kimono beauty petting a sleeping cat on engawa", "かわいい"),
           ("kimono beauty looking at the garden peacefully", "和みますね"),
           ("kimono beauty deeply breathing the crisp air", "深呼吸"),
           ("kimono beauty swinging legs cutely", "楽しい"),
           ("kimono beauty offering a cushion", "座布団どうぞ")]),
        # Set 2: うたた寝と眠さ
        m([("kimono beauty trying to keep eyes open", "眠い…"),
           ("kimono beauty rubbing eyes gently", "うとうと"),
           ("kimono beauty resting head on hands on engawa", "寝ちゃいそう"),
           ("kimono beauty sleeping soundly wrapped in haori", "すぅすぅ"),
           ("kimono beauty waking up startled", "はっ！"),
           ("kimono beauty stretching with a sleepy face", "よく寝たー"),
           ("kimono beauty yawning covering mouth", "ふぁぁ"),
           ("kimono beauty wiping slight drool playfully", "寝てた"),
           ("kimono beauty looking sleepy with bed hair", "おはよう")] ),
        # Set 3: 日常の返答・相槌
        m([("kimono beauty nodding softly", "うんうん"),
           ("kimono beauty smiling with closed eyes", "はい"),
           ("kimono beauty showing OK sign lazily", "OKー"),
           ("kimono beauty waving hand dismissively playfully", "ムリ"),
           ("kimono beauty putting hands together softly", "お願い"),
           ("kimono beauty pointing to herself confused", "え、私？"),
           ("kimono beauty laughing relaxedly", "あはは"),
           ("kimono beauty tilting head", "なに？"),
           ("kimono beauty crossing arms playfully", "どうしようか")]),
        # Set 4: 気遣いや感謝
        m([("kimono beauty bowing gently from a seated position", "ありがとう"),
           ("kimono beauty looking apologetic slightly", "ごめんね"),
           ("kimono beauty offering a blanket", "寒くない？"),
           ("kimono beauty touching someone's shoulder softly", "お疲れ様"),
           ("kimono beauty pouring hot tea", "温まって"),
           ("kimono beauty offering a wagashi lazily", "おやつ食べる？"),
           ("kimono beauty looking worried kindly", "大丈夫かな"),
           ("kimono beauty gently smiling to encourage", "ゆっくりでいいよ"),
           ("kimono beauty nodding dependably", "任せて")]),
        # Set 5: リアクション
        m([("kimono beauty wide open eyes", "びっくり！"),
           ("kimono beauty clapping softly with a smile", "いいね"),
           ("kimono beauty sighing with relief", "よかった"),
           ("kimono beauty looking somewhat disappointed", "しょぼん"),
           ("kimono beauty cheering with a soft fist bump", "がんばって！"),
           ("kimono beauty raising hands playfully", "やった！"),
           ("kimono beauty putting hand to cheek", "あらら"),
           ("kimono beauty giving a thumbs up with a lazy smile", "最高"),
           ("kimono beauty winking playfully", "内緒ね")]),
        # Set 6: 挨拶と終了
        m([("kimono beauty waving sleepily", "またねー"),
           ("kimono beauty bowing slightly on engawa", "失礼します"),
           ("kimono beauty rubbing eyes leaving", "もう寝ます"),
           ("kimono beauty bowing properly", "おやすみなさい"),
           ("kimono beauty smiling and waving", "気をつけてね"),
           ("kimono beauty looking forward", "また遊ぼうね"),
           ("kimono beauty giving a sleepy thumbs up", "おつかれ"),
           ("kimono beauty drinking water", "おしまい"),
           ("kimono beauty neatly bowing", "ごきげんよう")])
    ]),
    ("和服美人ｘ春を感じるｘ大正ロマン・レトロモダン", [
        # Set 1: ハイカラなお出かけ
        m([("kimono beauty walking briskly in hakama", "お出かけしましょう"),
           ("kimono beauty adjusting a retro hat", "似合いますか？"),
           ("kimono beauty checking a pocket watch", "急ぎましょう"),
           ("kimono beauty holding a retro leather bag", "準備OKです"),
           ("kimono beauty looking at a classic car", "素敵ですね"),
           ("kimono beauty pointing at a western style building", "行きましょう"),
           ("kimono beauty trying on round glasses", "見えますか？"),
           ("kimono beauty twirling an elegant umbrella", "おしゃれでしょ"),
           ("kimono beauty walking proudly", "いざ出発！")]),
        # Set 2: レトロな返事と挨拶
        m([("kimono beauty saluting playfully", "承知いたしました"),
           ("kimono beauty tipping hat elegantly", "ごきげんよう"),
           ("kimono beauty bowing beautifully", "ありがとう存じます"),
           ("kimono beauty nodding with a soft smile", "はい"),
           ("kimono beauty shaking head playfully", "いいえ"),
           ("kimono beauty making an OK gesture with hands", "良きかな"),
           ("kimono beauty pointing to chin thinking", "いかがいたしましょう"),
           ("kimono beauty waving retro gloved hand", "さようなら"),
           ("kimono beauty putting finger to lips", "秘密です")]),
        # Set 3: 感情の起伏
        m([("kimono beauty gasping in surprise", "まあっ！"),
           ("kimono beauty laughing heartily", "うふふっ"),
           ("kimono beauty looking angry playfully puffing cheeks", "もうっ"),
           ("kimono beauty wiping a tear elegantly", "悲しい"),
           ("kimono beauty clapping enthusiastically", "素晴らしい！"),
           ("kimono beauty jumping slightly", "嬉しい！"),
           ("kimono beauty crossing arms looking distressed", "あきれました"),
           ("kimono beauty sighing heavily", "やれやれ"),
           ("kimono beauty holding cheeks blushing", "お恥ずかしい")]),
        # Set 4: モダンなカフェでのやり取り
        m([("kimono beauty holding a coffee cup", "お茶にしましょう"),
           ("kimono beauty cutting a hotcake gracefully", "美味しそう"),
           ("kimono beauty stirring coffee with a silver spoon", "一息つきましょう"),
           ("kimono beauty offering a cookie", "おひとつどうぞ"),
           ("kimono beauty looking at the menu excited", "何にしますか？"),
           ("kimono beauty cleaning mouth with a napkin", "ごちそうさま"),
           ("kimono beauty waiting patiently at table", "お待ちしてました"),
           ("kimono beauty paying with an old coin purse", "お会計をお願い"),
           ("kimono beauty writing in a retro notebook", "メモしておきますわ")]),
        # Set 5: 労いと共感
        m([("kimono beauty handing over a soft towel", "お疲れ様です"),
           ("kimono beauty holding hands warmly", "頑張りましたね"),
           ("kimono beauty giving thumbs up in hakama", "その調子！"),
           ("kimono beauty looking sincerely worried", "大丈夫ですか？"),
           ("kimono beauty lightly patting shoulder", "ご無理なさらず"),
           ("kimono beauty offering medicine softly", "お大事に"),
           ("kimono beauty looking relieved", "安心しましたわ"),
           ("kimono beauty cheering with a flag", "フレー！フレー！"),
           ("kimono beauty softly smiling", "いつでも頼ってね")]),
        # Set 6: 会話の終わりと夜
        m([("kimono beauty looking at a starry sky with binoculars", "綺麗ですわね"),
           ("kimono beauty bowing elegantly in the evening", "お休みなさいませ"),
           ("kimono beauty walking away turning back softly", "またお会いしましょう"),
           ("kimono beauty waving a lace handkerchief", "ごきげんよう"),
           ("kimono beauty closing a pocket watch", "お別れの刻ですね"),
           ("kimono beauty looking sleepy with a book", "眠りにつきます"),
           ("kimono beauty holding a classical lamp", "お気をつけて"),
           ("kimono beauty smiling with a polite bow", "失礼いたします"),
           ("kimono beauty standing under a gas light", "またね")])
    ]),
    ("和服美人ｘ春を感じるｘ庭園に集まる小鳥", [
        # Set 1: 小鳥とのふれあい
        m([("kimono beauty feeding a little bird on hand", "よく来たね"),
           ("kimono beauty pointing softly at a singing bird", "歌ってますね"),
           ("kimono beauty looking around the garden happily", "見つけてみて"),
           ("kimono beauty holding finger up 'shh' for the bird", "しーっ"),
           ("kimono beauty smiling at a bird landing on her shoulder", "あらあら"),
           ("kimono beauty placing seeds on a stone", "どうぞ"),
           ("kimono beauty watching birds fly away", "いってらっしゃい"),
           ("kimono beauty bringing hands to cheeks amazed", "かわいいっ"),
           ("kimono beauty waving gently at a bird", "おーい")]),
        # Set 2: 挨拶と日頃のやりとり
        m([("kimono beauty bowing with a bird nearby", "おはようございます"),
           ("kimono beauty nodding and smiling", "はい"),
           ("kimono beauty shaking head kindly", "ううん"),
           ("kimono beauty making an OK sign gracefully", "OKです"),
           ("kimono beauty putting hands together thankfully", "ありがとうございます"),
           ("kimono beauty politely bowing", "ごめんなさい"),
           ("kimono beauty softly pointing to herself", "私ですか？"),
           ("kimono beauty handing over an item gently", "どうぞ"),
           ("kimono beauty tilting head lightly", "どうしました？")]),
        # Set 3: リアクション
        m([("kimono beauty wide eyes in surprise", "ええっ！"),
           ("kimono beauty laughing covering mouth", "ふふっ"),
           ("kimono beauty clapping softly with joy", "やったー"),
           ("kimono beauty wiping an invisible tear playfully", "悲しい"),
           ("kimono beauty sighing with relief", "ほっとしました"),
           ("kimono beauty giving thumbs up", "いいね！"),
           ("kimono beauty crossing arms playfully", "だめですよ"),
           ("kimono beauty looking incredibly happy", "嬉しい"),
           ("kimono beauty striking a confident pose", "まかせて！")]),
        # Set 4: 労いと慰め
        m([("kimono beauty offering a warm towel", "おつかれさま"),
           ("kimono beauty holding her hands gently", "大丈夫？"),
           ("kimono beauty looking kindly into eyes", "応援してるよ"),
           ("kimono beauty lightly rubbing back", "無理しないで"),
           ("kimono beauty offering a cup of tea", "休憩しましょう"),
           ("kimono beauty sending a supportive smile", "がんばって"),
           ("kimono beauty giving a small fist pump", "ファイト！"),
           ("kimono beauty looking relieved", "よかったー"),
           ("kimono beauty holding out an umbrella", "雨降ってきた")]),
        # Set 5: 季節と時間
        m([("kimono beauty looking up at the warm sun", "ぽかぽかですね"),
           ("kimono beauty stretching gently in the breeze", "のびのび"),
           ("kimono beauty smelling a spring flower", "いい香り"),
           ("kimono beauty listening to the wind", "春の音ですね"),
           ("kimono beauty looking at a pocket watch", "時間ですよ"),
           ("kimono beauty pointing at the falling sun", "夕暮れですね"),
           ("kimono beauty looking sleepy", "うとうと"),
           ("kimono beauty enjoying the silence", "静かですね"),
           ("kimono beauty walking gracefully", "散歩しましょう")]),
        # Set 6: 終わりと夜
        m([("kimono beauty waving goodbye with birds flying", "またね"),
           ("kimono beauty bowing warmly at dusk", "お気をつけて"),
           ("kimono beauty returning inside sliding door", "お邪魔しました"),
           ("kimono beauty softly waving", "バイバイ"),
           ("kimono beauty looking sleepy with a slight bow", "おやすみなさい"),
           ("kimono beauty bowing deeply", "失礼します"),
           ("kimono beauty smiling with a lantern", "足元に気をつけて"),
           ("kimono beauty looking softly over her shoulder", "また明日"),
           ("kimono beauty gently fixing her hair", "おしまい")])
    ]),
    ("和服美人ｘ春を感じるｘお花見弁当の彩り", [
        # Set 1: お弁当の準備と披露
        m([("kimono beauty proudly showing a colorful bento", "じゃーん！"),
           ("kimono beauty opening a bento box elegantly", "開けますよ"),
           ("kimono beauty handing over chopsticks", "食べてみて"),
           ("kimono beauty offering a rice ball", "どうぞ"),
           ("kimono beauty spreading a picnic sheet", "ここに座ろう"),
           ("kimono beauty packing the lunch elegantly", "準備OKです"),
           ("kimono beauty adjusting the heavy bento boxes", "重いっ"),
           ("kimono beauty looking at the bento happily", "美味しそう"),
           ("kimono beauty pouring drinks", "乾杯！")]),
        # Set 2: 食事中・感想
        m([("kimono beauty eating with a happy smile", "おいしい！"),
           ("kimono beauty holding cheeks in delight", "ほっぺが落ちそう"),
           ("kimono beauty wiping mouth carefully with napkin", "ごちそうさまでした"),
           ("kimono beauty patting full stomach happily", "お腹いっぱい"),
           ("kimono beauty offering more food playfully", "おかわりは？"),
           ("kimono beauty looking disappointed at an empty box", "全部食べちゃった"),
           ("kimono beauty chewing happily with closed eyes", "もぐもぐ"),
           ("kimono beauty putting hands together softly", "いただきます"),
           ("kimono beauty sipping tea after eating", "ふぅ")]),
        # Set 3: 挨拶と日常会話
        m([("kimono beauty waving under the cherry tree", "おはよう"),
           ("kimono beauty nodding cheerfully", "うんうん"),
           ("kimono beauty shaking head kindly", "ちがうよ"),
           ("kimono beauty giving OK sign with chopsticks", "りょうかい"),
           ("kimono beauty giving an X sign with arms", "ダメです"),
           ("kimono beauty bowing softly seated", "ありがとうございます"),
           ("kimono beauty humbly putting hands together", "ごめんなさい"),
           ("kimono beauty tilting head completely puzzled", "えっ？"),
           ("kimono beauty winking happily", "内緒です")]),
        # Set 4: 感情表現
        m([("kimono beauty laughing covering mouth", "あはは"),
           ("kimono beauty acting surprised with mouth open", "ほんとに！？"),
           ("kimono beauty tearing up in joy", "嬉しいっ"),
           ("kimono beauty pouting slightly", "もうっ"),
           ("kimono beauty clapping excitedly", "すごいすごい"),
           ("kimono beauty sighing with a gentle smile", "やれやれ"),
           ("kimono beauty making a fist bump gesture", "最高！"),
           ("kimono beauty offering a friendly high five", "イェイ！"),
           ("kimono beauty staring intently with glowing eyes", "じーっ")]),
        # Set 5: 労いと気づかい
        m([("kimono beauty offering tea with a smile", "おつかれさま"),
           ("kimono beauty giving thumbs up enthusiastically", "がんばって！"),
           ("kimono beauty looking worried kindly", "無理してない？"),
           ("kimono beauty patting someone's shoulder", "よしよし"),
           ("kimono beauty opening a wagasa for shade", "眩しいね"),
           ("kimono beauty waving a fan gently", "暑くない？"),
           ("kimono beauty offering a soft blanket", "冷えるからどうぞ"),
           ("kimono beauty nodding with reassurance", "大丈夫ですよ"),
           ("kimono beauty giving an encouraging smile", "いつでも呼んでね")]),
        # Set 6: 撤収と帰り道
        m([("kimono beauty packing up the empty boxes", "片付けますね"),
           ("kimono beauty standing up dusting herself off", "さあ行こう"),
           ("kimono beauty waving happily on the way back", "また行こうね"),
           ("kimono beauty looking back with a sunset background", "楽しかった"),
           ("kimono beauty bowing politely", "お気をつけて"),
           ("kimono beauty rubbing eyes tiredly", "眠くなってきちゃった"),
           ("kimono beauty bowing deeply gracefully", "おやすみなさい"),
           ("kimono beauty smiling softly leaving", "またね"),
           ("kimono beauty waving enthusiastically", "バイバイ！")])
    ])
]
