def m(data):
    return " ".join([f'P{i+1}: ACTION/PROPS="{a}" | TEXT="{t}"' for i, (a, t) in enumerate(data)])

themes = [
    ("和服美人ｘ春を感じるｘしっとり濡れる菜種梅雨", [
        # Set 1: 雨の風情
        m([("kimono beauty holding a traditional wagasa in the rain", "雨ですね"),
           ("kimono beauty looking up at a grey sky gently", "降りそうです"),
           ("kimono beauty extending hand to catch rain softly", "冷たい"),
           ("kimono beauty holding blooming hydrangeas gracefully", "綺麗に咲いてます"),
           ("kimono beauty listening to the sound of rain", "静かですね"),
           ("kimono beauty looking out from the engawa on a rainy day", "のんびりしましょう"),
           ("kimono beauty gently walking avoiding puddles", "足元ご用心"),
           ("kimono beauty smiling with a wet kimono sleeve", "濡れちゃった"),
           ("kimono beauty bringing an extra umbrella kindly", "傘どうぞ")]),
        # Set 2: 挨拶と日常
        m([("kimono beauty bowing deeply with a calm aura", "おはようございます"),
           ("kimono beauty waving softly under an umbrella", "こんにちは"),
           ("kimono beauty elegantly putting hands together", "ありがとうございます"),
           ("kimono beauty holding kimono collar apologetically", "ごめんなさい"),
           ("kimono beauty nodding with closed eyes", "はい"),
           ("kimono beauty shaking head kindly", "ううん"),
           ("kimono beauty smiling with an OK hand sign", "OKです"),
           ("kimono beauty offering an open hand", "どうぞ"),
           ("kimono beauty tilting head curiously", "どうしたの？")]),
        # Set 3: 感情
        m([("kimono beauty laughing covering mouth delicately", "ふふっ"),
           ("kimono beauty weeping softly wiping a tear", "悲しい"),
           ("kimono beauty clutching chest in relief", "よかった"),
           ("kimono beauty holding cheeks blushing", "恥ずかしい"),
           ("kimono beauty clapping softly rejoicing", "うれしい"),
           ("kimono beauty looking surprised with wide eyes", "えっ！"),
           ("kimono beauty looking slightly annoyed playfully", "もうっ"),
           ("kimono beauty giving a confident wink", "まかせて"),
           ("kimono beauty making a fist bump gesture gently", "やったね")]),
        # Set 4: 労いと共感
        m([("kimono beauty handing a warm towel kindly", "濡れませんでしたか？"),
           ("kimono beauty offering a hot cup of tea gently", "温まって"),
           ("kimono beauty actively listening with a nod", "うんうん"),
           ("kimono beauty looking sympathetically", "大変でしたね"),
           ("kimono beauty softly patting shoulder", "お疲れ様"),
           ("kimono beauty raising hands in support", "応援してます"),
           ("kimono beauty making a strong reassuring nod", "大丈夫"),
           ("kimono beauty gently handing over medicine", "無理しないで"),
           ("kimono beauty gently stretching arms", "ひと休み")]),
        # Set 5: その他返答
        m([("kimono beauty thinking with a hand on cheek", "そうですね"),
           ("kimono beauty putting hands together pleadingly", "お願い"),
           ("kimono beauty pointing away gracefully", "あっち"),
           ("kimono beauty pointing to herself", "私？"),
           ("kimono beauty giving a thumbs up", "いいね"),
           ("kimono beauty giving a crossed arms X sign", "違います"),
           ("kimono beauty using a calculator", "計算中"),
           ("kimono beauty holding an hourglass", "お待ちください"),
           ("kimono beauty bowing humbly", "お世話になります")]),
        # Set 6: 別れと夜
        m([("kimono beauty turning back softly calling out", "また明日"),
           ("kimono beauty waving politely in the evening mist", "さようなら"),
           ("kimono beauty bowing courteously at a door", "お気をつけて"),
           ("kimono beauty holding a lantern in the rain", "暗くなりました"),
           ("kimono beauty softly rubbing eyes sleepily", "眠いです"),
           ("kimono beauty lowering head gracefully", "おやすみなさい"),
           ("kimono beauty softly closing the window", "戸締り忘れずに"),
           ("kimono beauty smiling as the rain stops", "止みましたね"),
           ("kimono beauty waving gently disappearing into mist", "バイバイ")])
    ]),
    ("和服美人ｘ春を感じるｘ京都・鎌倉の寺社巡り", [
        # Set 1: 観光とお寺の雰囲気
        m([("kimono beauty praying at a shrine with hands together", "お参り"),
           ("kimono beauty throwing a coin into an offering box", "お願いごと"),
           ("kimono beauty drawing an omikuji fortune slip excitedly", "大吉でした！"),
           ("kimono beauty reading a goshuin quietly", "御朱印いただきました"),
           ("kimono beauty standing in front of red torii gates", "綺麗ですね"),
           ("kimono beauty bringing hands to cheeks amazed", "すごい"),
           ("kimono beauty pointing at an old temple", "歴史を感じます"),
           ("kimono beauty eating dango on a temple bench", "一休み"),
           ("kimono beauty ringing a gentle temple bell softly", "ゴーン")]),
        # Set 2: 挨拶と日頃のやりとり
        m([("kimono beauty bowing politely at the temple gate", "おはようございます"),
           ("kimono beauty waving a fan lightly", "こんにちは"),
           ("kimono beauty deeply bowing", "ありがとうございます"),
           ("kimono beauty bowing with hands tight", "申し訳ございません"),
           ("kimono beauty holding an OK sign with a smile", "了解です"),
           ("kimono beauty nodding calmly", "はい"),
           ("kimono beauty making an X sign playfully", "ダメですよ"),
           ("kimono beauty giving a thumbs up graciously", "バッチリ"),
           ("kimono beauty presenting with an open hand", "どうぞ")]),
        # Set 3: 感情
        m([("kimono beauty covering mouth while laughing", "うふふ"),
           ("kimono beauty shedding a tear touchingly", "感動しました"),
           ("kimono beauty looking happy with an omamori", "うれしい"),
           ("kimono beauty holding her head shocked", "信じられない"),
           ("kimono beauty clapping softly in delight", "やったー"),
           ("kimono beauty tilting head curiously", "どうしたの？"),
           ("kimono beauty looking up at a bright sky", "いいお天気"),
           ("kimono beauty blushing warmly", "照れます"),
           ("kimono beauty posing with a peace sign elegantly", "イェイ")]),
        # Set 4: 気遣い・いたわり
        m([("kimono beauty bringing a cup of cold tea", "喉渇いてない？"),
           ("kimono beauty softly wiping sweat from brow", "歩き疲れましたか"),
           ("kimono beauty fanning herself gently", "暑いですね"),
           ("kimono beauty holding someone's hand supportively", "一緒に頑張ろう"),
           ("kimono beauty offering a comforting smile", "おつかれさま"),
           ("kimono beauty looking concerned quietly", "大丈夫？"),
           ("kimono beauty giving an energetic wave", "がんばれ！"),
           ("kimono beauty rubbing her shoulders", "足が棒です"),
           ("kimono beauty looking relieved", "着きましたー")]),
        # Set 5: その他返答やリアクション
        m([("kimono beauty pointing far ahead", "あそこです"),
           ("kimono beauty holding up a camera playfully", "写真撮りますよ"),
           ("kimono beauty adjusting obi belt properly", "ちょっと待って"),
           ("kimono beauty thinking with finger on cheek", "どこ行こうか"),
           ("kimono beauty pointing firmly", "決定！"),
           ("kimono beauty turning around with a big smile", "こっちこっち"),
           ("kimono beauty clapping hands once cleanly", "決まりですね"),
           ("kimono beauty looking closely at a map", "迷子かも"),
           ("kimono beauty holding hands helplessly", "どうしよう")]),
        # Set 6: 別れの挨拶や夜の風景
        m([("kimono beauty admiring an illuminated temple", "幻想的です"),
           ("kimono beauty bowing under a stone lantern", "お気をつけて"),
           ("kimono beauty softly waving goodbye at the station", "また来ましょうね"),
           ("kimono beauty thanking with a deep bow", "お世話になりました"),
           ("kimono beauty rubbing sleepy eyes", "おやすみなさい"),
           ("kimono beauty walking away gracefully", "さようなら"),
           ("kimono beauty extending a hand for a handshake lightly", "またね"),
           ("kimono beauty looking peacefully at dusk", "夕暮れですね"),
           ("kimono beauty packing her bag neatly", "帰りましょう")])
    ]),
    ("和服美人ｘ春を感じるｘ幻想的な夜桜", [
        # Set 1: 夜桜と幻想的な雰囲気
        m([("kimono beauty looking up at illuminated sakura in awe", "綺麗…"),
           ("kimono beauty smiling softly holding a lantern", "幻想的です"),
           ("kimono beauty pointing to the bright moon and sakura", "月が綺麗ですね"),
           ("kimono beauty reaching for falling petals at night", "つかまえた"),
           ("kimono beauty holding a cup of hot sake under the moon", "乾杯"),
           ("kimono beauty breathing in the night air deeply", "夜風が気持ちいい"),
           ("kimono beauty turning around in the magical light", "夢みたい"),
           ("kimono beauty bringing hands to chest happily", "うっとり"),
           ("kimono beauty bringing a finger to lips under sakura", "シーッ")]),
        # Set 2: 挨拶と日頃のやりとり
        m([("kimono beauty bowing gently in the lamp light", "こんばんは"),
           ("kimono beauty bowing deeply with respect", "ありがとうございます"),
           ("kimono beauty slightly lowering head looking sad", "ごめんなさい"),
           ("kimono beauty nodding with closed eyes", "はい"),
           ("kimono beauty firmly shaking head", "いいえ"),
           ("kimono beauty giving OK sign with a soft smile", "OKです"),
           ("kimono beauty giving an X shape with fingers", "だめです"),
           ("kimono beauty making a pleading pose with hands together", "お願い"),
           ("kimono beauty cheerfully waving hand", "ヤッホー")]),
        # Set 3: 喜怒哀楽の表現
        m([("kimono beauty covering mouth laughing elegantly", "ふふっ"),
           ("kimono beauty wiping a tear playfully", "えーん"),
           ("kimono beauty puffing cheeks angrily", "もうっ！"),
           ("kimono beauty looking surprised holding hands to face", "びっくり"),
           ("kimono beauty sighing with a gentle relief", "よかったー"),
           ("kimono beauty jumping slightly for joy", "やった！"),
           ("kimono beauty holding face with a blush", "はずかしい"),
           ("kimono beauty looking absolutely exhausted", "疲れたぁ"),
           ("kimono beauty nodding vigorously", "間違いない")]),
        # Set 4: 労いとお疲れ様
        m([("kimono beauty passing to a warm drink cheerfully", "お疲れ様です"),
           ("kimono beauty giving an energetic thumbs up", "がんばって"),
           ("kimono beauty touching a shoulder supportively", "無理しないでね"),
           ("kimono beauty looking softly and lovingly", "えらいえらい"),
           ("kimono beauty holding a blanket over someone", "冷えますね"),
           ("kimono beauty acting genuinely concerned", "大丈夫？"),
           ("kimono beauty gently smiling to encourage", "私がついてます"),
           ("kimono beauty warmly looking into eyes", "安心してください"),
           ("kimono beauty lightly rubbing her own neck", "こりましたー")]),
        # Set 5: リアクション
        m([("kimono beauty raising hand elegantly", "はーい"),
           ("kimono beauty thinking with a hand delicately on chin", "考え中…"),
           ("kimono beauty using a abacus or calculator", "計算します"),
           ("kimono beauty pointing straight forward proudly", "決まり！"),
           ("kimono beauty clapping enthusiastically", "すごーい"),
           ("kimono beauty softly poking a friend playfully", "ねえねえ"),
           ("kimono beauty tilting head curiously with a smile", "本当？"),
           ("kimono beauty crossing arms playfully", "どうしようかしら"),
           ("kimono beauty pointing cheerfully to something", "あそこ！")]),
        # Set 6: お別れや就寝
        m([("kimono beauty waving gently under the cherry blossoms", "また明日"),
           ("kimono beauty taking a bow deeply", "お気をつけて"),
           ("kimono beauty sleeping softly against a tree", "スヤスヤ"),
           ("kimono beauty rubbing eyes sleepily", "おやすみなさい"),
           ("kimono beauty blowing out the lantern gracefully", "もう寝ます"),
           ("kimono beauty looking softly regretful to leave", "名残惜しいです"),
           ("kimono beauty walking away gracefully", "失礼します"),
           ("kimono beauty raising hand in a small wave", "バイバイ"),
           ("kimono beauty stretching sleepily", "よく遊びました")])
    ]),
    ("和服美人ｘ春を感じるｘ風に舞う花びら", [
        # Set 1: 風と花びら
        m([("kimono beauty catching a pink petal in her hands", "春風ですね"),
           ("kimono beauty dancing softly surrounded by petals", "舞い散る花びら"),
           ("kimono beauty holding her hat/hair in the wind", "風が強い！"),
           ("kimono beauty looking up at a petal storm happily", "桜吹雪です"),
           ("kimono beauty picking a petal out of her hair", "髪についてた"),
           ("kimono beauty pointing up at the sky", "飛んでいく"),
           ("kimono beauty closing eyes feeling the breeze", "気持ちいい"),
           ("kimono beauty spinning playfully in the petals", "わぁーっ"),
           ("kimono beauty carrying blowing petals playfully", "綺麗")]),
        # Set 2: 挨拶と日頃のやりとり
        m([("kimono beauty waving cheerfully in a light wind", "おはよう"),
           ("kimono beauty bowing politely", "ありがとうございます"),
           ("kimono beauty nodding with a very bright smile", "はい！"),
           ("kimono beauty shaking head kindly closing eyes", "違うよ"),
           ("kimono beauty looking politely apologetic", "ごめんなさい"),
           ("kimono beauty making an OK sign proudly", "OK"),
           ("kimono beauty putting hands together begging cutely", "お願い"),
           ("kimono beauty offering her palm softly", "どうぞ"),
           ("kimono beauty tilting her head curiously", "どうしたの？")]),
        # Set 3: 感情の表現
        m([("kimono beauty covering mouth to giggle softly", "ふふっ"),
           ("kimono beauty looking shocked opening mouth wide", "ええっ！"),
           ("kimono beauty clapping her hands softly", "やったー"),
           ("kimono beauty crying playfully wiping a small tear", "悲しい"),
           ("kimono beauty sighing heavily gently smiling", "やれやれ"),
           ("kimono beauty touching cheeks blushing", "照れるな"),
           ("kimono beauty acting disappointed pouting", "ちぇっ"),
           ("kimono beauty showing thumbs up", "最高！"),
           ("kimono beauty winking confidently", "任せて")]),
        # Set 4: 労いと気づかい
        m([("kimono beauty passing a soft handkerchief", "おつかれさま"),
           ("kimono beauty bringing warm tea", "ひと休みして"),
           ("kimono beauty giving encouraging smile with fist pump", "がんばれ！"),
           ("kimono beauty lovingly holding her hands together", "大丈夫？"),
           ("kimono beauty softly patting someone's shoulder", "無理しないで"),
           ("kimono beauty looking deeply relieved", "よかったー"),
           ("kimono beauty supporting lovingly", "応援してます"),
           ("kimono beauty softly dusting a shoulder", "汚れが"),
           ("kimono beauty looking affectionately", "えらいね")]),
        # Set 5: その他リアクション
        m([("kimono beauty pointing happily", "あっち！"),
           ("kimono beauty resting head on hand thinking", "うーん"),
           ("kimono beauty making an X sign gently with arms", "ダメです"),
           ("kimono beauty softly calling out to someone", "ねぇねぇ"),
           ("kimono beauty holding slightly on the obi gracefully", "ちょっと待って"),
           ("kimono beauty turning back smiling widely", "いくよー！"),
           ("kimono beauty clapping enthusiastically", "すごい！"),
           ("kimono beauty waving an empty hand playfully", "ないよ"),
           ("kimono beauty raising her hand gracefully", "はい！")]),
        # Set 6: 終わりとお別れ
        m([("kimono beauty waving as she walks away softly", "またね"),
           ("kimono beauty bowing softly gracefully saying goodbye", "さようなら"),
           ("kimono beauty politely extending her arm", "お気をつけて"),
           ("kimono beauty rubbing eyes sleepily", "ねむい"),
           ("kimono beauty yawning into a sleeve", "ふぁぁ"),
           ("kimono beauty bowing elegantly downwards", "おやすみなさい"),
           ("kimono beauty turning off a small lamp", "暗くなってきたね"),
           ("kimono beauty stretching comfortably", "終わりましたー"),
           ("kimono beauty smiling with closed eyes", "失礼します")])
    ]),
    ("和服美人ｘ春を感じるｘ雛祭りと桃の花", [
        # Set 1: 雛祭りの準備とお祝い
        m([("kimono beauty delicately arranging a hina doll", "飾りました"),
           ("kimono beauty admiring peach blossoms", "桃の節句ですね"),
           ("kimono beauty offering hishi mochi softly", "どうぞ召し上がれ"),
           ("kimono beauty drinking sweet shirozake safely", "美味しい"),
           ("kimono beauty clasping hands in happiness looking at dolls", "綺麗ですね"),
           ("kimono beauty offering hina arare playfully", "あられ食べる？"),
           ("kimono beauty wearing an elegant bright kimono warmly", "春らしいでしょ"),
           ("kimono beauty pointing lovingly to the emperor doll", "お内裏様"),
           ("kimono beauty gracefully bowing near the dolls", "おめでとう")]),
        # Set 2: 挨拶と日頃のやりとり
        m([("kimono beauty waving gently with an elegant smile", "おはよう"),
           ("kimono beauty politely bowing", "ありがとうございます"),
           ("kimono beauty softly putting hands together apologetically", "ごめんなさい"),
           ("kimono beauty nodding cheerfully", "はい"),
           ("kimono beauty shaking head kindly", "いいえ"),
           ("kimono beauty throwing an OK sign cheerfully", "OKです"),
           ("kimono beauty holding hands closely requesting", "おねがい"),
           ("kimono beauty extending an open hand to offer", "どうぞ"),
           ("kimono beauty playfully putting a finger to lips", "ないしょ")]),
        # Set 3: リアクション
        m([("kimono beauty gently holding cheeks covering a laugh", "ふふっ"),
           ("kimono beauty acting highly surprised", "まあ！"),
           ("kimono beauty clasping hands together in joy", "やったー"),
           ("kimono beauty slightly shedding a joyful tear", "嬉しい"),
           ("kimono beauty looking clearly sad pouting", "残念"),
           ("kimono beauty confidently striking a small pose", "任せて"),
           ("kimono beauty gently holding her obi in thought", "どうしようかしら"),
           ("kimono beauty giving a small thumbs up gracefully", "完璧です"),
           ("kimono beauty making an X playfully", "ちがうよ")]),
        # Set 4: 気遣いや感謝
        m([("kimono beauty offering a gentle towel thoughtfully", "お疲れ様です"),
           ("kimono beauty looking affectionately concerned", "大丈夫？"),
           ("kimono beauty cheering with a small flag gently", "がんばって"),
           ("kimono beauty holding tea offering warmth", "休んでね"),
           ("kimono beauty warmly looking up at you", "えらいです"),
           ("kimono beauty lovingly softly touching a shoulder", "応援しています"),
           ("kimono beauty sighing together in relief softly", "安心しました"),
           ("kimono beauty extending an arm supportively", "一緒にいこ"),
           ("kimono beauty softly bowing gracefully", "いつもありがとう")]),
        # Set 5: リアクション2
        m([("kimono beauty softly poking a friend to call", "ねえねえ"),
           ("kimono beauty holding an open face thinking", "んー？"),
           ("kimono beauty gently waving hands negatively", "とんでもない"),
           ("kimono beauty raising an elegant hand", "はいっ"),
           ("kimono beauty heavily enthusiastically clapping", "すごいすごい！"),
           ("kimono beauty checking a small watch gently", "時間です"),
           ("kimono beauty writing a note diligently", "メモメモ"),
           ("kimono beauty lightly pulling your sleeve", "こっちだよ"),
           ("kimono beauty cheerfully looking around", "どこですかー")]),
        # Set 6: 別れと就寝
        m([("kimono beauty politely waving goodbye gracefully", "またね"),
           ("kimono beauty taking a deep respectful bow", "お気をつけて"),
           ("kimono beauty softly waving looking back", "さようなら"),
           ("kimono beauty wiping sleepy eyes softly", "ねむい"),
           ("kimono beauty lightly yawning politely covering mouth", "ふぁぁ"),
           ("kimono beauty peacefully gracefully bowing to sleep", "おやすみなさい"),
           ("kimono beauty holding a warm candle lantern", "夜になりました"),
           ("kimono beauty softly smiling going away", "楽しかったです"),
           ("kimono beauty quietly closing the doors softly", "失礼いたします")])
    ]),
    ("和服美人ｘ春を感じるｘ春の味覚（苺や筍）", [
        # Set 1: 春の味覚
        m([("kimono beauty holding a shiny red strawberry happily", "いちご！"),
           ("kimono beauty eating a tasty strawberry", "甘くて美味しい"),
           ("kimono beauty admiring freshly dug bamboo shoots", "筍ですね"),
           ("kimono beauty holding a bowl of bamboo shoot rice", "筍ご飯です"),
           ("kimono beauty holding cheeks with both hands delightfully", "最高ですね"),
           ("kimono beauty offering a shiny strawberry gently", "あーん"),
           ("kimono beauty holding an empty bowl pleadingly", "おかわり"),
           ("kimono beauty gently patting her stomach", "お腹いっぱい"),
           ("kimono beauty placing hands gracefully together", "いただきます")]),
        # Set 2: 挨拶と日頃のやりとり
        m([("kimono beauty cheerfully waving in the kitchen", "おはよう"),
           ("kimono beauty firmly nodding", "はい"),
           ("kimono beauty smoothly shaking her head safely", "ううん"),
           ("kimono beauty happily giving an OK hand sign", "OKです"),
           ("kimono beauty politely respectfully bowing", "ありがとうございます"),
           ("kimono beauty gently humbly lowering her head", "ごめんなさい"),
           ("kimono beauty holding an X with arms cleanly", "だめです"),
           ("kimono beauty making a begging hands gesture", "おねがい"),
           ("kimono beauty cleanly pointing to herself", "私ですか？")]),
        # Set 3: 喜怒哀楽の表現
        m([("kimono beauty putting a hand to mouth laughing quietly", "ふふっ"),
           ("kimono beauty throwing open eyes incredibly shocked", "えっ！"),
           ("kimono beauty pumping a small fist confidently", "やったー"),
           ("kimono beauty softly looking down shedding a small tear", "悲しい"),
           ("kimono beauty acting playfully annoyed puffing cheeks", "もうっ"),
           ("kimono beauty holding an enthusiastic thumbs up", "いいね！"),
           ("kimono beauty showing peace sign elegantly", "イェイ"),
           ("kimono beauty giving a relieved light sigh", "よかった"),
           ("kimono beauty holding hands to blushing cheeks", "照れます")]),
        # Set 4: 労いとお気遣い
        m([("kimono beauty holding out warm wet towel kindly", "お疲れ様です"),
           ("kimono beauty showing loving worried face", "大丈夫？"),
           ("kimono beauty passing to a drink supportively", "休んでください"),
           ("kimono beauty gently lifting arms dynamically", "がんばれ！"),
           ("kimono beauty looking softly supportively", "応援してます"),
           ("kimono beauty holding medicine box politely", "お大事に"),
           ("kimono beauty giving soft confirming nods", "焦らずに"),
           ("kimono beauty taking shoulder kindly safely", "無理しないで"),
           ("kimono beauty wiping off brow playfully", "頑張ったね")]),
        # Set 5: その他返答やアクション
        m([("kimono beauty thinking putting finger on chin elegantly", "うーん"),
           ("kimono beauty excitedly softly raising hand", "はーい"),
           ("kimono beauty heavily looking at clock surprisingly", "急がなきゃ"),
           ("kimono beauty happily warmly pointing away", "あっち"),
           ("kimono beauty enthusiastically warmly clapping", "すごい！"),
           ("kimono beauty holding sleeve gently poking", "ねえねえ"),
           ("kimono beauty looking blankly confused tilting head", "ん？"),
           ("kimono beauty holding stomach sadly lightly hungry", "お腹すいた"),
           ("kimono beauty happily pulling something from sleeve", "じゃーん")]),
        # Set 6: お別れや就寝
        m([("kimono beauty happily excitedly waving goodbye", "また明日"),
           ("kimono beauty respectfully deeply safely bowing", "お気をつけて"),
           ("kimono beauty softly lovingly looking back", "さようなら"),
           ("kimono beauty looking visibly tired sleepy", "疲れちゃった"),
           ("kimono beauty softly rubbing a sleepy eye", "ねむい"),
           ("kimono beauty properly taking a sitting bow", "おやすみなさい"),
           ("kimono beauty raising hands for a stretch", "一日終わり"),
           ("kimono beauty securely properly locking door playfully", "戸締りヨシ"),
           ("kimono beauty safely softly blowing out a candle", "失礼します")])
    ]),
    ("和服美人ｘ春を感じるｘ季節の挨拶と丁寧な言葉", [
        # Set 1: 四季の挨拶・丁寧な言葉
        m([("kimono beauty deeply formally bowing from seated position", "春暖の候"),
           ("kimono beauty respectfully presenting an envelope", "お伺い申し上げます"),
           ("kimono beauty warmly looking up politely", "ご無沙汰しております"),
           ("kimono beauty deeply lowering her head elegantly", "厚く御礼申し上げます"),
           ("kimono beauty gracefully bowing on the engawa", "つつがなくお過ごしでしょうか"),
           ("kimono beauty politely raising hand slightly", "お招きいただき感謝いたします"),
           ("kimono beauty bowing slightly graciously standing", "ご機嫌伺い申し上げます"),
           ("kimono beauty warmly cheerfully looking polite", "暖かくなってまいりました"),
           ("kimono beauty holding a beautifully written letter", "拝啓")]),
        # Set 2: 実用的な日常挨拶
        m([("kimono beauty cheerfully safely gracefully bowing", "おはようございます"),
           ("kimono beauty looking professionally smiling smoothly", "お疲れ様でございます"),
           ("kimono beauty deeply confidently gracefully agreeing", "承知いたしました"),
           ("kimono beauty elegantly safely politely declining", "結構でございます"),
           ("kimono beauty gracefully safely warmly saying thanks", "ありがとうございます"),
           ("kimono beauty holding hands pleading deeply securely", "申し訳ございません"),
           ("kimono beauty bringing politely open hands offering", "どうぞごゆっくり"),
           ("kimono beauty bowing professionally humbly cleanly", "よろしくお願いいたします"),
           ("kimono beauty properly nodding professionally", "かしこまりました")]),
        # Set 3: 感情表現
        m([("kimono beauty elegantly covering mouth to smile happily", "喜ばしいです"),
           ("kimono beauty putting hands affectionately happily gracefully", "感動いたしました"),
           ("kimono beauty deeply sincerely expressing sad feelings softly", "残念でございます"),
           ("kimono beauty looking very deeply safely touched", "恐悦至極に存じます"),
           ("kimono beauty warmly proudly safely giving thumbs up", "素晴らしいです"),
           ("kimono beauty heavily lightly holding breath in awe", "お見事です"),
           ("kimono beauty blushing warmly politely gratefully", "恐縮です"),
           ("kimono beauty holding gracefully firmly hand lightly safely", "お気になさらず"),
           ("kimono beauty gently comfortably giving a deep sigh", "安堵いたしました")]),
        # Set 4: 労いとお気遣い
        m([("kimono beauty respectfully pouring hot green tea safely", "お茶をどうぞ"),
           ("kimono beauty warmly passionately supporting lovingly", "ご健勝をお祈りしております"),
           ("kimono beauty looking deeply sympathetically lightly", "ご自愛くださいませ"),
           ("kimono beauty showing deeply caring face gently", "ご心配には及びません"),
           ("kimono beauty gently patting affectionately supporting", "ご無理なさいませんよう"),
           ("kimono beauty making an elegant safely fighting pose", "ご活躍を祈念いたします"),
           ("kimono beauty handling gently softly with loving care", "お力落としのなきよう"),
           ("kimono beauty brightly giving supportive polite gaze", "陰ながら応援しております"),
           ("kimono beauty softly politely leaning affectionately", "いつでもご用命ください")]),
        # Set 5: リアクション
        m([("kimono beauty looking pleasantly beautifully surprised gently", "これは驚きました"),
           ("kimono beauty clapping softly purely gracefully cleanly", "見事な手際です"),
           ("kimono beauty gently comfortably looking gracefully curiously down", "いかがなさいましたか"),
           ("kimono beauty holding hand closely gently safely to cheek", "考えさせてください"),
           ("kimono beauty pointing professionally clearly cleanly away", "あちらでございます"),
           ("kimono beauty raising cleanly elegant politely hand casually", "お尋ねしてもよろしいでしょうか"),
           ("kimono beauty politely checking a beautiful pocket watch quietly", "お時間でございます"),
           ("kimono beauty holding lightly gently playfully a little fan safely", "いかがいたしましょう"),
           ("kimono beauty giving elegant happily politely correct marks softly", "正解でございます")]),
        # Set 6: お別れと就寝の辞
        m([("kimono beauty deeply lovingly safely bowing away respectfully", "またお目にかかりましょう"),
           ("kimono beauty holding warmly soft politely hands waving gently", "ごきげんよう"),
           ("kimono beauty deeply safely completely bowing goodbye standing safely", "お気を付けてお帰りください"),
           ("kimono beauty gracefully gently looking softly looking softly leaving sadly", "名残惜しゅうございます"),
           ("kimono beauty happily gently smoothly beautifully holding evening hands gracefully", "良い夜をお過ごしください"),
           ("kimono beauty holding sleepily gently comfortably graceful eyes resting humbly", "お休みなさいませ"),
           ("kimono beauty respectfully beautifully safely cleanly completely waving slowly gracefully softly", "失礼いたします"),
           ("kimono beauty lightly playfully safely bowing down cleanly properly closing comfortably quietly politely politely", "ご免くださいませ"),
           ("kimono beauty taking softly gently warmly cleanly final grateful deeply bowing beautifully", "敬具")])
    ])
]
