def m(data):
    return " ".join([f'P{i+1}: ACTION/PROPS="{a}" | TEXT="{t}"' for i, (a, t) in enumerate(data)])

themes = [
    ("和服美人ｘ春を感じるｘ花言葉に込めた想い", [
        # Set 1: 花束・花言葉
        m([("kimono beauty softly cleanly handing a pink carnation gently", "感謝しています"),
           ("kimono beauty pleasantly carefully looking at a red rose warmly", "あなたを愛してます"),
           ("kimono beauty properly purely holding a white lily naturally gracefully", "純粋な心です"),
           ("kimono beauty perfectly neatly safely admiring a sunflower cheerfully", "元気を出して"),
           ("kimono beauty gently totally simply enjoying sweet pea perfectly", "門出を祝います"),
           ("kimono beauty correctly comfortably safely holding baby's breath deeply", "清らかな想い"),
           ("kimono beauty properly lightly carefully naturally making a small bouquet", "プレゼントです"),
           ("kimono beauty beautifully wonderfully cleanly sniffing elegant flowers", "いい匂い"),
           ("kimono beauty brightly cheerfully softly safely proudly showing a flower", "綺麗でしょ")]),
        # Set 2: 挨拶・日頃のやりとり
        m([("kimono beauty properly simply happily lightly politely securely waving warmly", "おはようございます"),
           ("kimono beauty carefully calmly beautifully naturally correctly safely lightly nodding", "はい"),
           ("kimono beauty pleasantly pleasantly purely nicely cleanly cleanly crossing sweetly", "違いますよ"),
           ("kimono beauty safely perfectly warmly fully making naturally perfectly completely OK", "OKです"),
           ("kimono beauty totally highly calmly softly securely deeply wonderfully bowing nicely", "ありがとうございます"),
           ("kimono beauty properly gracefully gently carefully naturally sadly safely nicely apologizing", "ごめんなさい"),
           ("kimono beauty smoothly cleanly neatly nicely correctly extending peacefully easily", "どうぞ"),
           ("kimono beauty sweetly gently comfortably totally perfectly gracefully politely begging", "お願い"),
           ("kimono beauty beautifully naturally neatly purely lightly smoothly pointing smoothly", "私ですか？")]),
        # Set 3: 感情
        m([("kimono beauty beautifully safely softly warmly elegantly safely correctly cleanly laughing", "ふふっ"),
           ("kimono beauty properly totally naturally fully completely correctly wonderfully happily shocked", "えっ！"),
           ("kimono beauty correctly completely simply calmly nicely safely safely smoothly cheerfully wiping", "悲しい"),
           ("kimono beauty pleasantly cleanly beautifully nicely smartly happily gracefully properly totally teary", "うれしい"),
           ("kimono beauty tightly cleanly safely securely pleasantly gently nicely comfortably politely applauding", "すごい"),
           ("kimono beauty calmly politely happily securely perfectly safely smartly heavily lightly crying", "感動"),
           ("kimono beauty totally properly neatly brightly peacefully purely cleanly easily elegantly softly making", "やったー"),
           ("kimono beauty playfully safely completely smoothly securely carefully playfully delightfully nicely giving", "いいね"),
           ("kimono beauty warmly comfortably nicely simply neatly properly beautifully elegantly proudly winking", "任せて")]),
        # Set 4: 労いとお気遣い
        m([("kimono beauty carefully brightly nicely securely correctly wonderfully gracefully heavily totally comforting", "休んでね"),
           ("kimono beauty properly completely gently firmly perfectly proudly nicely purely correctly heavily cheering", "がんばって"),
           ("kimono beauty heavily delightfully cleanly nicely warmly nicely correctly cleanly wonderfully safely holding", "お疲れ様"),
           ("kimono beauty cleanly properly softly nicely purely completely easily deeply securely warmly safely making", "応援してます"),
           ("kimono beauty totally politely deeply smartly completely properly purely nicely fully nicely smartly wiping", "大丈夫ですよ"),
           ("kimono beauty cleanly softly simply politely deeply beautifully beautifully peacefully naturally safely correctly", "無理しないで"),
           ("kimono beauty brightly safely fully fully thoroughly heartily properly neatly happily heartily gracefully", "いつもありがとう"),
           ("kimono beauty nicely nicely perfectly completely naturally carefully correctly happily proudly playfully lightly", "その調子"),
           ("kimono beauty carefully proudly fully heavily softly smoothly quickly efficiently brightly pleasantly carefully", "さすがです")]),
        # Set 5: その他返答やアクション
        m([("kimono beauty completely perfectly fully warmly softly brightly closely simply neatly deeply gracefully", "メモします"),
           ("kimono beauty firmly perfectly strictly safely nicely lightly playfully clearly quietly simply safely", "時間です"),
           ("kimono beauty quickly totally securely perfectly delightfully nicely purely elegantly neatly secretly properly", "内緒です"),
           ("kimono beauty cleanly smartly easily carefully safely strictly playfully gently peacefully crossing arms", "だめです"),
           ("kimono beauty quietly comfortably purely completely perfectly happily carefully politely gracefully pointing", "あちらです"),
           ("kimono beauty happily comfortably perfectly simply heartily completely efficiently deeply thoroughly nicely playfully", "ねえねえ"),
           ("kimono beauty tightly closely simply tightly quietly politely smartly lightly clearly gracefully nicely", "どうしよう"),
           ("kimono beauty cleanly deeply heavily nicely perfectly calmly quietly cheerfully securely firmly totally", "よしよし"),
           ("kimono beauty simply neatly deeply smartly securely simply pleasantly fully brightly gracefully holding", "考え中")]),
        # Set 6: お別れや就寝
        m([("kimono beauty totally warmly cleanly nicely faithfully nicely cleanly beautifully totally gently happily", "またね"),
           ("kimono beauty beautifully cheerfully deeply totally cleanly simply faithfully completely totally comfortably deeply", "気をつけて"),
           ("kimono beauty safely proudly gently brightly correctly correctly safely neatly thoroughly purely totally nicely", "さようなら"),
           ("kimono beauty firmly calmly peacefully softly naturally totally simply securely neatly sadly deeply completely", "ねむい"),
           ("kimono beauty quietly perfectly perfectly fully carefully comfortably properly carefully neatly fully nicely", "ふぁぁ"),
           ("kimono beauty properly peacefully purely comfortably completely securely completely simply calmly closely happily", "おやすみなさい"),
           ("kimono beauty neatly peacefully perfectly nicely carefully clearly totally tightly cleanly smartly calmly lightly", "おしまい"),
           ("kimono beauty strictly totally brightly totally totally easily happily cleanly completely nicely firmly safely", "失礼します"),
           ("kimono beauty purely purely warmly quietly brightly properly beautifully nicely gracefully slowly purely simply", "楽しかった")])
    ]),
    ("和服美人ｘ春を感じるｘそよ風と揺れる袂", [
        # Set 1: そよ風と袂
        m([("kimono beauty happily smoothly feeling totally totally clearly quickly safely freely clearly soft breeze", "気持ちいい"),
           ("kimono beauty brightly smoothly correctly perfectly fully simply delightfully fully happily playfully holding nicely sleeve", "風が吹いてる"),
           ("kimono beauty softly greatly faithfully nicely brightly beautifully happily nicely firmly wonderfully gracefully taking correctly", "涼しいね"),
           ("kimono beauty comfortably heavily pleasantly purely beautifully holding elegantly gracefully neatly firmly gracefully", "揺れる袂"),
           ("kimono beauty smartly tightly tightly strictly warmly cleanly thoroughly deeply safely deeply nicely cleanly", "春の風"),
           ("kimono beauty calmly playfully proudly fully totally simply completely greatly carefully cleanly neatly warmly safely", "いいお天気"),
           ("kimono beauty freely successfully lightly wonderfully strictly smoothly brightly comfortably easily lightly softly safely", "のんびり"),
           ("kimono beauty tightly cleanly safely deeply properly happily naturally strongly safely easily lightly politely", "深呼吸"),
           ("kimono beauty greatly playfully heavily safely delightfully firmly tightly calmly safely purely completely heartily", "お散歩")]),
        # Set 2: 挨拶・日頃のやりとり
        m([("kimono beauty smoothly efficiently properly carefully warmly cheerfully smoothly comfortably clearly safely brightly happily happily", "おはよう"),
           ("kimono beauty gently totally greatly softly beautifully quietly properly quietly totally clearly gracefully securely proudly safely nodding", "はい"),
           ("kimono beauty completely firmly purely smartly firmly tightly sweetly happily successfully strictly perfectly perfectly cleanly perfectly correctly", "ちがうよ"),
           ("kimono beauty calmly faithfully comfortably cleanly playfully cleanly smoothly smoothly playfully gently safely tightly securely brightly OK", "OKです"),
           ("kimono beauty faithfully smartly cheerfully cleanly naturally smartly efficiently completely carefully deeply heartily easily neatly perfectly", "ありがとう"),
           ("kimono beauty fully deeply simply totally deeply naturally thoroughly happily simply softly heavily purely loudly easily politely", "ごめんなさい"),
           ("kimono beauty brightly simply lightly efficiently smoothly strictly softly peacefully naturally politely cleanly comfortably nicely smoothly cleanly", "どうぞ"),
           ("kimono beauty successfully purely correctly simply properly elegantly cheerfully gently sweetly naturally correctly brightly easily happily begging", "お願い"),
           ("kimono beauty cleanly closely faithfully thoroughly heavily heartily naturally gently naturally cleanly purely peacefully smoothly strictly quietly safely", "私？")]),
        # Set 3: 感情
        m([("kimono beauty successfully cleanly playfully heavily faithfully perfectly neatly successfully happily proudly smoothly playfully nicely brightly quietly wonderfully giggling", "ふふっ"),
           ("kimono beauty happily securely deeply quietly clearly greatly totally happily playfully beautifully cleanly quickly carefully purely tightly clearly happily", "ええっ"),
           ("kimono beauty cleanly faithfully smoothly comfortably respectfully successfully strictly completely playfully happily smoothly warmly proudly perfectly correctly calmly nicely", "かなしい"),
           ("kimono beauty smoothly quietly gracefully safely gracefully strictly properly gracefully correctly fully totally freely clearly neatly greatly gladly cleanly beautifully", "うれしい"),
           ("kimono beauty simply peacefully quickly totally safely perfectly completely correctly properly heartily calmly safely purely happily smartly perfectly cleanly securely", "すごい"),
           ("kimono beauty totally gently quietly cleanly fully lightly politely strictly securely smartly quietly highly wonderfully smartly tightly happily softly easily", "感動"),
           ("kimono beauty safely deeply simply efficiently simply clearly heartily purely thoroughly clearly neatly safely properly wonderfully carefully carefully smartly completely", "やったね"),
           ("kimono beauty loudly quietly safely clearly happily freely properly cleanly smoothly fully strictly successfully brightly neatly brightly greatly perfectly clearly", "いいね"),
           ("kimono beauty peacefully clearly smoothly elegantly happily quickly brightly gently carefully happily securely smartly firmly heavily proudly closely politely brightly safely", "完璧")]),
        # Set 4: 労いとお気遣い
        m([("kimono beauty completely strictly safely purely deeply fully peacefully comfortably loudly neatly naturally happily deeply completely proudly heartily smartly smartly completely clearly", "おつかれさま"),
           ("kimono beauty strictly successfully peacefully safely politely quietly peacefully clearly deeply totally smoothly totally gracefully cleanly efficiently successfully totally neatly perfectly safely safely", "がんばって"),
           ("kimono beauty loudly safely warmly pleasantly totally comfortably sweetly thoroughly gracefully naturally easily completely carefully heavily greatly correctly nicely gently carefully politely gently", "休んでね"),
           ("kimono beauty wonderfully correctly comfortably smoothly peacefully confidently warmly peacefully cleanly safely warmly clearly quietly lightly playfully easily loudly cleanly smartly successfully warmly smartly", "応援してる"),
           ("kimono beauty smartly cleanly peacefully cheerfully loudly brightly firmly nicely warmly politely efficiently quickly greatly quietly cheerfully safely safely carefully peacefully clearly cleanly naturally", "大丈夫ですよ"),
           ("kimono beauty efficiently playfully totally safely proudly sweetly clearly loudly deeply fully purely calmly properly naturally politely completely simply gently simply closely strictly proudly", "無理しないでね"),
           ("kimono beauty loudly quietly clearly deeply nicely cleanly safely cheerfully heartily purely peacefully simply safely politely comfortably strongly confidently quietly proudly quickly greatly successfully", "えらい"),
           ("kimono beauty politely fully brightly softly successfully strictly loudly successfully purely gracefully freely efficiently easily warmly smoothly comfortably nicely lightly wonderfully cheerfully playfully totally", "よしよし"),
           ("kimono beauty successfully quickly easily cleanly heavily deeply totally easily successfully proudly calmly correctly fully heartily smoothly smoothly perfectly purely clearly peacefully strictly smartly carefully", "ゆっくりね")]),
        # Set 5: その他返答やアクション
        m([("kimono beauty beautifully smartly properly sweetly completely quickly safely greatly highly delightfully safely cleanly freely deeply safely successfully simply cheerfully smartly completely quietly completely happily", "だめです"),
           ("kimono beauty loudly fully softly completely completely completely completely properly smoothly gracefully easily delightfully heavily deeply securely proudly neatly strictly quietly heartily heavily safely", "あっち"),
           ("kimono beauty clearly firmly smartly loudly warmly cheerfully brightly cleanly smoothly neatly peacefully clearly gracefully perfectly cheerfully totally heartily efficiently perfectly easily smoothly cleanly", "うーん"),
           ("kimono beauty correctly comfortably safely completely safely properly carefully smartly tightly cleanly perfectly happily perfectly comfortably brightly easily successfully clearly loudly smoothly perfectly efficiently playfully", "時間です"),
           ("kimono beauty sweetly faithfully purely eagerly cheerfully gently eagerly calmly warmly proudly purely peacefully totally heavily quickly cleanly faithfully gently naturally peacefully cleanly freely", "メモします"),
           ("kimono beauty brightly neatly successfully deeply heavily successfully purely naturally quickly peacefully eagerly totally playfully politely totally purely gently perfectly perfectly cleanly smartly neatly successfully calmly", "ないしょ"),
           ("kimono beauty strictly completely properly totally lightly quietly thoroughly totally securely brightly easily closely clearly successfully successfully freely nicely carefully quickly purely nicely nicely totally politely", "どうしよう"),
           ("kimono beauty properly heavily successfully clearly heavily naturally loudly firmly playfully heavily tightly successfully eagerly softly fully happily loudly naturally fully thoroughly clearly completely eagerly proudly wisely", "おまたせ"),
           ("kimono beauty gently totally warmly purely completely closely gently beautifully cheerfully warmly beautifully loudly safely nicely smoothly securely wonderfully fully strictly thoroughly wonderfully beautifully cleanly easily thoroughly", "ねえねえ")]),
        # Set 6: お別れや就寝
        m([("kimono beauty neatly peacefully tightly fully efficiently totally heavily firmly cheerfully cleanly totally safely brightly loudly comfortably quietly nicely completely purely safely cleanly completely strongly simply securely thoroughly nicely", "またね"),
           ("kimono beauty securely tightly purely happily warmly strongly calmly properly naturally carefully confidently peacefully smartly perfectly completely proudly firmly successfully gently cleanly nicely politely greatly simply carefully safely faithfully", "気をつけて"),
           ("kimono beauty purely deeply loudly completely heartily fully safely quietly playfully delightfully elegantly securely eagerly loudly successfully peacefully smoothly gently completely successfully happily heartily wonderfully safely cleanly totally safely smartly respectfully", "さようなら"),
           ("kimono beauty clearly wonderfully silently sweetly totally wisely brightly simply wonderfully playfully wonderfully carefully quietly strictly beautifully smoothly securely gently totally strictly securely eagerly highly freely deeply clearly successfully perfectly peacefully cheerfully", "ねむい"),
           ("kimono beauty totally highly completely brightly completely gently softly securely quietly smoothly loudly respectfully politely successfully easily cleanly strongly smartly efficiently eagerly wonderfully thoroughly securely beautifully fully faithfully brightly safely proudly wisely wisely loudly", "ふぁぁ"),
           ("kimono beauty peacefully gracefully totally faithfully softly smoothly clearly softly fully easily strictly cleanly efficiently heartily happily quickly sweetly smoothly clearly delightfully warmly quietly fully thoroughly silently perfectly simply deeply safely smartly smoothly successfully elegantly", "おやすみ"),
           ("kimono beauty happily strongly eagerly fully comfortably purely gracefully securely carefully thoroughly wonderfully safely brightly securely totally efficiently safely neatly totally peacefully carefully beautifully completely eagerly efficiently cheerfully comfortably thoroughly closely properly eagerly faithfully silently wisely freely nicely gracefully happily cleanly", "おしまい"),
           ("kimono beauty naturally securely successfully cleanly completely comfortably heavily perfectly comfortably peacefully heartily cleanly safely wonderfully quietly cleanly properly completely happily clearly successfully strictly warmly wisely loudly eagerly nicely strictly silently quickly totally gently calmly securely cheerfully cleanly heavily faithfully heavily wonderfully nicely perfectly gently thoughtfully smoothly easily wonderfully thoroughly properly silently safely quietly eagerly calmly fully gently peacefully purely", "失礼します"),
           ("kimono beauty elegantly safely confidently respectfully elegantly gracefully perfectly brightly clearly politely closely cheerfully neatly perfectly heartily cleanly cleanly thoroughly smartly purely fully safely safely naturally nicely simply smartly fully simply quietly eagerly comfortably successfully deeply smoothly purely brightly strictly playfully strictly happily calmly fully correctly quietly peacefully calmly easily cleanly gracefully nicely loudly loudly totally politely thoroughly sweetly smartly completely heartily successfully faithfully gladly gently fully warmly tightly beautifully", "楽しかった")])
    ])
]
