def m(data):
    return " ".join([f'P{i+1}: ACTION/PROPS="{a}" | TEXT="{t}"' for i, (a, t) in enumerate(data)])

themes = [
    ("和服美人ｘ春を感じるｘ卒業と新しい門出", [
        # Set 1: 卒業・祝賀
        m([("kimono beauty holding a diploma respectfully smiling", "卒業おめでとうございます"),
           ("kimono beauty wearing high quality hakama happily", "無事に卒業しました"),
           ("kimono beauty looking at a beautiful cherry blossom affectionately", "門出の季節ですね"),
           ("kimono beauty throwing a graduation cap cheerfully", "やりました！"),
           ("kimono beauty gracefully warmly handing a bouquet", "お祝いです"),
           ("kimono beauty joyfully peacefully looking at a camera", "記念撮影しましょう"),
           ("kimono beauty wiping a happy tear gently elegantly", "感動しました"),
           ("kimono beauty deeply bowing holding flowers respectfully", "お世話になりました"),
           ("kimono beauty softly smiling cleanly happily", "これからが楽しみ")]),
        # Set 2: 挨拶・日頃のやりとり
        m([("kimono beauty happily waving elegantly in hakama", "おはようございます"),
           ("kimono beauty politely respectfully cleanly bowing", "ありがとうございます"),
           ("kimono beauty holding hands apologetically gently", "ごめんなさい"),
           ("kimono beauty cleanly nodding beautifully", "はい"),
           ("kimono beauty gently shaking head safely respectfully", "いいえ"),
           ("kimono beauty holding an OK sign brightly", "了解です"),
           ("kimono beauty holding up an X safely elegantly", "できません"),
           ("kimono beauty warmly extending an open hand", "どうぞ"),
           ("kimono beauty looking nicely gently lovingly", "私ですか？")]),
        # Set 3: 感情
        m([("kimono beauty softly pleasantly covering mouth to laugh", "ふふっ"),
           ("kimono beauty happily crying covering face emotionally", "うれし泣き"),
           ("kimono beauty holding hands to flushed cheeks playfully", "恥ずかしい"),
           ("kimono beauty looking completely surprisingly beautifully shocked", "えっ！"),
           ("kimono beauty clapping enthusiastically gracefully", "素晴らしい"),
           ("kimono beauty pointing happily with a peace sign", "イェイ！"),
           ("kimono beauty cheerfully enthusiastically happily giving thumbs up", "最高です"),
           ("kimono beauty leaning gracefully heavily comfortably tired", "頑張りました"),
           ("kimono beauty cleanly cleanly wiping a sweat elegantly", "お見事")]),
        # Set 4: 労いと激励
        m([("kimono beauty looking at you affectionately softly warmly", "お疲れ様でした"),
           ("kimono beauty heavily enthusiastically raising a fist", "新生活がんばって"),
           ("kimono beauty kindly rubbing back comfortingly warmly", "無理しないでね"),
           ("kimono beauty happily warmly offering a present securely", "ささやかですが"),
           ("kimono beauty looking at you firmly supportively lovingly", "応援しています"),
           ("kimono beauty holding both hands warmly closely", "いつでも頼って"),
           ("kimono beauty cleanly passing a handkerchief warmly kindly", "涙を拭いて"),
           ("kimono beauty warmly looking deeply trustingly", "きっと大丈夫"),
           ("kimono beauty securely giving an affirming gentle nod", "その調子です")]),
        # Set 5: その他リアクション
        m([("kimono beauty thinking gracefully putting finger to cheek", "どうしようか"),
           ("kimono beauty enthusiastically proudly cleanly pointing", "決まり！"),
           ("kimono beauty waving an empty hand happily politely", "忘れないでね"),
           ("kimono beauty pulling securely happily a sleeve", "こっちこっち"),
           ("kimono beauty looking gently patiently affectionately waiting", "待ってます"),
           ("kimono beauty holding a small notebook gracefully neatly", "連絡してね"),
           ("kimono beauty nicely nicely pointing closely to you", "あなたならできる"),
           ("kimono beauty properly securely firmly clasping hands", "祈ってます"),
           ("kimono beauty cheerfully completely warmly cleanly jumping", "やったー！")]),
        # Set 6: 別れの挨拶と夜
        m([("kimono beauty lovingly completely peacefully happily waving", "また会いましょう"),
           ("kimono beauty safely gracefully completely respectfully bowing", "ご機嫌よう"),
           ("kimono beauty safely tightly nicely cleanly holding hands leaving", "さようなら"),
           ("kimono beauty peacefully gracefully smoothly elegantly leaving", "元気でね"),
           ("kimono beauty cleanly peacefully tiredly lightly rubbing eyes", "お休みなさい"),
           ("kimono beauty smoothly cleanly packing bags efficiently politely", "準備ヨシ"),
           ("kimono beauty turning back warmly gracefully safely softly", "いつまでもお元気で"),
           ("kimono beauty nicely peacefully looking up at stars nicely", "良い夜ですね"),
           ("kimono beauty holding cleanly gently playfully smoothly politely a lantern", "失礼いたします")])
    ]),
    ("和服美人ｘ春を感じるｘ柳の芽吹きと水辺の散歩", [
        # Set 1: 水辺・柳の情景
        m([("kimono beauty admiring freshly sprouted weeping willow pleasantly", "芽吹きましたね"),
           ("kimono beauty looking at a peaceful river gracefully happily", "水面が綺麗"),
           ("kimono beauty softly dropping a petal playfully into the river", "流れていく"),
           ("kimono beauty cleanly peacefully closing eyes listening cleanly", "川のせせらぎ"),
           ("kimono beauty looking peacefully wonderfully up at branches", "風流ですね"),
           ("kimono beauty walking nicely slowly across a bridge neatly", "散歩日和です"),
           ("kimono beauty gracefully playfully smoothly looking at fish", "鯉がいます"),
           ("kimono beauty softly taking deep breaths by happily nature", "深呼吸"),
           ("kimono beauty happily cleanly gently waving a wagasa nicely", "いいお天気")]),
        # Set 2: 挨拶・日頃のやりとり
        m([("kimono beauty politely nicely cleanly warmly enthusiastically waving", "おはようございます"),
           ("kimono beauty firmly nicely gracefully cleanly politely agreeing", "はい"),
           ("kimono beauty cleanly gently cleanly smoothly disagreeing politely", "違いますよ"),
           ("kimono beauty enthusiastically making an OK gracefully sign", "OK"),
           ("kimono beauty deeply respectfully carefully completely bowing thankfully", "ありがとう"),
           ("kimono beauty warmly thoughtfully gracefully securely apologizing delicately", "ごめんなさい"),
           ("kimono beauty gracefully naturally gently respectfully offering", "どうぞ"),
           ("kimono beauty politely respectfully cleanly smoothly begging calmly", "お願い"),
           ("kimono beauty kindly wonderfully nicely naturally inquiring warmly", "どなた？")]),
        # Set 3: 感情
        m([("kimono beauty beautifully cheerfully pleasantly beautifully softly laughing", "ふふっ"),
           ("kimono beauty surprisingly completely happily suddenly completely shocked", "びっくり"),
           ("kimono beauty sadly politely cleanly dropping cleanly naturally a tear", "悲しい"),
           ("kimono beauty joyfully perfectly wonderfully fully beautifully crying", "嬉しい"),
           ("kimono beauty playfully puffing cheeks annoyingly wonderfully gracefully", "もうっ！"),
           ("kimono beauty cheerfully gracefully cleanly cleanly clapping elegantly", "すごい"),
           ("kimono beauty purely happily brightly securely cleanly making peace", "イェイ"),
           ("kimono beauty totally happily completely naturally deeply sighing", "疲れたぁ"),
           ("kimono beauty politely carefully securely gracefully beautifully blushing", "照れるな")]),
        # Set 4: 気遣い・いたわり
        m([("kimono beauty safely comfortably handing beautifully politely a warm tea", "ひと休みして"),
           ("kimono beauty properly securely looking gently deeply calmly lovingly", "大丈夫？"),
           ("kimono beauty warmly comfortably patting nicely naturally smoothly closely", "よしよし"),
           ("kimono beauty cheerfully beautifully happily heavily completely cheering", "がんばって！"),
           ("kimono beauty totally safely completely nicely perfectly encouraging", "応援してます"),
           ("kimono beauty pleasantly softly cleanly comfortably politely supporting", "無理しないで"),
           ("kimono beauty easily safely securely deeply confidently softly smiling", "私がついてるよ"),
           ("kimono beauty heavily securely correctly neatly fully wiping sweat", "お疲れ様"),
           ("kimono beauty completely gently gracefully wonderfully looking closely", "偉いね")]),
        # Set 5: リアクション
        m([("kimono beauty nicely wonderfully comfortably clearly safely warmly pointing", "あそこです"),
           ("kimono beauty cleanly smoothly heavily perfectly checking politely time", "もうこんな時間"),
           ("kimono beauty perfectly completely smartly wonderfully making gracefully notes", "メモメモ"),
           ("kimono beauty nicely playfully completely secretly securely whispering", "内緒だよ"),
           ("kimono beauty perfectly warmly carefully fully gracefully holding chin", "考え中"),
           ("kimono beauty gently totally completely safely lightly naturally pulling", "行こう！"),
           ("kimono beauty purely delightfully safely perfectly naturally finding", "見つけた"),
           ("kimono beauty strictly safely safely purely purely gently crossing", "だめー"),
           ("kimono beauty totally properly totally playfully casually safely poking", "ねえねえ")]),
        # Set 6: 別れの挨拶や夕暮れ
        m([("kimono beauty warmly comfortably cleanly lovingly correctly safely waving", "またね"),
           ("kimono beauty peacefully gracefully gracefully deeply safely carefully bowing", "気をつけて"),
           ("kimono beauty happily totally properly cleanly softly naturally turning back", "さようなら"),
           ("kimono beauty beautifully gently smoothly completely easily gracefully leaving", "失礼します"),
           ("kimono beauty gently properly calmly warmly calmly safely correctly sleeping", "スヤスヤ"),
           ("kimono beauty happily safely warmly totally tiredly respectfully safely rubbing", "ねむい"),
           ("kimono beauty deeply properly cleanly peacefully beautifully securely resting", "おやすみなさい"),
           ("kimono beauty smoothly peacefully wonderfully naturally admiring peacefully dusk", "夕暮れですね"),
           ("kimono beauty neatly wonderfully totally safely properly warmly walking away", "おしまい")])
    ]),
    ("和服美人ｘ春を感じるｘ読書と春の日差し", [
        # Set 1: 本と読書環境
        m([("kimono beauty holding a beautifully peacefully smoothly book properly openly", "読書中"),
           ("kimono beauty wonderfully pleasantly cleanly beautifully nicely reading thoroughly", "面白いです"),
           ("kimono beauty carefully calmly beautifully heavily completely happily turning a page", "次のページ"),
           ("kimono beauty smoothly pleasantly lightly happily lightly totally closing nicely", "読み終わりました"),
           ("kimono beauty wonderfully neatly perfectly deeply safely comfortably looking deeply outside", "日差しが暖かい"),
           ("kimono beauty pleasantly correctly gracefully peacefully calmly neatly deeply taking tea", "お茶と本"),
           ("kimono beauty politely elegantly naturally naturally securely holding securely glasses", "よく見えます"),
           ("kimono beauty deeply perfectly clearly pleasantly nicely safely wonderfully resting eyes", "休憩します"),
           ("kimono beauty carefully safely completely naturally cleanly naturally cleanly marking book", "栞を挟みます")]),
        # Set 2: 挨拶・日頃のやりとり
        m([("kimono beauty perfectly naturally comfortably gently gracefully safely happily waving", "おはようございます"),
           ("kimono beauty politely nicely easily wonderfully securely wonderfully elegantly completely nodding", "はい"),
           ("kimono beauty easily gently perfectly lightly completely shaking naturally politely cleanly", "違うよ"),
           ("kimono beauty joyfully confidently purely perfectly elegantly cleanly clearly signaling", "OKです"),
           ("kimono beauty gracefully correctly cleanly properly naturally politely bowing beautifully safely", "ありがとうございます"),
           ("kimono beauty cleanly smoothly softly securely completely perfectly correctly begging properly", "ごめんなさい"),
           ("kimono beauty warmly closely politely gently respectfully extending cleanly naturally cleanly", "どうぞ"),
           ("kimono beauty beautifully completely respectfully neatly cleanly carefully making begging nicely", "お願い"),
           ("kimono beauty completely nicely totally cleanly purely purely purely curiously happily tilting", "なに？")]),
        # Set 3: 感情
        m([("kimono beauty covering mouth happily nicely nicely gently naturally safely completely gracefully", "ふふっ"),
           ("kimono beauty smoothly easily totally totally perfectly joyfully gently laughing cleanly", "あはは"),
           ("kimono beauty heavily cleanly playfully cleanly carefully cleanly crossing perfectly wonderfully", "困ります"),
           ("kimono beauty purely delightfully safely smoothly safely perfectly beautifully naturally crying", "悲しい"),
           ("kimono beauty beautifully easily heavily beautifully totally naturally heavily cheerfully applauding", "すごい！"),
           ("kimono beauty simply beautifully perfectly perfectly clearly wonderfully comfortably happily celebrating", "やったー"),
           ("kimono beauty safely comfortably quietly gently securely perfectly easily happily blushing totally", "照れます"),
           ("kimono beauty totally happily beautifully simply correctly gently cleanly pleasantly sighing purely", "疲れたぁ"),
           ("kimono beauty perfectly nicely cleanly clearly playfully completely heavily completely fully making", "いいね")]),
        # Set 4: 労いとお気遣い
        m([("kimono beauty softly cleanly cleanly politely correctly naturally clearly properly nicely making", "お疲れ様です"),
           ("kimono beauty easily gracefully perfectly purely heavily wonderfully neatly comfortably passing sweetly", "休んでね"),
           ("kimono beauty safely comfortably perfectly smoothly naturally totally cleanly smartly gently cheering", "がんばって"),
           ("kimono beauty cleanly calmly deeply softly wonderfully quietly wonderfully tenderly securely patting", "大丈夫ですよ"),
           ("kimono beauty cleanly politely softly totally warmly perfectly gently comfortably naturally holding", "あたたかいね"),
           ("kimono beauty safely pleasantly cleanly lovingly purely wonderfully purely perfectly perfectly safely", "無理しないで"),
           ("kimono beauty warmly carefully heavily beautifully wonderfully beautifully beautifully perfectly nodding", "その調子"),
           ("kimono beauty cheerfully correctly wonderfully cleanly firmly nicely gently giving peacefully thumbs", "さすがです"),
           ("kimono beauty perfectly elegantly completely nicely totally nicely quietly completely looking deeply firmly", "よしよし")]),
        # Set 5: その他返答やアクション
        m([("kimono beauty simply beautifully simply carefully happily strongly cleanly perfectly crossing tightly", "だめです"),
           ("kimono beauty properly simply completely nicely safely easily firmly pointing purely happily politely", "あっち"),
           ("kimono beauty heavily delightfully easily correctly beautifully gracefully holding perfectly safely chin", "うーん"),
           ("kimono beauty purely totally warmly purely heavily smartly holding carefully perfectly completely watch", "時間です"),
           ("kimono beauty beautifully wonderfully perfectly safely brightly cleverly beautifully safely smartly making", "メモ完了"),
           ("kimono beauty happily naturally cleanly fully easily playfully secretly quietly comfortably smoothly secretly", "内緒"),
           ("kimono beauty simply simply fully simply delightfully neatly calmly perfectly clearly clearly completely naturally", "私ですか？"),
           ("kimono beauty calmly politely correctly carefully smartly holding cleanly smoothly gracefully completely softly", "どうしましょう"),
           ("kimono beauty playfully purely simply properly clearly safely cheerfully cleanly brightly quickly gently poking", "ねぇねぇ")]),
        # Set 6: お別れや就寝
        m([("kimono beauty nicely nicely politely safely deeply properly safely warmly leaving happily safely peacefully", "また明日"),
           ("kimono beauty heavily cleanly deeply safely neatly softly respectfully bowing respectfully calmly neatly", "お気をつけて"),
           ("kimono beauty safely cleanly simply properly beautifully safely safely simply smoothly resting warmly carefully", "ねむい"),
           ("kimono beauty wonderfully pleasantly completely clearly clearly pleasantly safely lightly rubbing naturally cleanly", "ふぁぁ"),
           ("kimono beauty clearly simply simply perfectly safely peacefully beautifully carefully fully elegantly resting safely", "おやすみなさい"),
           ("kimono beauty purely perfectly securely gently nicely gracefully calmly calmly nicely wonderfully safely stretching", "おしまい"),
           ("kimono beauty clearly fully simply cleanly purely gracefully politely comfortably respectfully turning naturally gracefully", "失礼します"),
           ("kimono beauty completely nicely totally cleanly beautifully softly lovingly lightly smoothly nicely slowly waving safely", "さようなら"),
           ("kimono beauty perfectly brightly wonderfully cleverly cleanly safely warmly correctly easily delightfully softly leaving heavily", "楽しかった")])
    ])
]
