import os
import csv

os.makedirs('outputs/prompts', exist_ok=True)

def save_csv(theme, raw_text):
    filename = f'outputs/prompts/{theme}_prompts.csv'
    with open(filename, 'w', encoding='utf-8-sig', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['prompt'])
        for line in raw_text.strip().split('\n'):
            if line.strip():
                writer.writerow([line.strip()])

d1="""
P1: ACTION/PROPS="heavy wind" | TEXT="春一番だ" P2: ACTION/PROPS="blown away" | TEXT="飛ばされる" P3: ACTION/PROPS="holding tree" | TEXT="耐えろ" P4: ACTION/PROPS="wind in face" | TEXT="向かい風" P5: ACTION/PROPS="landing" | TEXT="着地" P6: ACTION/PROPS="calm" | TEXT="凪" P7: ACTION/PROPS="messy hair" | TEXT="ボサボサ" P8: ACTION/PROPS="thumbs up" | TEXT="無事" P9: ACTION/PROPS="walking forward" | TEXT="前進"
P1: ACTION/PROPS="umbrella fly" | TEXT="傘が" P2: ACTION/PROPS="chasing" | TEXT="まてー" P3: ACTION/PROPS="running fast" | TEXT="ダッシュ" P4: ACTION/PROPS="catching" | TEXT="捕獲" P5: ACTION/PROPS="broken umbrella" | TEXT="折れた" P6: ACTION/PROPS="crying" | TEXT="ぴえん" P7: ACTION/PROPS="rain stop" | TEXT="やんだ" P8: ACTION/PROPS="rainbow" | TEXT="虹だ" P9: ACTION/PROPS="smile" | TEXT="笑顔"
P1: ACTION/PROPS="dust wind" | TEXT="砂ぼこり" P2: ACTION/PROPS="closing eyes" | TEXT="目痛い" P3: ACTION/PROPS="rubbing eyes" | TEXT="ゴシゴシ" P4: ACTION/PROPS="washing face" | TEXT="洗う" P5: ACTION/PROPS="refreshing" | TEXT="スッキリ" P6: ACTION/PROPS="looking up" | TEXT="晴れた" P7: ACTION/PROPS="stretching" | TEXT="伸び" P8: ACTION/PROPS="deep breath" | TEXT="深呼吸" P9: ACTION/PROPS="ready" | TEXT="よし"
P1: ACTION/PROPS="leaning forward" | TEXT="前傾姿勢" P2: ACTION/PROPS="stepping" | TEXT="一歩" P3: ACTION/PROPS="sliding back" | TEXT="戻る" P4: ACTION/PROPS="pushing wind" | TEXT="押す" P5: ACTION/PROPS="tired" | TEXT="疲れた" P6: ACTION/PROPS="sitting" | TEXT="休憩" P7: ACTION/PROPS="drinking water" | TEXT="水" P8: ACTION/PROPS="stand up" | TEXT="復活" P9: ACTION/PROPS="walking" | TEXT="進む"
P1: ACTION/PROPS="wind blow clothes" | TEXT="キャッ" P2: ACTION/PROPS="holding clothes" | TEXT="セーフ" P3: ACTION/PROPS="embarrassed" | TEXT="照れる" P4: ACTION/PROPS="looking around" | TEXT="見た？" P5: ACTION/PROPS="relieved" | TEXT="よかった" P6: ACTION/PROPS="wind again" | TEXT="また" P7: ACTION/PROPS="squatting" | TEXT="しゃがむ" P8: ACTION/PROPS="safe" | TEXT="回避" P9: ACTION/PROPS="sigh" | TEXT="ふぅ"
P1: ACTION/PROPS="thunder" | TEXT="雷" P2: ACTION/PROPS="hiding" | TEXT="怖い" P3: ACTION/PROPS="trembling" | TEXT="ブルブル" P4: ACTION/PROPS="covering ears" | TEXT="耳塞ぐ" P5: ACTION/PROPS="peeking" | TEXT="チラッ" P6: ACTION/PROPS="clear sky" | TEXT="快晴" P7: ACTION/PROPS="dancing" | TEXT="踊る" P8: ACTION/PROPS="happy" | TEXT="わーい" P9: ACTION/PROPS="peace" | TEXT="平和"
"""
save_csv('全身タイツｘ春を感じるｘ春の嵐（春一番）に立ち向かう', d1)

d2="""
P1: ACTION/PROPS="looking at bulb" | TEXT="球根" P2: ACTION/PROPS="watering" | TEXT="水やり" P3: ACTION/PROPS="waiting" | TEXT="まだかな" P4: ACTION/PROPS="sprout" | TEXT="芽が出た" P5: ACTION/PROPS="magnifying glass" | TEXT="観察" P6: ACTION/PROPS="measuring" | TEXT="伸びた" P7: ACTION/PROPS="sleeping next to it" | TEXT="添い寝" P8: ACTION/PROPS="bud" | TEXT="つぼみ" P9: ACTION/PROPS="excited" | TEXT="わくわく"
P1: ACTION/PROPS="red tulip" | TEXT="赤" P2: ACTION/PROPS="white tulip" | TEXT="白" P3: ACTION/PROPS="yellow tulip" | TEXT="黄色" P4: ACTION/PROPS="singing" | TEXT="咲いた" P5: ACTION/PROPS="clapping" | TEXT="綺麗" P6: ACTION/PROPS="smelling" | TEXT="いい匂い" P7: ACTION/PROPS="taking photo" | TEXT="パシャ" P8: ACTION/PROPS="smiling" | TEXT="にっこり" P9: ACTION/PROPS="pointing" | TEXT="見て"
P1: ACTION/PROPS="butterfly on tulip" | TEXT="蝶々" P2: ACTION/PROPS="silent" | TEXT="しーっ" P3: ACTION/PROPS="watching closely" | TEXT="じーっ" P4: ACTION/PROPS="butterfly flies" | TEXT="飛んだ" P5: ACTION/PROPS="waving" | TEXT="バイバイ" P6: ACTION/PROPS="sunshine" | TEXT="ぽかぽか" P7: ACTION/PROPS="yawning" | TEXT="あくび" P8: ACTION/PROPS="stretching" | TEXT="のびー" P9: ACTION/PROPS="peaceful" | TEXT="のどか"
P1: ACTION/PROPS="tulip field" | TEXT="満開" P2: ACTION/PROPS="running in field" | TEXT="走る" P3: ACTION/PROPS="jumping" | TEXT="ジャンプ" P4: ACTION/PROPS="hiding in tulips" | TEXT="かくれんぼ" P5: ACTION/PROPS="peeking out" | TEXT="ばぁ" P6: ACTION/PROPS="laughing" | TEXT="あはは" P7: ACTION/PROPS="rolling" | TEXT="ゴロゴロ" P8: ACTION/PROPS="tired" | TEXT="疲れた" P9: ACTION/PROPS="sleeping" | TEXT="スヤスヤ"
P1: ACTION/PROPS="rain on tulip" | TEXT="雨だ" P2: ACTION/PROPS="holding umbrella over it" | TEXT="傘どうぞ" P3: ACTION/PROPS="wet" | TEXT="濡れちゃう" P4: ACTION/PROPS="shivering" | TEXT="寒い" P5: ACTION/PROPS="rain stops" | TEXT="やんだ" P6: ACTION/PROPS="droplet" | TEXT="雫" P7: ACTION/PROPS="sparkling" | TEXT="キラキラ" P8: ACTION/PROPS="sun comes out" | TEXT="太陽" P9: ACTION/PROPS="happy" | TEXT="嬉しい"
P1: ACTION/PROPS="wilted tulip" | TEXT="しおれた" P2: ACTION/PROPS="crying" | TEXT="悲しい" P3: ACTION/PROPS="watering fast" | TEXT="水水" P4: ACTION/PROPS="praying" | TEXT="元気になれ" P5: ACTION/PROPS="revived" | TEXT="復活" P6: ACTION/PROPS="cheering" | TEXT="やった" P7: ACTION/PROPS="hugging pot" | TEXT="大好き" P8: ACTION/PROPS="thumbs up" | TEXT="最高" P9: ACTION/PROPS="waving" | TEXT="また明日"
"""
save_csv('全身タイツｘ春を感じるｘチューリップの開花観察', d2)

d3="""
P1: ACTION/PROPS="basket" | TEXT="出発" P2: ACTION/PROPS="mountain path" | TEXT="険しい" P3: ACTION/PROPS="searching" | TEXT="どこだ" P4: ACTION/PROPS="found one" | TEXT="あった" P5: ACTION/PROPS="picking" | TEXT="採れた" P6: ACTION/PROPS="showing off" | TEXT="ドヤ" P7: ACTION/PROPS="putting in basket" | TEXT="ポイッ" P8: ACTION/PROPS="wiping sweat" | TEXT="ふぅ" P9: ACTION/PROPS="smiling" | TEXT="順調"
P1: ACTION/PROPS="fuki" | TEXT="ふきのとう" P2: ACTION/PROPS="smelling it" | TEXT="春の香り" P3: ACTION/PROPS="bitter face" | TEXT="苦そう" P4: ACTION/PROPS="tempura thought" | TEXT="天ぷら" P5: ACTION/PROPS="drooling" | TEXT="じゅるり" P6: ACTION/PROPS="looking for more" | TEXT="もっと" P7: ACTION/PROPS="digging" | TEXT="掘る" P8: ACTION/PROPS="muddy face" | TEXT="泥だらけ" P9: ACTION/PROPS="laughing" | TEXT="あはは"
P1: ACTION/PROPS="蕨 (warabi)" | TEXT="わらび" P2: ACTION/PROPS="stretching up" | TEXT="伸びてる" P3: ACTION/PROPS="snapping it" | TEXT="ポキッ" P4: ACTION/PROPS="good sound" | TEXT="いい音" P5: ACTION/PROPS="basket full" | TEXT="大豊作" P6: ACTION/PROPS="heavy" | TEXT="重い" P7: ACTION/PROPS="carrying" | TEXT="よっこいしょ" P8: ACTION/PROPS="proud" | TEXT="大満足" P9: ACTION/PROPS="thumbs up" | TEXT="最高"
P1: ACTION/PROPS="bear footprint" | TEXT="ん？" P2: ACTION/PROPS="shocked" | TEXT="足跡" P3: ACTION/PROPS="trembling" | TEXT="ガクブル" P4: ACTION/PROPS="looking back" | TEXT="誰かいる？" P5: ACTION/PROPS="running away" | TEXT="逃げろ" P6: ACTION/PROPS="panting" | TEXT="ハァハァ" P7: ACTION/PROPS="safe zone" | TEXT="助かった" P8: ACTION/PROPS="crying" | TEXT="怖かった" P9: ACTION/PROPS="sigh of relief" | TEXT="命拾い"
P1: ACTION/PROPS="competing with someone" | TEXT="負けない" P2: ACTION/PROPS="staring angrily" | TEXT="火花" P3: ACTION/PROPS="sprinting to target" | TEXT="早い者勝ち" P4: ACTION/PROPS="grabbing same plant" | TEXT="私のだ" P5: ACTION/PROPS="tug of war" | TEXT="引っ張り合い" P6: ACTION/PROPS="plant breaks" | TEXT="あーあ" P7: ACTION/PROPS="disappointed" | TEXT="がっかり" P8: ACTION/PROPS="shaking hands" | TEXT="仲直り" P9: ACTION/PROPS="sharing" | TEXT="半分こ"
P1: ACTION/PROPS="cooking" | TEXT="調理中" P2: ACTION/PROPS="tasting" | TEXT="味見" P3: ACTION/PROPS="smiling delicious" | TEXT="美味い" P4: ACTION/PROPS="serving food" | TEXT="できた" P5: ACTION/PROPS="eating" | TEXT="いただきます" P6: ACTION/PROPS="chewing" | TEXT="もぐもぐ" P7: ACTION/PROPS="thumbs up" | TEXT="絶品" P8: ACTION/PROPS="full belly" | TEXT="満腹" P9: ACTION/PROPS="tea" | TEXT="ごちそうさま"
"""
save_csv('全身タイツｘ春を感じるｘ山菜採りの真剣勝負', d3)

d4="""
P1: ACTION/PROPS="picnic sheet" | TEXT="場所取り" P2: ACTION/PROPS="spreading sheet" | TEXT="広げる" P3: ACTION/PROPS="sitting" | TEXT="座ろ" P4: ACTION/PROPS="opening bento" | TEXT="ジャーン" P5: ACTION/PROPS="sparkling eyes" | TEXT="豪華" P6: ACTION/PROPS="chopsticks" | TEXT="いただきます" P7: ACTION/PROPS="eating onigiri" | TEXT="ぱくっ" P8: ACTION/PROPS="delicious" | TEXT="美味しい" P9: ACTION/PROPS="smiling" | TEXT="最高"
P1: ACTION/PROPS="tamagoyaki" | TEXT="卵焼き" P2: ACTION/PROPS="sausage" | TEXT="タコさん" P3: ACTION/PROPS="karaage" | TEXT="唐揚げ" P4: ACTION/PROPS="sharing" | TEXT="食べる？" P5: ACTION/PROPS="feeding" | TEXT="あーん" P6: ACTION/PROPS="shy" | TEXT="照れる" P7: ACTION/PROPS="chewing together" | TEXT="もぐもぐ" P8: ACTION/PROPS="thumbs up" | TEXT="うまっ" P9: ACTION/PROPS="tea time" | TEXT="お茶"
P1: ACTION/PROPS="wind blows" | TEXT="風が" P2: ACTION/PROPS="chasing trash" | TEXT="待って" P3: ACTION/PROPS="catching trash" | TEXT="キャッチ" P4: ACTION/PROPS="relieved" | TEXT="危ない" P5: ACTION/PROPS="dust on food" | TEXT="あ…" P6: ACTION/PROPS="crying" | TEXT="砂が" P7: ACTION/PROPS="brushing off" | TEXT="払う" P8: ACTION/PROPS="eating anyway" | TEXT="気にしない" P9: ACTION/PROPS="strong" | TEXT="たくましい"
P1: ACTION/PROPS="bird steals food" | TEXT="トンビ" P2: ACTION/PROPS="shocked empty hand" | TEXT="ない" P3: ACTION/PROPS="looking up crying" | TEXT="私のおかず" P4: ACTION/PROPS="angry shaking fist" | TEXT="返せ" P5: ACTION/PROPS="friend gives food" | TEXT="あげる" P6: ACTION/PROPS="touched" | TEXT="神" P7: ACTION/PROPS="eating crying" | TEXT="やさしい" P8: ACTION/PROPS="happy again" | TEXT="復活" P9: ACTION/PROPS="hiding food" | TEXT="隠す"
P1: ACTION/PROPS="eating too much" | TEXT="食べすぎた" P2: ACTION/PROPS="rubbing belly" | TEXT="ぽんぽこ" P3: ACTION/PROPS="laying down" | TEXT="苦しい" P4: ACTION/PROPS="yawning" | TEXT="眠い" P5: ACTION/PROPS="sleeping on sheet" | TEXT="おやすみ" P6: ACTION/PROPS="snoring" | TEXT="ｚｚｚ" P7: ACTION/PROPS="waking up" | TEXT="はっ" P8: ACTION/PROPS="stretching" | TEXT="おはよう" P9: ACTION/PROPS="sunset" | TEXT="夕方だ"
P1: ACTION/PROPS="packing up" | TEXT="片付け" P2: ACTION/PROPS="folding sheet" | TEXT="畳む" P3: ACTION/PROPS="bag heavy" | TEXT="よっこいしょ" P4: ACTION/PROPS="trash bag" | TEXT="ゴミは持ち帰る" P5: ACTION/PROPS="looking back" | TEXT="楽しかった" P6: ACTION/PROPS="waving" | TEXT="また来よう" P7: ACTION/PROPS="walking home" | TEXT="帰るよ" P8: ACTION/PROPS="smiling" | TEXT="大満足" P9: ACTION/PROPS="bowing" | TEXT="おつかれ"
"""
save_csv('全身タイツｘ春を感じるｘピクニックのお弁当タイム', d4)

d5="""
P1: ACTION/PROPS="crawling out of hole" | TEXT="おはよう" P2: ACTION/PROPS="yawning huge" | TEXT="大あくび" P3: ACTION/PROPS="rubbing eyes" | TEXT="春だ" P4: ACTION/PROPS="sunlight" | TEXT="眩しい" P5: ACTION/PROPS="stretching arms" | TEXT="伸びー" P6: ACTION/PROPS="cracking back" | TEXT="ポキッ" P7: ACTION/PROPS="pain face" | TEXT="痛っ" P8: ACTION/PROPS="holding back" | TEXT="腰が" P9: ACTION/PROPS="slowly standing" | TEXT="よっこいしょ"
P1: ACTION/PROPS="radio gymnastics" | TEXT="体操" P2: ACTION/PROPS="deep breath" | TEXT="深呼吸" P3: ACTION/PROPS="bending forward" | TEXT="前屈" P4: ACTION/PROPS="can't reach toes" | TEXT="届かない" P5: ACTION/PROPS="sweating" | TEXT="硬い" P6: ACTION/PROPS="forcing it" | TEXT="むぎぎ" P7: ACTION/PROPS="collapsing" | TEXT="限界" P8: ACTION/PROPS="panting" | TEXT="ハァハァ" P9: ACTION/PROPS="thumbs up" | TEXT="頑張った"
P1: ACTION/PROPS="jogging in place" | TEXT="足踏み" P2: ACTION/PROPS="jumping jacks" | TEXT="ジャンプ" P3: ACTION/PROPS="high knees" | TEXT="もも上げ" P4: ACTION/PROPS="tripping" | TEXT="おっと" P5: ACTION/PROPS="falling" | TEXT="ドテッ" P6: ACTION/PROPS="rubbing head" | TEXT="イタタ" P7: ACTION/PROPS="laughing" | TEXT="なまってる" P8: ACTION/PROPS="standing up" | TEXT="もう一回" P9: ACTION/PROPS="fighting pose" | TEXT="やるぞ"
P1: ACTION/PROPS="yoga tree pose" | TEXT="ヨガ" P2: ACTION/PROPS="wobbling" | TEXT="グラグラ" P3: ACTION/PROPS="falling over" | TEXT="あわわ" P4: ACTION/PROPS="downward dog" | TEXT="犬のポーズ" P5: ACTION/PROPS="shaking arms" | TEXT="ぷるぷる" P6: ACTION/PROPS="exhausted" | TEXT="終了" P7: ACTION/PROPS="drinking protein" | TEXT="プロテイン" P8: ACTION/PROPS="flexing muscle" | TEXT="マッスル" P9: ACTION/PROPS="proud" | TEXT="ドヤ"
P1: ACTION/PROPS="butterfly flies by" | TEXT="あ" P2: ACTION/PROPS="chasing it" | TEXT="まて" P3: ACTION/PROPS="running fast" | TEXT="ダッシュ" P4: ACTION/PROPS="out of breath" | TEXT="ゼェゼェ" P5: ACTION/PROPS="cramping leg" | TEXT="足つった" P6: ACTION/PROPS="holding leg crying" | TEXT="痛い" P7: ACTION/PROPS="rolling ground" | TEXT="のたうち回る" P8: ACTION/PROPS="calming down" | TEXT="治った" P9: ACTION/PROPS="sigh" | TEXT="準備運動大事"
P1: ACTION/PROPS="looking in mirror" | TEXT="鏡" P2: ACTION/PROPS="touching belly" | TEXT="太った？" P3: ACTION/PROPS="shocked" | TEXT="マジか" P4: ACTION/PROPS="measuring tape" | TEXT="現実逃避" P5: ACTION/PROPS="crying" | TEXT="ダイエット" P6: ACTION/PROPS="running" | TEXT="走るぞ" P7: ACTION/PROPS="burning aura" | TEXT="燃える" P8: ACTION/PROPS="confident" | TEXT="絶対痩せる" P9: ACTION/PROPS="pointing" | TEXT="見てろよ"
"""
save_csv('全身タイツｘ春を感じるｘ冬眠明けの全力ストレッチ', d5)

d6="""
P1: ACTION/PROPS="looking at closet" | TEXT="衣替え" P2: ACTION/PROPS="pulling out tights" | TEXT="冬用" P3: ACTION/PROPS="putting in box" | TEXT="しまう" P4: ACTION/PROPS="taking out spring tights" | TEXT="春用" P5: ACTION/PROPS="sparkling tights" | TEXT="新品" P6: ACTION/PROPS="putting it on" | TEXT="お着替え" P7: ACTION/PROPS="zipping up" | TEXT="ジーッ" P8: ACTION/PROPS="posing" | TEXT="完成" P9: ACTION/PROPS="smiling" | TEXT="似合う？"
P1: ACTION/PROPS="pastel pink tights" | TEXT="桜色" P2: ACTION/PROPS="twirling" | TEXT="クルッ" P3: ACTION/PROPS="posing cute" | TEXT="かわいい" P4: ACTION/PROPS="light green tights" | TEXT="若草色" P5: ACTION/PROPS="stretching" | TEXT="伸びる" P6: ACTION/PROPS="comfortable" | TEXT="着心地最高" P7: ACTION/PROPS="yellow tights" | TEXT="菜の花色" P8: ACTION/PROPS="jumping" | TEXT="軽快" P9: ACTION/PROPS="happy" | TEXT="るんるん"
P1: ACTION/PROPS="tights too tight" | TEXT="きつい" P2: ACTION/PROPS="struggling to zip" | TEXT="閉まらない" P3: ACTION/PROPS="sucking in belly" | TEXT="ふんっ" P4: ACTION/PROPS="zipper breaks" | TEXT="あっ" P5: ACTION/PROPS="crying" | TEXT="破れた" P6: ACTION/PROPS="sewing" | TEXT="チクチク" P7: ACTION/PROPS="wearing with patch" | TEXT="直した" P8: ACTION/PROPS="sighing" | TEXT="やれやれ" P9: ACTION/PROPS="diet thought" | TEXT="痩せなきゃ"
P1: ACTION/PROPS="cleaning closet" | TEXT="断捨離" P2: ACTION/PROPS="holding old tights" | TEXT="どうしよう" P3: ACTION/PROPS="remembering memories" | TEXT="思い出" P4: ACTION/PROPS="crying a bit" | TEXT="捨てられない" P5: ACTION/PROPS="hug tights" | TEXT="ありがとう" P6: ACTION/PROPS="putting in trash bag" | TEXT="さよなら" P7: ACTION/PROPS="wiping tear" | TEXT="スッキリ" P8: ACTION/PROPS="looking at empty closet" | TEXT="綺麗" P9: ACTION/PROPS="nodding" | TEXT="よし"
P1: ACTION/PROPS="shopping for tights" | TEXT="買い物" P2: ACTION/PROPS="looking at display" | TEXT="どれにしよう" P3: ACTION/PROPS="holding two colors" | TEXT="迷う" P4: ACTION/PROPS="asking clerk" | TEXT="どっちが良い？" P5: ACTION/PROPS="buying both" | TEXT="大人買い" P6: ACTION/PROPS="carrying bags" | TEXT="荷物いっぱい" P7: ACTION/PROPS="empty wallet" | TEXT="金欠" P8: ACTION/PROPS="crying laughing" | TEXT="やっちまった" P9: ACTION/PROPS="happy with purchase" | TEXT="幸せ"
P1: ACTION/PROPS="spring breeze" | TEXT="春風" P2: ACTION/PROPS="feeling light" | TEXT="身軽" P3: ACTION/PROPS="walking briskly" | TEXT="スキップ" P4: ACTION/PROPS="dancing" | TEXT="ステップ" P5: ACTION/PROPS="smelling flowers" | TEXT="いい匂い" P6: ACTION/PROPS="waving greeting" | TEXT="こんにちは" P7: ACTION/PROPS="bright smile" | TEXT="気分最高" P8: ACTION/PROPS="looking at sky" | TEXT="青空" P9: ACTION/PROPS="thumbs up" | TEXT="完璧"
"""
save_csv('全身タイツｘ春を感じるｘ春の衣替え（タイツの新調）', d6)

d7="""
P1: ACTION/PROPS="huge backpack" | TEXT="ピカピカ" P2: ACTION/PROPS="oversized uniform" | TEXT="ブカブカ" P3: ACTION/PROPS="walking stiffly" | TEXT="ガチガチ" P4: ACTION/PROPS="tripping" | TEXT="おっと" P5: ACTION/PROPS="rubbing head" | TEXT="てへへ" P6: ACTION/PROPS="looking at school gate" | TEXT="着いた" P7: ACTION/PROPS="sparkling eyes" | TEXT="ワクワク" P8: ACTION/PROPS="deep breath" | TEXT="深呼吸" P9: ACTION/PROPS="step forward" | TEXT="行くぞ"
P1: ACTION/PROPS="taking photo at gate" | TEXT="記念撮影" P2: ACTION/PROPS="peace sign" | TEXT="ピース" P3: ACTION/PROPS="awkward smile" | TEXT="ひきつる" P4: ACTION/PROPS="looking around" | TEXT="人多い" P5: ACTION/PROPS="lost" | TEXT="どこ？" P6: ACTION/PROPS="looking at map" | TEXT="迷子" P7: ACTION/PROPS="crying" | TEXT="助けて" P8: ACTION/PROPS="teacher points" | TEXT="あっちか" P9: ACTION/PROPS="bowing" | TEXT="ありがとうございます"
P1: ACTION/PROPS="sitting in chair tightly" | TEXT="緊張" P2: ACTION/PROPS="name called" | TEXT="はいっ" P3: ACTION/PROPS="voice too loud" | TEXT="響く" P4: ACTION/PROPS="blushing" | TEXT="恥ずかしい" P5: ACTION/PROPS="hiding face" | TEXT="穴があったら" P6: ACTION/PROPS="looking at desk" | TEXT="落ち着け" P7: ACTION/PROPS="sigh of relief" | TEXT="ふぅ" P8: ACTION/PROPS="clapping" | TEXT="拍手" P9: ACTION/PROPS="smiling" | TEXT="無事終了"
P1: ACTION/PROPS="talking to classmate" | TEXT="よろしくね" P2: ACTION/PROPS="shaking hands" | TEXT="友達" P3: ACTION/PROPS="exchanging contact" | TEXT="ポチポチ" P4: ACTION/PROPS="happy jump" | TEXT="できた" P5: ACTION/PROPS="walking together" | TEXT="一緒に帰ろ" P6: ACTION/PROPS="eating snacks" | TEXT="食べる？" P7: ACTION/PROPS="laughing" | TEXT="あはは" P8: ACTION/PROPS="waving goodbye" | TEXT="また明日" P9: ACTION/PROPS="skipping" | TEXT="るんるん"
P1: ACTION/PROPS="cherry blossom falls on head" | TEXT="桜" P2: ACTION/PROPS="holding it" | TEXT="綺麗" P3: ACTION/PROPS="putting it in diary" | TEXT="記念" P4: ACTION/PROPS="looking at sky" | TEXT="頑張る" P5: ACTION/PROPS="fist pump" | TEXT="エイエイオー" P6: ACTION/PROPS="running home" | TEXT="ただいま" P7: ACTION/PROPS="showing bag" | TEXT="見て見て" P8: ACTION/PROPS="proud face" | TEXT="えっへん" P9: ACTION/PROPS="sleeping exhausted" | TEXT="おやすみ"
P1: ACTION/PROPS="looking at textbook" | TEXT="分厚い" P2: ACTION/PROPS="opening it" | TEXT="パラパラ" P3: ACTION/PROPS="mind blank" | TEXT="わからん" P4: ACTION/PROPS="closing it fast" | TEXT="パタン" P5: ACTION/PROPS="ignoring it" | TEXT="見なかった事にする" P6: ACTION/PROPS="whistling" | TEXT="明日から本気出す" P7: ACTION/PROPS="thumbs up" | TEXT="よし" P8: ACTION/PROPS="lying on bed" | TEXT="休憩" P9: ACTION/PROPS="snoring" | TEXT="グー"
"""
save_csv('全身タイツｘ春を感じるｘ入学式で浮かれる新入生風', d7)

d8="""
P1: ACTION/PROPS="field of yellow flowers" | TEXT="菜の花" P2: ACTION/PROPS="covering eyes" | TEXT="もういいかい" P3: ACTION/PROPS="listening" | TEXT="耳を澄ます" P4: ACTION/PROPS="shouting" | TEXT="まぁだだよ" P5: ACTION/PROPS="waiting" | TEXT="まだ？" P6: ACTION/PROPS="shouting again" | TEXT="もういいよ" P7: ACTION/PROPS="opening eyes" | TEXT="探すぞ" P8: ACTION/PROPS="looking around" | TEXT="きょろきょろ" P9: ACTION/PROPS="walking stealthily" | TEXT="抜き足"
P1: ACTION/PROPS="crouching in flowers" | TEXT="隠れる" P2: ACTION/PROPS="holding breath" | TEXT="しーっ" P3: ACTION/PROPS="peeking through stems" | TEXT="チラッ" P4: ACTION/PROPS="footsteps approach" | TEXT="来た" P5: ACTION/PROPS="sweating" | TEXT="ドキドキ" P6: ACTION/PROPS="closing eyes tight" | TEXT="見つかる" P7: ACTION/PROPS="footsteps fade" | TEXT="行った" P8: ACTION/PROPS="sighing" | TEXT="ふー" P9: ACTION/PROPS="smiling sneaky" | TEXT="ふふふ"
P1: ACTION/PROPS="sneezing loudly" | TEXT="はっくしょん" P2: ACTION/PROPS="covering mouth" | TEXT="やばい" P3: ACTION/PROPS="found out" | TEXT="みっけ" P4: ACTION/PROPS="startled" | TEXT="バレた" P5: ACTION/PROPS="running away" | TEXT="逃げろ" P6: ACTION/PROPS="chasing" | TEXT="まてー" P7: ACTION/PROPS="tagging" | TEXT="タッチ" P8: ACTION/PROPS="falling laughing" | TEXT="捕まった" P9: ACTION/PROPS="breathing hard" | TEXT="疲れた"
P1: ACTION/PROPS="bee approaches" | TEXT="ブーン" P2: ACTION/PROPS="frozen stiff" | TEXT="蜂だ" P3: ACTION/PROPS="sweating waterfalls" | TEXT="動けない" P4: ACTION/PROPS="bee lands on nose" | TEXT="ひぃ" P5: ACTION/PROPS="cross eyed looking at bee" | TEXT="じーっ" P6: ACTION/PROPS="bee flies away" | TEXT="行った" P7: ACTION/PROPS="collapsing" | TEXT="腰抜けた" P8: ACTION/PROPS="crying" | TEXT="怖かった" P9: ACTION/PROPS="hugging knees" | TEXT="帰りたい"
P1: ACTION/PROPS="everyone went home" | TEXT="あれ？" P2: ACTION/PROPS="looking around empty field" | TEXT="誰もいない" P3: ACTION/PROPS="calling out" | TEXT="おーい" P4: ACTION/PROPS="echoing" | TEXT="しーん" P5: ACTION/PROPS="getting dark" | TEXT="夕方" P6: ACTION/PROPS="crying loud" | TEXT="置いてかれた" P7: ACTION/PROPS="friend comes back" | TEXT="ごめん" P8: ACTION/PROPS="hugging friend crying" | TEXT="うわーん" P9: ACTION/PROPS="walking home holding hands" | TEXT="帰ろう"
P1: ACTION/PROPS="making flower crown" | TEXT="編む" P2: ACTION/PROPS="putting on head" | TEXT="冠" P3: ACTION/PROPS="posing" | TEXT="似合う？" P4: ACTION/PROPS="giving to friend" | TEXT="あげる" P5: ACTION/PROPS="smiling together" | TEXT="かわいい" P6: ACTION/PROPS="smelling flowers" | TEXT="いい匂い" P7: ACTION/PROPS="laying in field" | TEXT="ごろん" P8: ACTION/PROPS="looking at clouds" | TEXT="空が青い" P9: ACTION/PROPS="peaceful" | TEXT="幸せ"
"""
save_csv('全身タイツｘ春を感じるｘ菜の花畑でかくれんぼ', d8)

d9="""
P1: ACTION/PROPS="holding sake pourer" | TEXT="銚子" P2: ACTION/PROPS="holding sake cup" | TEXT="盃" P3: ACTION/PROPS="holding long handle pourer" | TEXT="長柄銚子" P4: ACTION/PROPS="posing formally" | TEXT="三人官女" P5: ACTION/PROPS="kneeling perfectly" | TEXT="正座" P6: ACTION/PROPS="serious face" | TEXT="キリッ" P7: ACTION/PROPS="bowing together" | TEXT="おめでとうございます" P8: ACTION/PROPS="legs numb" | TEXT="足痺れた" P9: ACTION/PROPS="wobbling" | TEXT="プルプル"
P1: ACTION/PROPS="drinking sweet sake secretly" | TEXT="ごくごく" P2: ACTION/PROPS="getting tipsy flushed" | TEXT="ぽっ" P3: ACTION/PROPS="hiccup" | TEXT="ひっく" P4: ACTION/PROPS="laughing loudly" | TEXT="あはは" P5: ACTION/PROPS="dancing weirdly" | TEXT="踊る" P6: ACTION/PROPS="falling over" | TEXT="どてっ" P7: ACTION/PROPS="sleeping on floor" | TEXT="すやぁ" P8: ACTION/PROPS="scolded by emperor" | TEXT="怒られた" P9: ACTION/PROPS="apologizing profusely" | TEXT="ごめんなさい"
P1: ACTION/PROPS="looking at hina arare" | TEXT="ひなあられ" P2: ACTION/PROPS="eating one" | TEXT="ぱくっ" P3: ACTION/PROPS="sweet" | TEXT="甘い" P4: ACTION/PROPS="eating handful" | TEXT="もぐもぐ" P5: ACTION/PROPS="mouth full" | TEXT="んふー" P6: ACTION/PROPS="choking" | TEXT="ゲホッ" P7: ACTION/PROPS="drinking water" | TEXT="水" P8: ACTION/PROPS="relieved" | TEXT="死ぬかと" P9: ACTION/PROPS="eating more" | TEXT="やめられない"
P1: ACTION/PROPS="fighting over diamond mochi" | TEXT="菱餅" P2: ACTION/PROPS="pulling it" | TEXT="私のだ" P3: ACTION/PROPS="glaring" | TEXT="バチバチ" P4: ACTION/PROPS="mochi breaks" | TEXT="あ" P5: ACTION/PROPS="crying" | TEXT="割れた" P6: ACTION/PROPS="sharing pieces" | TEXT="分ける" P7: ACTION/PROPS="eating together" | TEXT="美味しいね" P8: ACTION/PROPS="smiling" | TEXT="仲良し" P9: ACTION/PROPS="tea time" | TEXT="ほっ"
P1: ACTION/PROPS="trying to be empress" | TEXT="お雛様" P2: ACTION/PROPS="sitting on top tier" | TEXT="よっこいしょ" P3: ACTION/PROPS="posing elegantly" | TEXT="おほほ" P4: ACTION/PROPS="empress glares" | TEXT="ジロッ" P5: ACTION/PROPS="sweating" | TEXT="すみません" P6: ACTION/PROPS="climbing down fast" | TEXT="逃げろ" P7: ACTION/PROPS="back to bottom tier" | TEXT="定位置" P8: ACTION/PROPS="sighing" | TEXT="落ち着く" P9: ACTION/PROPS="dusting off knees" | TEXT="パンパン"
P1: ACTION/PROPS="singing hina song" | TEXT="明かりをつけましょ" P2: ACTION/PROPS="swaying rhythm" | TEXT="ゆらゆら" P3: ACTION/PROPS="playing imaginary flute" | TEXT="ピーヒョロ" P4: ACTION/PROPS="hitting imaginary drum" | TEXT="ポンポン" P5: ACTION/PROPS="clapping" | TEXT="楽しい" P6: ACTION/PROPS="celebrating" | TEXT="お祭り" P7: ACTION/PROPS="throwing confetti" | TEXT="パーン" P8: ACTION/PROPS="laughing" | TEXT="わーい" P9: ACTION/PROPS="exhausted happy" | TEXT="満足"
"""
save_csv('全身タイツｘ春を感じるｘひな祭りの三人官女ごっこ', d9)

d10="""
P1: ACTION/PROPS="night cherry blossoms" | TEXT="夜桜" P2: ACTION/PROPS="looking up in awe" | TEXT="綺麗" P3: ACTION/PROPS="illuminated" | TEXT="ライトアップ" P4: ACTION/PROPS="standing very still" | TEXT="木になる" P5: ACTION/PROPS="blending in" | TEXT="同化" P6: ACTION/PROPS="holding branches" | TEXT="私は桜" P7: ACTION/PROPS="tourist takes photo" | TEXT="パシャ" P8: ACTION/PROPS="sweating not moving" | TEXT="動けない" P9: ACTION/PROPS="winking" | TEXT="バレてない"
P1: ACTION/PROPS="moonlight" | TEXT="月夜" P2: ACTION/PROPS="drinking sake under tree" | TEXT="花見酒" P3: ACTION/PROPS="face flushed" | TEXT="酔った" P4: ACTION/PROPS="dancing with petals" | TEXT="舞い踊る" P5: ACTION/PROPS="spinning" | TEXT="くるくる" P6: ACTION/PROPS="falling dizzy" | TEXT="目回った" P7: ACTION/PROPS="lying on ground" | TEXT="ごろん" P8: ACTION/PROPS="looking at moon" | TEXT="風流" P9: ACTION/PROPS="sleeping" | TEXT="むにゃ"
P1: ACTION/PROPS="cold night breeze" | TEXT="ヒュッ" P2: ACTION/PROPS="shivering violently" | TEXT="寒い" P3: ACTION/PROPS="rubbing arms" | TEXT="さすさす" P4: ACTION/PROPS="sneezing" | TEXT="クシュン" P5: ACTION/PROPS="wrapping in blanket" | TEXT="毛布" P6: ACTION/PROPS="drinking hot tea" | TEXT="あったかい" P7: ACTION/PROPS="relieved sigh" | TEXT="生き返る" P8: ACTION/PROPS="hugging hot drink" | TEXT="ぬくぬく" P9: ACTION/PROPS="runny nose" | TEXT="鼻水出た"
P1: ACTION/PROPS="spotlight on face" | TEXT="眩しい" P2: ACTION/PROPS="covering eyes" | TEXT="目がぁぁ" P3: ACTION/PROPS="squinting" | TEXT="見えない" P4: ACTION/PROPS="striking a pose in light" | TEXT="主役" P5: ACTION/PROPS="blowing a kiss" | TEXT="チュッ" P6: ACTION/PROPS="waving elegantly" | TEXT="ありがとう" P7: ACTION/PROPS="light turns off" | TEXT="消えた" P8: ACTION/PROPS="darkness confused" | TEXT="真っ暗" P9: ACTION/PROPS="feeling around" | TEXT="どこ"
P1: ACTION/PROPS="lantern glowing" | TEXT="提灯" P2: ACTION/PROPS="holding lantern close" | TEXT="明るい" P3: ACTION/PROPS="scary face lit from below" | TEXT="おばけ" P4: ACTION/PROPS="laughing mischievously" | TEXT="うらめしや" P5: ACTION/PROPS="friend gets scared" | TEXT="キャッ" P6: ACTION/PROPS="laughing hard" | TEXT="大成功" P7: ACTION/PROPS="friend hits him" | TEXT="ポカッ" P8: ACTION/PROPS="rubbing head sorry" | TEXT="ごめんて" P9: ACTION/PROPS="smiling together" | TEXT="仲良し"
P1: ACTION/PROPS="petals falling like snow" | TEXT="吹雪" P2: ACTION/PROPS="reaching out trying to catch" | TEXT="キャッチ" P3: ACTION/PROPS="missing" | TEXT="すか" P4: ACTION/PROPS="catching one" | TEXT="とれた" P5: ACTION/PROPS="making a wish" | TEXT="願い事" P6: ACTION/PROPS="blowing petal away" | TEXT="ふーっ" P7: ACTION/PROPS="watching it fly" | TEXT="綺麗だね" P8: ACTION/PROPS="hands together" | TEXT="春ですね" P9: ACTION/PROPS="gentle smile" | TEXT="微笑む"
"""
save_csv('全身タイツｘ春を感じるｘ夜桜のライトアップと一体化', d10)

d11="""
P1: ACTION/PROPS="stepping outside" | TEXT="いい天気" P2: ACTION/PROPS="stretching arms wide" | TEXT="のびのび" P3: ACTION/PROPS="walking cheerfully" | TEXT="お散歩" P4: ACTION/PROPS="swinging arms" | TEXT="ぶんぶん" P5: ACTION/PROPS="humming" | TEXT="ふふーん" P6: ACTION/PROPS="greeting dog" | TEXT="ワンちゃん" P7: ACTION/PROPS="petting dog" | TEXT="よしよし" P8: ACTION/PROPS="dog licks face" | TEXT="くすぐったい" P9: ACTION/PROPS="waving" | TEXT="バイバイ"
P1: ACTION/PROPS="finding a sunny spot" | TEXT="ここいいな" P2: ACTION/PROPS="sitting on bench" | TEXT="よっこいしょ" P3: ACTION/PROPS="closing eyes facing sun" | TEXT="ぽかぽか" P4: ACTION/PROPS="melting relaxed" | TEXT="溶けそう" P5: ACTION/PROPS="nodding off" | TEXT="うとうと" P6: ACTION/PROPS="head falls forward waking up" | TEXT="はっ" P7: ACTION/PROPS="wiping drool" | TEXT="よだれ" P8: ACTION/PROPS="looking around pretending" | TEXT="起きてたよ" P9: ACTION/PROPS="laughing embarrassed" | TEXT="あはは"
P1: ACTION/PROPS="smelling bakery outisde" | TEXT="いい匂い" P2: ACTION/PROPS="following scent floating" | TEXT="ふらふら" P3: ACTION/PROPS="looking through window" | TEXT="パンだ" P4: ACTION/PROPS="drooling" | TEXT="食べたい" P5: ACTION/PROPS="checking empty pockets" | TEXT="財布ない" P6: ACTION/PROPS="crying anime style" | TEXT="ガーン" P7: ACTION/PROPS="pressing face on glass" | TEXT="ぐぬぬ" P8: ACTION/PROPS="sighing walking away" | TEXT="諦めよ" P9: ACTION/PROPS="belly rumbling loudly" | TEXT="ぐぅぅ"
P1: ACTION/PROPS="walking down path" | TEXT="てくてく" P2: ACTION/PROPS="stepping on puddle" | TEXT="バシャ" P3: ACTION/PROPS="looking at muddy leg" | TEXT="あーあ" P4: ACTION/PROPS="shaking leg off" | TEXT="ぶるぶる" P5: ACTION/PROPS="finding a colorful pebble" | TEXT="おっ" P6: ACTION/PROPS="picking it up examining" | TEXT="綺麗" P7: ACTION/PROPS="putting in pocket" | TEXT="宝物" P8: ACTION/PROPS="skipping" | TEXT="ルンルン" P9: ACTION/PROPS="whistling" | TEXT="ご機嫌"
P1: ACTION/PROPS="looking up at birds" | TEXT="鳥だ" P2: ACTION/PROPS="flapping arms imitating" | TEXT="パタパタ" P3: ACTION/PROPS="jumping trying to fly" | TEXT="飛べない" P4: ACTION/PROPS="landing heavy on feet" | TEXT="ズスン" P5: ACTION/PROPS="rubbing ankles" | TEXT="イタタ" P6: ACTION/PROPS="shaking head laughing" | TEXT="人間だもの" P7: ACTION/PROPS="giving thumbs up to birds" | TEXT="いいな" P8: ACTION/PROPS="putting hands on hips" | TEXT="さてと" P9: ACTION/PROPS="walking home" | TEXT="帰ろう"
P1: ACTION/PROPS="watching sunset" | TEXT="夕焼け" P2: ACTION/PROPS="stretching long shadow" | TEXT="影が伸びた" P3: ACTION/PROPS="stomping on shadow" | TEXT="えいっ" P4: ACTION/PROPS="playing alone" | TEXT="影ふみ" P5: ACTION/PROPS="stomach growls" | TEXT="腹減った" P6: ACTION/PROPS="smelling dinner from house" | TEXT="カレーの匂い" P7: ACTION/PROPS="running fast toward home" | TEXT="ダッシュ" P8: ACTION/PROPS="opening door" | TEXT="ただいま" P9: ACTION/PROPS="big smile" | TEXT="帰宅"
"""
save_csv('全身タイツｘ春を感じるｘ春の陽気に誘われて散歩', d11)

print("生成完了しました！")
