import os
import csv

os.makedirs('outputs/prompts', exist_ok=True)

def generate_theme_csv(theme_name, data_rows):
    filename = f'outputs/prompts/{theme_name}_prompts.csv'
    with open(filename, 'w', encoding='utf-8-sig', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['prompt'])
        for row in data_rows:
            writer.writerow([row])

# --- Theme 1: 和服美人ｘ春を感じるｘ満開の桜 ---
theme1_data = [
    'P1: ACTION/PROPS="Smiling softly, looking up at cherry blossoms" | TEXT="春ですね" P2: ACTION/PROPS="Catching a falling cherry blossom petal" | TEXT="綺麗" P3: ACTION/PROPS="Holding a pink parasol under the blossoms" | TEXT="お出かけ日和" P4: ACTION/PROPS="Sitting on a red bench, drinking tea" | TEXT="ほっと一息" P5: ACTION/PROPS="Waving hand with a bright smile" | TEXT="おはよう" P6: ACTION/PROPS="Closing eyes against the spring breeze" | TEXT="心地よい風" P7: ACTION/PROPS="Pointing at a beautiful cherry tree branch" | TEXT="見てみて" P8: ACTION/PROPS="Walking gracefully on a petal-covered path" | TEXT="行ってきます" P9: ACTION/PROPS="Looking affectionately at a single cherry blossom" | TEXT="ありがとう"',
    'P1: ACTION/PROPS="Clapping hands excitedly" | TEXT="わぁ、満開" P2: ACTION/PROPS="Taking a selfie with cherry blossoms" | TEXT="記念撮影！" P3: ACTION/PROPS="Adjusting kimono collar gently" | TEXT="身嗜み" P4: ACTION/PROPS="Laughing with eyes closed" | TEXT="ふふふ" P5: ACTION/PROPS="Tying hair up while looking at flowers" | TEXT="さてと" P6: ACTION/PROPS="Holding hands out to feel the warmth" | TEXT="あたたかい" P7: ACTION/PROPS="Curious look, tilting head under the tree" | TEXT="どうしたの？" P8: ACTION/PROPS="Bowing politely" | TEXT="よろしくお願いします" P9: ACTION/PROPS="Waving goodbye gently" | TEXT="またね"',
    'P1: ACTION/PROPS="Looking tired, wiping forehead" | TEXT="少し休憩" P2: ACTION/PROPS="Wiping tear from eye emotionally" | TEXT="感動しました" P3: ACTION/PROPS="Looking surprised with hand on cheek" | TEXT="びっくり" P4: ACTION/PROPS="Holding up an OK sign" | TEXT="了解です" P5: ACTION/PROPS="Nodding enthusiastically" | TEXT="うんうん！" P6: ACTION/PROPS="Looking regretful, hands together" | TEXT="ごめんなさい" P7: ACTION/PROPS="Hand on chest, relieved" | TEXT="よかった" P8: ACTION/PROPS="Offering a gentle smile" | TEXT="お疲れ様" P9: ACTION/PROPS="Looking up at the night cherry blossoms" | TEXT="おやすみなさい"',
    'P1: ACTION/PROPS="Holding a bento box" | TEXT="お弁当" P2: ACTION/PROPS="Offering a cup of tea" | TEXT="お茶どうぞ" P3: ACTION/PROPS="Looking thoughtful, touching chin" | TEXT="うーん…" P4: ACTION/PROPS="Sparkling eyes, looking excitedly" | TEXT="楽しみ！" P5: ACTION/PROPS="Crossing arms gently, smiling" | TEXT="ふむふむ" P6: ACTION/PROPS="Hand covering mouth while laughing" | TEXT="おほほ" P7: ACTION/PROPS="Finger to lips gently" | TEXT="内緒ですよ" P8: ACTION/PROPS="Patting shoulder playfully" | TEXT="元気出して" P9: ACTION/PROPS="Cheering with a small fist pump" | TEXT="頑張って！"',
    'P1: ACTION/PROPS="Walking briskly with purpose" | TEXT="急ぎます" P2: ACTION/PROPS="Stopping to tie obi ribbon" | TEXT="ちょっと待って" P3: ACTION/PROPS="Looking warmly, hands folded" | TEXT="いつもありがとう" P4: ACTION/PROPS="Sighing softly" | TEXT="ふぅ" P5: ACTION/PROPS="Looking proud with hands on hips" | TEXT="任せて！" P6: ACTION/PROPS="Giving a thumbs up" | TEXT="バッチリ" P7: ACTION/PROPS="Bowing deeply" | TEXT="感謝いたします" P8: ACTION/PROPS="Looking shy, looking down" | TEXT="照れますね" P9: ACTION/PROPS="Stretching arms out feeling good" | TEXT="いいお天気"',
    'P1: ACTION/PROPS="Peeking from behind a cherry tree" | TEXT="ちらっ" P2: ACTION/PROPS="Jumping lightly with joy" | TEXT="やったー！" P3: ACTION/PROPS="Looking away, pretending not to notice" | TEXT="知らない" P4: ACTION/PROPS="Touching forehead, confused" | TEXT="あれれ？" P5: ACTION/PROPS="Hands on cheeks in awe" | TEXT="すごい！" P6: ACTION/PROPS="Pouting slightly" | TEXT="むー" P7: ACTION/PROPS="Wiping sweat with a handkerchief" | TEXT="あつあつ" P8: ACTION/PROPS="Holding stomach, laughing" | TEXT="お腹痛い" P9: ACTION/PROPS="Sleeping under the cherry blossoms gently" | TEXT="むにゃむにゃ"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ満開の桜', theme1_data)

# --- Theme 2: 和服美人ｘ春を感じるｘ和菓子とお茶 ---
theme2_data = [
    'P1: ACTION/PROPS="Holding a tray with matcha and wagashi" | TEXT="お茶にしましょう" P2: ACTION/PROPS="Eating a pink sakura mochi" | TEXT="美味しい！" P3: ACTION/PROPS="Sipping green tea elegantly" | TEXT="ほっとします" P4: ACTION/PROPS="Offering a wagashi on a small dish" | TEXT="どうぞ召し上がれ" P5: ACTION/PROPS="Looking at colourful wagashi with sparkling eyes" | TEXT="どれにしようかな" P6: ACTION/PROPS="Wiping lips with a small beautiful paper" | TEXT="ごちそうさま" P7: ACTION/PROPS="Blowing lightly on hot tea" | TEXT="ふーふー" P8: ACTION/PROPS="Holding a traditional teapot" | TEXT="おかわりいかがですか？" P9: ACTION/PROPS="Smiling with a tea whisk (chasen)" | TEXT="点てますね"',
    'P1: ACTION/PROPS="Clapping hands gently in delight" | TEXT="いただきます" P2: ACTION/PROPS="Looking deeply satisfied after drinking tea" | TEXT="至福の時間" P3: ACTION/PROPS="Cutting wagashi with a small wooden pick" | TEXT="上品にね" P4: ACTION/PROPS="Nodding while enjoying the flavour" | TEXT="味わい深い" P5: ACTION/PROPS="Smelling the aroma of tea" | TEXT="いい香り" P6: ACTION/PROPS="Looking thoughtful next to teapot" | TEXT="落ち着く…" P7: ACTION/PROPS="Laughing while holding a teacup" | TEXT="楽しいですね" P8: ACTION/PROPS="Surprised by the sweetness" | TEXT="甘くて美味しい" P9: ACTION/PROPS="Tilting head with a wagashi pick" | TEXT="おひとついかが？"',
    'P1: ACTION/PROPS="Waving hand softly" | TEXT="いってらっしゃい" P2: ACTION/PROPS="Looking happy with a sakura manju" | TEXT="春の味ですね" P3: ACTION/PROPS="Putting hands together in appreciation" | TEXT="ありがとうございます" P4: ACTION/PROPS="Looking shy, slightly hiding mouth with sleeve" | TEXT="お恥ずかしい" P5: ACTION/PROPS="Showing an empty plate" | TEXT="ぺろり" P6: ACTION/PROPS="Giving a gentle affirming nod" | TEXT="その通りです" P7: ACTION/PROPS="Pondering, finger to chin" | TEXT="そうですか" P8: ACTION/PROPS="Looking apologetic" | TEXT="お待たせしました" P9: ACTION/PROPS="Bowing graciously" | TEXT="お越しやす"',
    'P1: ACTION/PROPS="Looking up happily" | TEXT="いい一日" P2: ACTION/PROPS="Offering a seat gesture with hand" | TEXT="こちらへどうぞ" P3: ACTION/PROPS="Holding chest in relief" | TEXT="安心しました" P4: ACTION/PROPS="Crying small happy tears" | TEXT="嬉し泣き" P5: ACTION/PROPS="Gently scolding with a smile" | TEXT="もうっ" P6: ACTION/PROPS="Staring warmly into eyes" | TEXT="ずっと一緒" P7: ACTION/PROPS="Flicking hand lightly" | TEXT="気にしないで" P8: ACTION/PROPS="Thumbs up with tea in other hand" | TEXT="最高！" P9: ACTION/PROPS="Putting tea away" | TEXT="また明日"',
    'P1: ACTION/PROPS="Touching a decorated wagashi box" | TEXT="お土産です" P2: ACTION/PROPS="Opening the wagashi box excitedly" | TEXT="わくわく" P3: ACTION/PROPS="Holding hands out" | TEXT="貸して？" P4: ACTION/PROPS="Shaking head left and right" | TEXT="いえいえ" P5: ACTION/PROPS="Blinking fast in surprise" | TEXT="えっ！" P6: ACTION/PROPS="Pointing index finger up" | TEXT="ひらめいた" P7: ACTION/PROPS="Looking down, hands together" | TEXT="お手数かけます" P8: ACTION/PROPS="Patting someone on the back" | TEXT="大丈夫ですか？" P9: ACTION/PROPS="Looking back over shoulder" | TEXT="呼びました？"',
    'P1: ACTION/PROPS="Clasping hands near face" | TEXT="お願い" P2: ACTION/PROPS="Wiping table gently with cloth" | TEXT="きれいにきれいに" P3: ACTION/PROPS="Leaning forward with interest" | TEXT="それでそれで？" P4: ACTION/PROPS="Crossing fingers" | TEXT="祈ってます" P5: ACTION/PROPS="Yawning gracefully behind sleeve" | TEXT="ふわぁ" P6: ACTION/PROPS="Looking sleepy holding tea" | TEXT="眠くなってきました" P7: ACTION/PROPS="Stretching gently" | TEXT="うーんと" P8: ACTION/PROPS="Waving with both hands" | TEXT="ばいばい" P9: ACTION/PROPS="Dropping head slightly sleeping" | TEXT="スヤァ"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ和菓子とお茶', theme2_data)

# --- Theme 3: 和服美人ｘ春を感じるｘ日本の伝統色（淡いピンクや萌黄色） ---
theme3_data = [
    'P1: ACTION/PROPS="Wearing a pale pink kimono, smiling gently" | TEXT="春色ですね" P2: ACTION/PROPS="Wearing a light green kimono, looking fresh" | TEXT="爽やかです" P3: ACTION/PROPS="Looking at kimono sleeve happily" | TEXT="お気に入り" P4: ACTION/PROPS="Twirling lightly to show the kimono" | TEXT="どうですか？" P5: ACTION/PROPS="Adjusting a beautiful pale pink obijime" | TEXT="整えますね" P6: ACTION/PROPS="Holding a light green sensu (folding fan)" | TEXT="あおぎます" P7: ACTION/PROPS="Looking elegant with hands softly restings" | TEXT="美しい" P8: ACTION/PROPS="Pointing to a pale flower pattern" | TEXT="春らしいでしょ" P9: ACTION/PROPS="Touching a cherry blossom hairpin" | TEXT="ふうむ"',
    'P1: ACTION/PROPS="Smiling softly, eyes closed" | TEXT="幸せ" P2: ACTION/PROPS="Looking back elegantly" | TEXT="ふりむく" P3: ACTION/PROPS="Applauding lightly" | TEXT="パチパチ" P4: ACTION/PROPS="Nodding with a calm expression" | TEXT="承知いたしました" P5: ACTION/PROPS="Holding a pale pink umbrella" | TEXT="相合い傘" P6: ACTION/PROPS="Offering hand gently" | TEXT="手をつなごう" P7: ACTION/PROPS="Bowing slightly, smiling" | TEXT="ごきげんよう" P8: ACTION/PROPS="Looking surprised with hand at mouth" | TEXT="あらま" P9: ACTION/PROPS="Puffing cheeks slightly" | TEXT="ぷん"',
    'P1: ACTION/PROPS="Crossing arms with a smile" | TEXT="なるほど" P2: ACTION/PROPS="Looking worried" | TEXT="心配です" P3: ACTION/PROPS="Wiping tears with sleeve" | TEXT="ぐすん" P4: ACTION/PROPS="Cheering with both hands up" | TEXT="フレーフレー" P5: ACTION/PROPS="Showing an ok sign elegantly" | TEXT="OKよ" P6: ACTION/PROPS="Thumbs up with a wink" | TEXT="いいね" P7: ACTION/PROPS="Looking thoughtfully upwards" | TEXT="んー" P8: ACTION/PROPS="Laughing covering mouth with sleeve" | TEXT="くすくす" P9: ACTION/PROPS="Sighing deeply" | TEXT="はぁ…"',
    'P1: ACTION/PROPS="Waving happily" | TEXT="やっほー" P2: ACTION/PROPS="Bowing deeply in light green kimono" | TEXT="恐れ入ります" P3: ACTION/PROPS="Looking excited, leaning forward" | TEXT="ほんと？" P4: ACTION/PROPS="Putting index finger on lip" | TEXT="シーッ" P5: ACTION/PROPS="Hand on hip playfully" | TEXT="どうしようかな" P6: ACTION/PROPS="Touching cheek bashfully" | TEXT="いやだなぁ" P7: ACTION/PROPS="Holding a small flower bouquet" | TEXT="プレゼント" P8: ACTION/PROPS="Looking proud" | TEXT="えへん！" P9: ACTION/PROPS="Holding hand to ear to listen" | TEXT="なんて？"',
    'P1: ACTION/PROPS="Looking up at the sun shielding eyes" | TEXT="まぶしい" P2: ACTION/PROPS="Shivering slightly in breeze" | TEXT="少し肌寒い" P3: ACTION/PROPS="Offering a gentle embrace gesture" | TEXT="おいで" P4: ACTION/PROPS="Patting head gently" | TEXT="よしよし" P5: ACTION/PROPS="Looking lonely" | TEXT="さみしい" P6: ACTION/PROPS="Holding phone gracefully" | TEXT="電話します" P7: ACTION/PROPS="Typing on phone with a smile" | TEXT="返信中" P8: ACTION/PROPS="Looking surprised at screen" | TEXT="本当？！" P9: ACTION/PROPS="Taking a picture with phone" | TEXT="パシャリ"',
    'P1: ACTION/PROPS="Waving both hands frantically" | TEXT="ばいばーい" P2: ACTION/PROPS="Rubbing eyes sleepily" | TEXT="ねむい" P3: ACTION/PROPS="Laying head on arms on table" | TEXT="ぐったり" P4: ACTION/PROPS="Waking up stretching" | TEXT="おはよ" P5: ACTION/PROPS="Looking determined softly" | TEXT="やります" P6: ACTION/PROPS="Hand on chest gratefully" | TEXT="ありがたい" P7: ACTION/PROPS="Looking slightly annoyed" | TEXT="もう" P8: ACTION/PROPS="Giggling with eyes closed" | TEXT="あはは" P9: ACTION/PROPS="Waving goodbye warmly" | TEXT="いってらっしゃい"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ日本の伝統色（淡いピンクや萌黄色）', theme3_data)

# --- Theme 4: 和服美人ｘ春を感じるｘ縁側でのうたた寝 ---
theme4_data = [
    'P1: ACTION/PROPS="Sleeping peacefully on the veranda (engawa)" | TEXT="すやすや" P2: ACTION/PROPS="Waking up, rubbing eyes" | TEXT="んっ？" P3: ACTION/PROPS="Yawning delicately" | TEXT="ふわぁ…" P4: ACTION/PROPS="Stretching arms out on the veranda" | TEXT="よく寝た" P5: ACTION/PROPS="Sitting on veranda, feeling the breeze" | TEXT="ぽかぽかする" P6: ACTION/PROPS="Looking at a sleeping cat next to her" | TEXT="可愛いね" P7: ACTION/PROPS="Resting head on knees" | TEXT="のどか" P8: ACTION/PROPS="Smiling softly at the garden" | TEXT="癒されます" P9: ACTION/PROPS="Leaning against a pillar drowsily" | TEXT="うとうと"',
    'P1: ACTION/PROPS="Putting a blanket over shoulders" | TEXT="少し冷える？" P2: ACTION/PROPS="Holding a warm cup, looking sleepy" | TEXT="温まる" P3: ACTION/PROPS="Softly patting the sleeping spot" | TEXT="ここおいで" P4: ACTION/PROPS="Looking softly over shoulder" | TEXT="おやすみ" P5: ACTION/PROPS="Closing eyes against sunlight" | TEXT="まどろむ" P6: ACTION/PROPS="Brushing hair behind ear sleepily" | TEXT="まだ眠い" P7: ACTION/PROPS="Nodding off and waking up suddenly" | TEXT="はっ" P8: ACTION/PROPS="Laughing at falling asleep" | TEXT="寝ちゃってた" P9: ACTION/PROPS="Smiling warmly at the camera" | TEXT="いい夢を"',
    'P1: ACTION/PROPS="Sighing contentedly" | TEXT="極楽" P2: ACTION/PROPS="Listening to the wind chimes" | TEXT="チリンチリン" P3: ACTION/PROPS="Adjusting rumpled kimono collar" | TEXT="乱れちゃった" P4: ACTION/PROPS="Bowing head slightly" | TEXT="失礼しました" P5: ACTION/PROPS="Clapping hands once" | TEXT="よし！" P6: ACTION/PROPS="Looking refreshed and awake" | TEXT="完全復活" P7: ACTION/PROPS="Raising hand lightly" | TEXT="やあ" P8: ACTION/PROPS="Thumbs up sign" | TEXT="いいね！" P9: ACTION/PROPS="Pointing to the side" | TEXT="あちらへ"',
    'P1: ACTION/PROPS="Looking surprised at the time" | TEXT="もうこんな時間！" P2: ACTION/PROPS="Hurrying to get up" | TEXT="急がなきゃ" P3: ACTION/PROPS="Looking apologetic" | TEXT="ごめんね" P4: ACTION/PROPS="Hands together in apology" | TEXT="許して" P5: ACTION/PROPS="Tilting head confused" | TEXT="どうしたの？" P6: ACTION/PROPS="Pouting cheeks" | TEXT="起こしてよー" P7: ACTION/PROPS="Laughing playfully" | TEXT="うそだよん" P8: ACTION/PROPS="Looking impressed" | TEXT="おおっ" P9: ACTION/PROPS="Clapping slowly" | TEXT="素晴らしい"',
    'P1: ACTION/PROPS="Waving to someone in garden" | TEXT="おーい" P2: ACTION/PROPS="Signalling to come closer" | TEXT="こっちこっち" P3: ACTION/PROPS="Looking pleased" | TEXT="満足" P4: ACTION/PROPS="Wiping a happy tear" | TEXT="幸せすぎる" P5: ACTION/PROPS="Holding both hands in joy" | TEXT="わーい" P6: ACTION/PROPS="Showing an OK gesture" | TEXT="オッケー" P7: ACTION/PROPS="Crossing arms thinking" | TEXT="さてと" P8: ACTION/PROPS="Nodding strongly" | TEXT="間違いない" P9: ACTION/PROPS="Looking up gratefully" | TEXT="ありがとう"',
    'P1: ACTION/PROPS="Shivering, rubbing arms" | TEXT="ぶるぶる" P2: ACTION/PROPS="Sneezing delicately" | TEXT="くしゅん" P3: ACTION/PROPS="Laughing heartily" | TEXT="あははは" P4: ACTION/PROPS="Looking deeply into eyes" | TEXT="じーっ" P5: ACTION/PROPS="Blushing furiously" | TEXT="ぽっ" P6: ACTION/PROPS="Hiding face with hands" | TEXT="見ないで" P7: ACTION/PROPS="Peeking through fingers" | TEXT="まだ見てる？" P8: ACTION/PROPS="Waving goodbye sleepily" | TEXT="また明日" P9: ACTION/PROPS="Falling back asleep" | TEXT="Zzz..."'
]
generate_theme_csv('和服美人ｘ春を感じるｘ縁側でのうたた寝', theme4_data)

# --- Theme 5: 和服美人ｘ春を感じるｘ大正ロマン・レトロモダン ---
theme5_data = [
    'P1: ACTION/PROPS="Wearing a retro modern kimono with a hakama, smiling" | TEXT="はいからさん" P2: ACTION/PROPS="Holding a retro parasol" | TEXT="モダンですね" P3: ACTION/PROPS="Adjusting a large ribbon in hair" | TEXT="どうかしら" P4: ACTION/PROPS="Walking gracefully with leather boots" | TEXT="ハイカラね" P5: ACTION/PROPS="Reading a classic literature book" | TEXT="読書中" P6: ACTION/PROPS="Looking up from a book, surprised" | TEXT="あら" P7: ACTION/PROPS="Sitting in a retro cafe chair" | TEXT="素敵" P8: ACTION/PROPS="Drinking tea from an antique cup" | TEXT="良いお味" P9: ACTION/PROPS="Smiling softly at the camera" | TEXT="ごきげんよう"',
    'P1: ACTION/PROPS="Holding a round pair of glasses playfully" | TEXT="にてる？" P2: ACTION/PROPS="Waving politely" | TEXT="こんにちは" P3: ACTION/PROPS="Putting hands together excitedly" | TEXT="楽しみ" P4: ACTION/PROPS="Looking curious, leaning forward" | TEXT="それは本当？" P5: ACTION/PROPS="Laughing, covering mouth with hand" | TEXT="おほほ" P6: ACTION/PROPS="Looking thoughtful, looking away" | TEXT="どうしよう" P7: ACTION/PROPS="Nodding elegantly" | TEXT="存じております" P8: ACTION/PROPS="Bowing deeply and gracefully" | TEXT="ありがとうございます" P9: ACTION/PROPS="Looking shy, avoiding gaze" | TEXT="恥ずかしい"',
    'P1: ACTION/PROPS="Holding up a classic pocket watch" | TEXT="時間です" P2: ACTION/PROPS="Rushing quickly but elegantly" | TEXT="急ぎますわ" P3: ACTION/PROPS="Sighing heavily" | TEXT="はぁ" P4: ACTION/PROPS="Looking sad, tearing up" | TEXT="悲しい" P5: ACTION/PROPS="Clapping hands gently" | TEXT="お見事" P6: ACTION/PROPS="Showing an OK sign" | TEXT="了見しました" P7: ACTION/PROPS="Giving a thumbs up" | TEXT="ばっちり" P8: ACTION/PROPS="Looking proud, hands on hips" | TEXT="任せて頂だい" P9: ACTION/PROPS="Pointing forward gracefully" | TEXT="あちらです"',
    'P1: ACTION/PROPS="Winking playfully" | TEXT="内緒よ" P2: ACTION/PROPS="Pouting angrily" | TEXT="ぷんぷん" P3: ACTION/PROPS="Looking surprised, dropping book" | TEXT="ええっ" P4: ACTION/PROPS="Picking up book calmly" | TEXT="失礼" P5: ACTION/PROPS="Holding stomach, laughing" | TEXT="可笑しい" P6: ACTION/PROPS="Offering a gentle smile" | TEXT="大丈夫よ" P7: ACTION/PROPS="Patting head gently" | TEXT="よしよし" P8: ACTION/PROPS="Cheering gently" | TEXT="がんばれ" P9: ACTION/PROPS="Clasping hands in prayer" | TEXT="無事を祈ります"',
    'P1: ACTION/PROPS="Looking elegant with a retro suitcase" | TEXT="旅に出ます" P2: ACTION/PROPS="Looking back, waving" | TEXT="いってきます" P3: ACTION/PROPS="Taking a picture with a vintage camera" | TEXT="はいチーズ" P4: ACTION/PROPS="Looking at a developed photo happily" | TEXT="綺麗に撮れた" P5: ACTION/PROPS="Writing a letter with a fountain pen" | TEXT="お手紙書くわ" P6: ACTION/PROPS="Giving the letter" | TEXT="どうぞ" P7: ACTION/PROPS="Receiving something gracefully" | TEXT="頂戴します" P8: ACTION/PROPS="Tying a shoelace of boots" | TEXT="ちょっと待って" P9: ACTION/PROPS="Leaning on an old gas lamp" | TEXT="夕暮れね"',
    'P1: ACTION/PROPS="Shivering in the spring evening" | TEXT="少し冷えるわ" P2: ACTION/PROPS="Wrapping a shawl around shoulders" | TEXT="温かい" P3: ACTION/PROPS="Yawning gracefully" | TEXT="ふわぁ" P4: ACTION/PROPS="Stretching elegantly" | TEXT="んっ" P5: ACTION/PROPS="Sleeping on a train bench" | TEXT="うとうと" P6: ACTION/PROPS="Looking out a train window" | TEXT="旅情ね" P7: ACTION/PROPS="Bowing to say goodbye" | TEXT="さようなら" P8: ACTION/PROPS="Waving gently" | TEXT="また明日" P9: ACTION/PROPS="Smiling with eyes closed softly" | TEXT="おやすみ"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ大正ロマン・レトロモダン', theme5_data)

# --- Theme 6: 和服美人ｘ春を感じるｘ庭園に集まる小鳥 ---
theme6_data = [
    'P1: ACTION/PROPS="Looking at a little bird on finger" | TEXT="かわいい" P2: ACTION/PROPS="Holding bird feed gently" | TEXT="どうぞ" P3: ACTION/PROPS="Smiling softly as birds fly around" | TEXT="春ですね" P4: ACTION/PROPS="Pointing to a bird on a branch" | TEXT="あそこにも" P5: ACTION/PROPS="Listening to bird chirping with closed eyes" | TEXT="いい声" P6: ACTION/PROPS="Looking curious at a baby bird" | TEXT="どうしたの？" P7: ACTION/PROPS="Clapping hands gently to call birds" | TEXT="おいで" P8: ACTION/PROPS="Waving goodbye to flying birds" | TEXT="またね" P9: ACTION/PROPS="Holding hands in delight" | TEXT="素敵"',
    'P1: ACTION/PROPS="Surprised by a bird landing on head" | TEXT="あらら" P2: ACTION/PROPS="Laughing as a bird tickles" | TEXT="くすぐったい" P3: ACTION/PROPS="Looking softly, smiling warmly" | TEXT="癒し" P4: ACTION/PROPS="Nodding while watching birds eat" | TEXT="うんうん" P5: ACTION/PROPS="Tilting head like a bird" | TEXT="チュンチュン？" P6: ACTION/PROPS="Sneaking quietly to not scare birds" | TEXT="そーっと" P7: ACTION/PROPS="Placing finger on lips" | TEXT="静かにね" P8: ACTION/PROPS="Wiping tear of joy" | TEXT="感動" P9: ACTION/PROPS="Looking at the sky where birds flew" | TEXT="行ってしまった"',
    'P1: ACTION/PROPS="Looking down apologetically" | TEXT="ごめんね" P2: ACTION/PROPS="Hands together in apology" | TEXT="申し訳ない" P3: ACTION/PROPS="Tearing up slightly" | TEXT="うう…" P4: ACTION/PROPS="Sighing softly" | TEXT="はぁ" P5: ACTION/PROPS="Cheering up quickly" | TEXT="元気出そう！" P6: ACTION/PROPS="Giving a thumbs up" | TEXT="大丈夫" P7: ACTION/PROPS="Showing an OK sign" | TEXT="オーケー" P8: ACTION/PROPS="Patting chest proudly" | TEXT="任せて" P9: ACTION/PROPS="Bowing respectfully" | TEXT="感謝します"',
    'P1: ACTION/PROPS="Looking happy, walking playfully" | TEXT="るんるん" P2: ACTION/PROPS="Skipping lightly" | TEXT="いい天気" P3: ACTION/PROPS="Waving enthusiastically" | TEXT="こっちこっち！" P4: ACTION/PROPS="Looking confused, scratching head" | TEXT="あれれ" P5: ACTION/PROPS="Pouting softly" | TEXT="むー" P6: ACTION/PROPS="Looking sleepy, rubbing eyes" | TEXT="ねむい" P7: ACTION/PROPS="Yawning gently behind a sleeve" | TEXT="ふわぁ" P8: ACTION/PROPS="Stretching with a smile" | TEXT="よし！" P9: ACTION/PROPS="Waving goodbye warmly" | TEXT="さようなら"',
    'P1: ACTION/PROPS="Holding a nice camera" | TEXT="撮るよー" P2: ACTION/PROPS="Looking at photo on camera" | TEXT="綺麗に撮れた" P3: ACTION/PROPS="Offering the camera to look" | TEXT="見てみて" P4: ACTION/PROPS="Looking shy and looking away" | TEXT="うふふ" P5: ACTION/PROPS="Covering face with sleeve" | TEXT="恥ずかしい" P6: ACTION/PROPS="Peeking through sleeve" | TEXT="ちらっ" P7: ACTION/PROPS="Opening arms to hug" | TEXT="おいでー" P8: ACTION/PROPS="Smiling warmly, tilting head" | TEXT="どうしたの？" P9: ACTION/PROPS="Giving a gentle affirming nod" | TEXT="そうですね"',
    'P1: ACTION/PROPS="Blowing a small whistle playfully" | TEXT="ピュー" P2: ACTION/PROPS="Holding a little watering can" | TEXT="お花にお水" P3: ACTION/PROPS="Looking proud of the garden" | TEXT="えっへん" P4: ACTION/PROPS="Sitting quietly with hands folded" | TEXT="お待ちしてます" P5: ACTION/PROPS="Standing tall" | TEXT="よろしくお願いします" P6: ACTION/PROPS="Running playfully" | TEXT="まてまてー" P7: ACTION/PROPS="Catching breath" | TEXT="ふー" P8: ACTION/PROPS="Looking up at the sun smiling" | TEXT="良い一日を" P9: ACTION/PROPS="Sleeping gently on a garden bench" | TEXT="すうすう"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ庭園に集まる小鳥', theme6_data)

# --- Theme 7: 和服美人ｘ春を感じるｘお花見弁当の彩り ---
theme7_data = [
    'P1: ACTION/PROPS="Holding a bright colourful bento box" | TEXT="お弁当" P2: ACTION/PROPS="Opening the bento with a smile" | TEXT="じゃーん！" P3: ACTION/PROPS="Offering an onigiri" | TEXT="どうぞ" P4: ACTION/PROPS="Eating a tamagoyaki happily" | TEXT="美味しい！" P5: ACTION/PROPS="Wiping mouth with a napkin elegantly" | TEXT="ごちそうさま" P6: ACTION/PROPS="Looking at an empty bento box" | TEXT="完食" P7: ACTION/PROPS="Patting full stomach gently" | TEXT="お腹いっぱい" P8: ACTION/PROPS="Looking excited, pointing at bento" | TEXT="どれが好き？" P9: ACTION/PROPS="Pondering what to eat next with chopsticks" | TEXT="迷うなぁ"',
    'P1: ACTION/PROPS="Looking proud with cooking utensils" | TEXT="私が作りました" P2: ACTION/PROPS="Giving a thumbs up" | TEXT="味見バッチリ" P3: ACTION/PROPS="Looking worried holding a bento" | TEXT="お口に合うかな" P4: ACTION/PROPS="Smiling with relief" | TEXT="よかった" P5: ACTION/PROPS="Clapping hands nicely" | TEXT="いただきます" P6: ACTION/PROPS="Offering tea with the bento" | TEXT="お茶もどうぞ" P7: ACTION/PROPS="Spreading a picnic mat" | TEXT="ここにしよ" P8: ACTION/PROPS="Sitting down elegantly on the mat" | TEXT="よっこいしょ" P9: ACTION/PROPS="Looking up at the cherry blossoms gently" | TEXT="最高だね"',
    'P1: ACTION/PROPS="Sighing contentedly" | TEXT="最高です" P2: ACTION/PROPS="Laughing behind her hand" | TEXT="うふふ" P3: ACTION/PROPS="Waving a friend over" | TEXT="こっちだよ！" P4: ACTION/PROPS="Looking surprised at a huge bento" | TEXT="すごい量" P5: ACTION/PROPS="Puffing cheeks, slightly mad" | TEXT="食べすぎ注意" P6: ACTION/PROPS="Holding hands defensively" | TEXT="もう食べられない" P7: ACTION/PROPS="Shaking head left and right" | TEXT="無理無理" P8: ACTION/PROPS="Nodding enthusiastically" | TEXT="最高！" P9: ACTION/PROPS="Giving a high five" | TEXT="イェイ"',
    'P1: ACTION/PROPS="Looking apologetic" | TEXT="遅れました" P2: ACTION/PROPS="Bowing deeply" | TEXT="お待たせ" P3: ACTION/PROPS="Holding hands together in apology" | TEXT="ごめんなさい！" P4: ACTION/PROPS="Looking slightly shy" | TEXT="一緒にお弁当どう？" P5: ACTION/PROPS="Smiling purely" | TEXT="嬉しい" P6: ACTION/PROPS="Giggling happily" | TEXT="あはは" P7: ACTION/PROPS="Pointing a chopstick playfully" | TEXT="それ狙ってる？" P8: ACTION/PROPS="Hiding bento playfully" | TEXT="あげないよ" P9: ACTION/PROPS="Giving the food playfully" | TEXT="あーん"',
    'P1: ACTION/PROPS="Looking sleepy after eating" | TEXT="眠くなってきた" P2: ACTION/PROPS="Yawning gently" | TEXT="ふわぁ" P3: ACTION/PROPS="Stretching arms out" | TEXT="うーん" P4: ACTION/PROPS="Laying down on the picnic mat" | TEXT="ごろりん" P5: ACTION/PROPS="Sleeping peacefully" | TEXT="すやすや" P6: ACTION/PROPS="Sitting back up looking refreshed" | TEXT="ぱっちり" P7: ACTION/PROPS="Cleaning up the bento box" | TEXT="お片付け" P8: ACTION/PROPS="Carrying the bento cloth bundle" | TEXT="帰ろう" P9: ACTION/PROPS="Looking back and smiling" | TEXT="また来ようね"',
    'P1: ACTION/PROPS="Looking warmly at friend" | TEXT="いつもありがとう" P2: ACTION/PROPS="Holding hand out" | TEXT="手をつなごう" P3: ACTION/PROPS="Walking side by side" | TEXT="楽しい" P4: ACTION/PROPS="Looking up happily" | TEXT="最高の日" P5: ACTION/PROPS="Waving goodbye softly" | TEXT="バイバイ" P6: ACTION/PROPS="Blowing a kiss playfully" | TEXT="ちゅっ" P7: ACTION/PROPS="Blushing furiously" | TEXT="恥ずかしい" P8: ACTION/PROPS="Running away playfully" | TEXT="じゃあねん" P9: ACTION/PROPS="Turning around to wave again" | TEXT="また明日"'
]
generate_theme_csv('和服美人ｘ春を感じるｘお花見弁当の彩り', theme7_data)

# --- Theme 8: 和服美人ｘ春を感じるｘしっとり濡れる菜種梅雨 ---
theme8_data = [
    'P1: ACTION/PROPS="Holding a beautiful wagasa (traditional umbrella)" | TEXT="雨ですね" P2: ACTION/PROPS="Looking at the rain gently" | TEXT="しとしと…" P3: ACTION/PROPS="Smiling under the umbrella" | TEXT="風情がありますね" P4: ACTION/PROPS="Holding out a hand to catch rain drops" | TEXT="冷たい" P5: ACTION/PROPS="Looking a bit sad the rain continues" | TEXT="やまないかな" P6: ACTION/PROPS="Looking relived as rain stops" | TEXT="やみました！" P7: ACTION/PROPS="Closing the wagasa elegantly" | TEXT="よかった" P8: ACTION/PROPS="Looking at a beautiful rainbow" | TEXT="虹！" P9: ACTION/PROPS="Pointing to the sky with a smile" | TEXT="綺麗"',
    'P1: ACTION/PROPS="Looking closely at a wet flower" | TEXT="しっとり" P2: ACTION/PROPS="Tilting umbrella to look up" | TEXT="あっ" P3: ACTION/PROPS="Offering the umbrella to someone" | TEXT="入りませんか" P4: ACTION/PROPS="Sharing an umbrella fondly" | TEXT="相合い傘" P5: ACTION/PROPS="Blushing slightly under the umbrella" | TEXT="近いですね" P6: ACTION/PROPS="Looking away shyly" | TEXT="えっと…" P7: ACTION/PROPS="Laughing lightly" | TEXT="ふふふ" P8: ACTION/PROPS="Holding onto a sleeve gently" | TEXT="離れないでね" P9: ACTION/PROPS="Looking deeply into eyes" | TEXT="好き"',
    'P1: ACTION/PROPS="Sneezing elegantly" | TEXT="くしゅん" P2: ACTION/PROPS="Rubbing shoulders cold" | TEXT="少し寒い" P3: ACTION/PROPS="Wrapping a shawl warmly" | TEXT="あたたかい" P4: ACTION/PROPS="Looking worried" | TEXT="風邪ひかないでね" P5: ACTION/PROPS="Patting back comfortingly" | TEXT="大丈夫？" P6: ACTION/PROPS="Nodding confidently" | TEXT="任せて" P7: ACTION/PROPS="Showing an OK sign" | TEXT="バッチリ" P8: ACTION/PROPS="Thumbs up with a wink" | TEXT="いいね！" P9: ACTION/PROPS="Clapping hands once" | TEXT="よし！"',
    'P1: ACTION/PROPS="Sighing looking at the rainy window" | TEXT="退屈だなぁ" P2: ACTION/PROPS="Pouting slightly" | TEXT="お出かけできない" P3: ACTION/PROPS="Looking excited suddenly" | TEXT="そうだ！" P4: ACTION/PROPS="Bringing out tea and wagashi" | TEXT="お茶にしましょう" P5: ACTION/PROPS="Reading a book gracefully by the window" | TEXT="読書日和" P6: ACTION/PROPS="Sleeping leaning on the table" | TEXT="うとうと" P7: ACTION/PROPS="Waking up blushing" | TEXT="寝てた！" P8: ACTION/PROPS="Sticking tongue out playfully" | TEXT="てへぺろ" P9: ACTION/PROPS="Waving hand dismissively" | TEXT="気にしないで"',
    'P1: ACTION/PROPS="Looking angry gracefully" | TEXT="ぷんぷん" P2: ACTION/PROPS="Turning away" | TEXT="知らない" P3: ACTION/PROPS="Looking back teary-eyed" | TEXT="本当に？" P4: ACTION/PROPS="Wiping tear softly" | TEXT="よかった" P5: ACTION/PROPS="Hugging warmly" | TEXT="ぎゅっ" P6: ACTION/PROPS="Smiling peacefully" | TEXT="安心した" P7: ACTION/PROPS="Holding both hands together" | TEXT="これお願い" P8: ACTION/PROPS="Bowing deeply" | TEXT="ありがとう" P9: ACTION/PROPS="Waving goodbye with wagasa" | TEXT="また明日ね"',
    'P1: ACTION/PROPS="Walking gracefully on wet pavement" | TEXT="足元気を付けて" P2: ACTION/PROPS="Stopping and turning around" | TEXT="どうしたの？" P3: ACTION/PROPS="Looking excited, pointing at something down" | TEXT="カエル！" P4: ACTION/PROPS="Looking scared, stepping back" | TEXT="ひゃっ" P5: ACTION/PROPS="Laughing at herself" | TEXT="びっくりした" P6: ACTION/PROPS="Breathing deeply" | TEXT="深呼吸" P7: ACTION/PROPS="Looking determined" | TEXT="がんばるぞ" P8: ACTION/PROPS="Raising fist softly" | TEXT="オー！" P9: ACTION/PROPS="Smiling warmly at camera" | TEXT="お疲れ様"'
]
generate_theme_csv('和服美人ｘ春を感じるｘしっとり濡れる菜種梅雨', theme8_data)

# --- Theme 9: 和服美人ｘ春を感じるｘ京都・鎌倉の寺社巡り ---
theme9_data = [
    'P1: ACTION/PROPS="Looking at a grand temple gate" | TEXT="着きました" P2: ACTION/PROPS="Putting hands together in prayer" | TEXT="お参りしましょう" P3: ACTION/PROPS="Tossing a coin into the offering box" | TEXT="お賽銭" P4: ACTION/PROPS="Bowing twice respectfully" | TEXT="二礼二拍手一礼" P5: ACTION/PROPS="Looking earnestly at a drawn omikuji (fortune)" | TEXT="大吉！" P6: ACTION/PROPS="Looking disappointed at fortune" | TEXT="凶だった…" P7: ACTION/PROPS="Tying the fortune to a designated string" | TEXT="結びます" P8: ACTION/PROPS="Holding an ema (wooden plaque) smiling" | TEXT="願い事" P9: ACTION/PROPS="Walking on stone steps gracefully" | TEXT="風情があります"',
    'P1: ACTION/PROPS="Looking tired, wiping forehead" | TEXT="少し疲れました" P2: ACTION/PROPS="Sitting on a red bench at a teahouse" | TEXT="休憩しましょう" P3: ACTION/PROPS="Eating matcha ice cream" | TEXT="冷たくて美味しい" P4: ACTION/PROPS="Looking refreshed and happy" | TEXT="元気出た" P5: ACTION/PROPS="Looking at a beautiful dry landscape garden" | TEXT="枯山水ですね" P6: ACTION/PROPS="Sighing with deep relaxation" | TEXT="心静まる" P7: ACTION/PROPS="Pondering deeply, looking at the moss" | TEXT="侘び寂び" P8: ACTION/PROPS="Nodding knowingly" | TEXT="なるほど" P9: ACTION/PROPS="Taking a fine picture with camera" | TEXT="良い構図"',
    'P1: ACTION/PROPS="Waving to a friend" | TEXT="おーい" P2: ACTION/PROPS="Rushing excitedly" | TEXT="急ごう！" P3: ACTION/PROPS="Looking puzzled, holding a map" | TEXT="迷子かも" P4: ACTION/PROPS="Tilting head cutely" | TEXT="どこかな？" P5: ACTION/PROPS="Looking relieved when found" | TEXT="あった！" P6: ACTION/PROPS="Giving a thumbs up" | TEXT="完璧です" P7: ACTION/PROPS="Doing a tiny victory pose" | TEXT="やったね" P8: ACTION/PROPS="Looking proud hands on hips" | TEXT="任せて" P9: ACTION/PROPS="Bowing politely to a monk" | TEXT="有難うございます"',
    'P1: ACTION/PROPS="Slipping on a stone, looking shocked" | TEXT="わっ！" P2: ACTION/PROPS="Being caught playfully" | TEXT="危なかった" P3: ACTION/PROPS="Laughing playfully, hiding mouth" | TEXT="おほほ" P4: ACTION/PROPS="Pouting lightly" | TEXT="笑わないで" P5: ACTION/PROPS="Looking at a beautiful weeping cherry tree" | TEXT="しだれ桜" P6: ACTION/PROPS="Clapping hands gently" | TEXT="見事ですね" P7: ACTION/PROPS="Smiling purely at someone" | TEXT="一緒に来れてよかった" P8: ACTION/PROPS="Blushing looking down" | TEXT="照れるな" P9: ACTION/PROPS="Looking up happily" | TEXT="最高の旅"',
    'P1: ACTION/PROPS="Looking sad, tearing up" | TEXT="感動です" P2: ACTION/PROPS="Wiping tears with handkerchief" | TEXT="ぐすっ" P3: ACTION/PROPS="Showing an OK sign gently" | TEXT="大丈夫" P4: ACTION/PROPS="Offering a hand" | TEXT="行きましょう" P5: ACTION/PROPS="Purchasing an omamori (amulet)" | TEXT="お守り買いました" P6: ACTION/PROPS="Giving the omamori to someone" | TEXT="どうぞ" P7: ACTION/PROPS="Clasping hands in a wish" | TEXT="ご利益ありますように" P8: ACTION/PROPS="Looking at sunset affectionately" | TEXT="夕暮れですね" P9: ACTION/PROPS="Stretching elegantly" | TEXT="あー疲れた"',
    'P1: ACTION/PROPS="Waving goodbye at the temple gate" | TEXT="また来ます" P2: ACTION/PROPS="Looking sleepy on the train back" | TEXT="うとうと" P3: ACTION/PROPS="Sleeping happily" | TEXT="すやすや" P4: ACTION/PROPS="Waking up refreshed" | TEXT="おはよう！" P5: ACTION/PROPS="Looking at souvenir bag" | TEXT="お土産だよ" P6: ACTION/PROPS="Offering the souvenir" | TEXT="つまらないものですが" P7: ACTION/PROPS="Smiling softly and warmly" | TEXT="お疲れ様でした" P8: ACTION/PROPS="Bowing deeply" | TEXT="お世話になりました" P9: ACTION/PROPS="Waving cheerfully" | TEXT="ばいばい"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ京都・鎌倉の寺社巡り', theme9_data)

# --- Theme 10: 和服美人ｘ春を感じるｘ幻想的な夜桜 ---
theme10_data = [
    'P1: ACTION/PROPS="Looking up in awe at illuminated night cherry blossoms" | TEXT="すごく綺麗" P2: ACTION/PROPS="Holding a paper lantern softly glowing" | TEXT="幻想的ですね" P3: ACTION/PROPS="Smiling mysteriously in the dark" | TEXT="ふふ" P4: ACTION/PROPS="Pointing to a beautiful branch" | TEXT="見て！" P5: ACTION/PROPS="Closing eyes, feeling the night breeze" | TEXT="夜風が気持ちいい" P6: ACTION/PROPS="Looking over shoulder elegantly" | TEXT="行きましょうか" P7: ACTION/PROPS="Offering hand" | TEXT="こっちです" P8: ACTION/PROPS="Walking gracefully on the path" | TEXT="静かですね" P9: ACTION/PROPS="Looking warmly at the person" | TEXT="ずっと見ていたい"',
    'P1: ACTION/PROPS="Shivering slightly in the night cold" | TEXT="少し冷えますね" P2: ACTION/PROPS="Wrapping shawl tighter" | TEXT="ぶるっ" P3: ACTION/PROPS="Looking surprised, receiving someone\'s warm coat" | TEXT="えっ" P4: ACTION/PROPS="Looking shy and happy" | TEXT="ありがとうございます" P5: ACTION/PROPS="Holding a hot drink" | TEXT="温かい" P6: ACTION/PROPS="Sneezing softly" | TEXT="くしゅん" P7: ACTION/PROPS="Rubbing nose playfully" | TEXT="恥ずかしい" P8: ACTION/PROPS="Looking worried" | TEXT="風邪ひかないでね" P9: ACTION/PROPS="Nodding gently" | TEXT="はい"',
    'P1: ACTION/PROPS="Taking a photo of the night sakura" | TEXT="上手く撮れない" P2: ACTION/PROPS="Looking puzzled at the camera screen" | TEXT="暗いなぁ" P3: ACTION/PROPS="Looking excited, asking for help" | TEXT="手伝って？" P4: ACTION/PROPS="Giving a thumbs up" | TEXT="さすがです！" P5: ACTION/PROPS="Clapping hands lightly" | TEXT="お見事" P6: ACTION/PROPS="Taking a selfie together" | TEXT="はいチーズ" P7: ACTION/PROPS="Looking at the selfie and laughing" | TEXT="いい笑顔" P8: ACTION/PROPS="Pouting cutely" | TEXT="私変な顔" P9: ACTION/PROPS="Sticking tongue out" | TEXT="もう一回！"',
    'P1: ACTION/PROPS="Looking sad, checking the time" | TEXT="もうこんな時間" P2: ACTION/PROPS="Looking reluctant to leave" | TEXT="帰りたくないな" P3: ACTION/PROPS="Looking down holding sleeves" | TEXT="うう…" P4: ACTION/PROPS="Looking up hopefully" | TEXT="また来ようね？" P5: ACTION/PROPS="Wiping a happy tear" | TEXT="うんうん" P6: ACTION/PROPS="Showing an OK sign cheerfully" | TEXT="約束！" P7: ACTION/PROPS="Linking pinky fingers" | TEXT="ゆびきりげんまん" P8: ACTION/PROPS="Smiling purely" | TEXT="絶対だよ" P9: ACTION/PROPS="Waving goodbye" | TEXT="また明日"',
    'P1: ACTION/PROPS="Looking tired, yawning" | TEXT="ふわぁ" P2: ACTION/PROPS="Rubbing eyes" | TEXT="眠くなってきちゃった" P3: ACTION/PROPS="Stretching arms out" | TEXT="ふぅ" P4: ACTION/PROPS="Looking apologetic" | TEXT="ごめんね" P5: ACTION/PROPS="Bowing lightly" | TEXT="お先です" P6: ACTION/PROPS="Turning back with a smile" | TEXT="ありがとうね" P7: ACTION/PROPS="Sending a flying kiss" | TEXT="ちゅ" P8: ACTION/PROPS="Running away blushing" | TEXT="きゃー" P9: ACTION/PROPS="Hiding face with sleeve" | TEXT="恥ずかしいっ"',
    'P1: ACTION/PROPS="Looking surprised at falling petals" | TEXT="花吹雪" P2: ACTION/PROPS="Catching a petal in hands" | TEXT="捕まえた" P3: ACTION/PROPS="Making a wish holding the petal" | TEXT="願い事" P4: ACTION/PROPS="Smiling peacefully" | TEXT="叶うといいな" P5: ACTION/PROPS="Looking determined" | TEXT="がんばる" P6: ACTION/PROPS="Raising fist softly" | TEXT="エイエイオー" P7: ACTION/PROPS="Bowing deeply and elegantly" | TEXT="大変お世話になりました" P8: ACTION/PROPS="Waving with both hands warmly" | TEXT="さようなら" P9: ACTION/PROPS="Looking up gratefully" | TEXT="おやすみなさい"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ幻想的な夜桜', theme10_data)

# --- Theme 11: 和服美人ｘ春を感じるｘ風に舞う花びら ---
theme11_data = [
    'P1: ACTION/PROPS="Looking up as petals dance in the wind" | TEXT="綺麗ですね" P2: ACTION/PROPS="Catching a petal elegantly" | TEXT="つかまえた" P3: ACTION/PROPS="Smiling purely amidst dancing petals" | TEXT="春霞" P4: ACTION/PROPS="Closing eyes, feeling the breeze" | TEXT="心地よい" P5: ACTION/PROPS="Holding kimono sleeves against the wind" | TEXT="風が強い" P6: ACTION/PROPS="Laughing as a petal lands on nose" | TEXT="くすぐったい" P7: ACTION/PROPS="Pointing to the floral snow" | TEXT="桜吹雪" P8: ACTION/PROPS="Spinning lightly with the wind" | TEXT="舞い散る" P9: ACTION/PROPS="Looking back warmly" | TEXT="ずっと見ていたい"',
    'P1: ACTION/PROPS="Running playfully through dancing petals" | TEXT="待ってー" P2: ACTION/PROPS="Looking amazed with hands clasped" | TEXT="うわぁ…" P3: ACTION/PROPS="Blowing a petal from hand" | TEXT="ふーっ" P4: ACTION/PROPS="Tilting head gracefully" | TEXT="どうしたの？" P5: ACTION/PROPS="Covering mouth, giggling" | TEXT="ふふふ" P6: ACTION/PROPS="Nodding knowingly" | TEXT="そうですね" P7: ACTION/PROPS="Wiping a sudden tear" | TEXT="なんだか泣ける" P8: ACTION/PROPS="Smiling brightly" | TEXT="元気出していこう" P9: ACTION/PROPS="Waving cheerfully" | TEXT="また明日"',
    'P1: ACTION/PROPS="Looking confused as a petal covers eye" | TEXT="前が見えない" P2: ACTION/PROPS="Brushing off petals from shoulder" | TEXT="よいしょ" P3: ACTION/PROPS="Looking down apologetically" | TEXT="ごめんなさい" P4: ACTION/PROPS="Sighing softly" | TEXT="はぁ" P5: ACTION/PROPS="Clapping hands gently" | TEXT="お見事！" P6: ACTION/PROPS="Giving a thumbs up" | TEXT="いいね！" P7: ACTION/PROPS="Patting chest safely" | TEXT="よかった" P8: ACTION/PROPS="Bowing deeply" | TEXT="感謝いたします" P9: ACTION/PROPS="Showing an OK sign" | TEXT="了解！"',
    'P1: ACTION/PROPS="Holding a broom, sweeping petals temporarily" | TEXT="お掃除お掃除" P2: ACTION/PROPS="Looking tired, wiping sweat" | TEXT="ふう" P3: ACTION/PROPS="Looking proud with hands on hips" | TEXT="綺麗になった！" P4: ACTION/PROPS="More petals fall immediately" | TEXT="あーあ…" P5: ACTION/PROPS="Laughing at the situation" | TEXT="仕方ないね" P6: ACTION/PROPS="Offering a cup of tea" | TEXT="一服どうぞ" P7: ACTION/PROPS="Pouting slightly" | TEXT="もう" P8: ACTION/PROPS="Winking playfully" | TEXT="内緒だよ" P9: ACTION/PROPS="Looking up happily" | TEXT="まあいっか"',
    'P1: ACTION/PROPS="Holding an umbrella to block petals" | TEXT="すごい舞ってる" P2: ACTION/PROPS="Peeking from behind the umbrella" | TEXT="ちらっ" P3: ACTION/PROPS="Looking worried" | TEXT="寒くない？" P4: ACTION/PROPS="Wrapping a scarf around" | TEXT="あたたかい" P5: ACTION/PROPS="Holding hands out playfully" | TEXT="ぎゅーっ" P6: ACTION/PROPS="Blushing deeply" | TEXT="恥ずかしいな" P7: ACTION/PROPS="Looking at phone happily" | TEXT="連絡きた" P8: ACTION/PROPS="Typing quickly" | TEXT="今行くね" P9: ACTION/PROPS="Running towards camera" | TEXT="お待たせ！"',
    'P1: ACTION/PROPS="Walking gracefully on a petal carpet" | TEXT="花の絨毯" P2: ACTION/PROPS="Stopping to pick up a perfect flower" | TEXT="これあげる" P3: ACTION/PROPS="Yawning sleepily" | TEXT="ふわぁ" P4: ACTION/PROPS="Rubbing eyes" | TEXT="眠い…" P5: ACTION/PROPS="Stretching elegantly" | TEXT="うーん" P6: ACTION/PROPS="Looking determined softly" | TEXT="よし、がんばる" P7: ACTION/PROPS="Bowing to say goodbye" | TEXT="失礼します" P8: ACTION/PROPS="Waving gently" | TEXT="さようなら" P9: ACTION/PROPS="Sleeping happily" | TEXT="おやすみなさい"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ風に舞う花びら', theme11_data)

# --- Theme 12: 和服美人ｘ春を感じるｘ雛祭りと桃の花 ---
theme12_data = [
    'P1: ACTION/PROPS="Setting up Hina dolls elegantly" | TEXT="おひなさま" P2: ACTION/PROPS="Looking proud of the display" | TEXT="綺麗に飾れました" P3: ACTION/PROPS="Holding a branch of peach blossoms" | TEXT="桃の花" P4: ACTION/PROPS="Smiling warmly at the dolls" | TEXT="健やかに" P5: ACTION/PROPS="Offering hishi mochi (diamond rice cake)" | TEXT="ひし餅どうぞ" P6: ACTION/PROPS="Drinking shirozake (sweet white sake)" | TEXT="美味しい" P7: ACTION/PROPS="Tying hair up gracefully" | TEXT="準備完了" P8: ACTION/PROPS="Clapping hands softly in celebration" | TEXT="おめでとう" P9: ACTION/PROPS="Looking playfully at camera" | TEXT="うれしいひなまつり"',
    'P1: ACTION/PROPS="Eating hina arare (rice crackers) happily" | TEXT="ぽりぽり" P2: ACTION/PROPS="Offering arare" | TEXT="食べる？" P3: ACTION/PROPS="Looking deeply satisfied" | TEXT="幸せ" P4: ACTION/PROPS="Tilting head gently" | TEXT="どうしたの？" P5: ACTION/PROPS="Covering mouth, laughing lightly" | TEXT="おほほ" P6: ACTION/PROPS="Looking shy, avoiding eye contact" | TEXT="いやーん" P7: ACTION/PROPS="Pouting cheeks playfully" | TEXT="ぷんぷん" P8: ACTION/PROPS="Winking sweetly" | TEXT="てへ" P9: ACTION/PROPS="Bowing graciously" | TEXT="ありがとうございます"',
    'P1: ACTION/PROPS="Bringing a bowl of clam soup" | TEXT="はまぐりのお吸い物" P2: ACTION/PROPS="Savouring the soup" | TEXT="いいお味" P3: ACTION/PROPS="Sighing contentedly" | TEXT="ほっ" P4: ACTION/PROPS="Looking worried holding cheeks" | TEXT="大丈夫？" P5: ACTION/PROPS="Patting back encouragingly" | TEXT="元気出して" P6: ACTION/PROPS="Showing an OK gesture" | TEXT="オッケー！" P7: ACTION/PROPS="Thumbs up with a bright smile" | TEXT="いいね" P8: ACTION/PROPS="Doing a small guts pose" | TEXT="やったー" P9: ACTION/PROPS="Putting hands together politely" | TEXT="お願いします"',
    'P1: ACTION/PROPS="Folding an origami doll" | TEXT="折り紙" P2: ACTION/PROPS="Showing the finished origami" | TEXT="できた！" P3: ACTION/PROPS="Looking apologetic" | TEXT="ごめんね" P4: ACTION/PROPS="Wiping a small tear" | TEXT="うう…" P5: ACTION/PROPS="Looking fiercely determined" | TEXT="負けない" P6: ACTION/PROPS="Pointing index finger playfully" | TEXT="これ大事" P7: ACTION/PROPS="Nodding enthusiastically" | TEXT="うんっ" P8: ACTION/PROPS="Shaking head gently" | TEXT="ちがうの" P9: ACTION/PROPS="Waving both hands" | TEXT="ちがうちがう"',
    'P1: ACTION/PROPS="Holding a small lantern toy (bonbori)" | TEXT="明かりをつけましょ" P2: ACTION/PROPS="Looking amazed at the light" | TEXT="きれい" P3: ACTION/PROPS="Peeking from behind the peach blossoms" | TEXT="ばぁ！" P4: ACTION/PROPS="Laughing heartily" | TEXT="あはは" P5: ACTION/PROPS="Looking sleepy, holding a pillow" | TEXT="ねむい" P6: ACTION/PROPS="Stretching nicely" | TEXT="うーんっ" P7: ACTION/PROPS="Waving goodbye warmly" | TEXT="また遊ぼうね" P8: ACTION/PROPS="Blowing a gentle kiss" | TEXT="ちゅ" P9: ACTION/PROPS="Sleeping happily beside the dolls" | TEXT="スヤァ"',
    'P1: ACTION/PROPS="Brushing off dust playfully" | TEXT="お掃除" P2: ACTION/PROPS="Looking back elegantly" | TEXT="呼びました？" P3: ACTION/PROPS="Offering a hand gently" | TEXT="一緒にどう？" P4: ACTION/PROPS="Putting hands on hips, scolding softly" | TEXT="こらこら" P5: ACTION/PROPS="Clasping hands in a wish" | TEXT="おねがい" P6: ACTION/PROPS="Looking up cheerfully" | TEXT="今日はいい日" P7: ACTION/PROPS="Sitting politely seiza" | TEXT="お待ちしてます" P8: ACTION/PROPS="Bowing deeply" | TEXT="よろしくお願いします" P9: ACTION/PROPS="Waving goodbye softly" | TEXT="ごきげんよう"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ雛祭りと桃の花', theme12_data)

# --- Theme 13: 和服美人ｘ春を感じるｘ春の味覚（苺や筍） ---
theme13_data = [
    'P1: ACTION/PROPS="Holding a shiny red strawberry" | TEXT="いちご" P2: ACTION/PROPS="Eating a strawberry playfully" | TEXT="あーん" P3: ACTION/PROPS="Smiling brightly with a juicy bite" | TEXT="あまい！" P4: ACTION/PROPS="Holding a basket of strawberries" | TEXT="たくさん採れた" P5: ACTION/PROPS="Offering a strawberry" | TEXT="ひとつどうぞ" P6: ACTION/PROPS="Looking at a harvested bamboo shoot (takenoko)" | TEXT="立派な筍" P7: ACTION/PROPS="Cooking takenoko rice" | TEXT="筍ごはん" P8: ACTION/PROPS="Serving a bowl of rice happily" | TEXT="できたてですよ" P9: ACTION/PROPS="Sighing contentedly after eating" | TEXT="春の味覚"',
    'P1: ACTION/PROPS="Clapping hands gently" | TEXT="いただきます" P2: ACTION/PROPS="Eating with chopsticks elegantly" | TEXT="美味しい" P3: ACTION/PROPS="Cheering with a small fist pump" | TEXT="最高！" P4: ACTION/PROPS="Looking proud in an apron over kimono" | TEXT="私が作りました" P5: ACTION/PROPS="Wiping sweat from brow" | TEXT="ふう" P6: ACTION/PROPS="Looking thoughtfully at menu" | TEXT="何にしようかな" P7: ACTION/PROPS="Nodding knowingly" | TEXT="それにしよう" P8: ACTION/PROPS="Holding stomach comfortably full" | TEXT="お腹いっぱい" P9: ACTION/PROPS="Bowing politely" | TEXT="ごちそうさまでした"',
    'P1: ACTION/PROPS="Looking surprised at sour strawberry" | TEXT="すっぱ！" P2: ACTION/PROPS="Puckering lips playfully" | TEXT="うー" P3: ACTION/PROPS="Laughing it off" | TEXT="あはは" P4: ACTION/PROPS="Looking sad, dropping a strawberry" | TEXT="ああっ" P5: ACTION/PROPS="Pouting slightly" | TEXT="もったいない" P6: ACTION/PROPS="Looking apologetic" | TEXT="ごめんなさい" P7: ACTION/PROPS="Offering an OK sign" | TEXT="大丈夫" P8: ACTION/PROPS="Giving a thumbs up" | TEXT="ばっちり！" P9: ACTION/PROPS="Winking happily" | TEXT="内緒ね"',
    'P1: ACTION/PROPS="Sneaking a bite of food" | TEXT="つまみ食い" P2: ACTION/PROPS="Looking caught, pointing fingers" | TEXT="うそ！？" P3: ACTION/PROPS="Turning away embarrassed" | TEXT="見ないで" P4: ACTION/PROPS="Tearing up a little" | TEXT="からい〜" P5: ACTION/PROPS="Drinking tea quickly" | TEXT="お茶！お茶！" P6: ACTION/PROPS="Sighing in relief" | TEXT="助かった" P7: ACTION/PROPS="Holding hand to chest" | TEXT="ドキドキ" P8: ACTION/PROPS="Pointing to empty plate" | TEXT="おかわり" P9: ACTION/PROPS="Smiling gently" | TEXT="もう一杯"',
    'P1: ACTION/PROPS="Waving broadly" | TEXT="こっちこっち" P2: ACTION/PROPS="Looking sleepy holding tea" | TEXT="ねむいな" P3: ACTION/PROPS="Yawning gracefully" | TEXT="ふわぁ" P4: ACTION/PROPS="Spreading arms stretching" | TEXT="うーんっ" P5: ACTION/PROPS="Looking confused" | TEXT="あれれ？" P6: ACTION/PROPS="Tilting head cute" | TEXT="はて？" P7: ACTION/PROPS="Bowing deeply" | TEXT="よろしくお願いします" P8: ACTION/PROPS="Patting head gently" | TEXT="よしよし" P9: ACTION/PROPS="Clasping hands in a simple wish" | TEXT="お願い"',
    'P1: ACTION/PROPS="Looking at the spring rain softly" | TEXT="恵みの雨" P2: ACTION/PROPS="Holding a single perfect strawberry" | TEXT="きれい" P3: ACTION/PROPS="Putting strawberry in a neat box" | TEXT="贈り物です" P4: ACTION/PROPS="Giving the present warmly" | TEXT="つまらないものですが" P5: ACTION/PROPS="Looking excited, blushing" | TEXT="開けてみて" P6: ACTION/PROPS="Jumping lightly in joy" | TEXT="わーい" P7: ACTION/PROPS="Waving goodbye cheerfully" | TEXT="また明日" P8: ACTION/PROPS="Blowing a kiss" | TEXT="ちゅっ" P9: ACTION/PROPS="Sleeping happily at the kotatsu" | TEXT="すやすや"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ春の味覚（苺や筍）', theme13_data)

# --- Theme 14: 和服美人ｘ春を感じるｘ季節の挨拶と丁寧な言葉 ---
theme14_data = [
    'P1: ACTION/PROPS="Bowing beautifully and deeply" | TEXT="ごきげんよう" P2: ACTION/PROPS="Looking up with a gentle smile" | TEXT="春めいてまいりました" P3: ACTION/PROPS="Putting hands neatly on lap" | TEXT="お変わりありませんか" P4: ACTION/PROPS="Offering a gentle nod" | TEXT="いかがお過ごしですか" P5: ACTION/PROPS="Looking at flying cherry petals warmly" | TEXT="暖かくなりましたね" P6: ACTION/PROPS="Covering mouth playfully with a small laugh" | TEXT="おほほ" P7: ACTION/PROPS="Holding hands to chest in gratitude" | TEXT="ありがとうございます" P8: ACTION/PROPS="Bowing slightly" | TEXT="お世話になっております" P9: ACTION/PROPS="Looking warmly into eyes" | TEXT="お会いできて嬉しいです"',
    'P1: ACTION/PROPS="Looking apologetic, hands together" | TEXT="申し訳ございません" P2: ACTION/PROPS="Looking sincerely sorry, bowing" | TEXT="お詫び申し上げます" P3: ACTION/PROPS="Looking slightly concerned" | TEXT="お体ご自愛ください" P4: ACTION/PROPS="Offering a warm cup of tea" | TEXT="一服いかがですか" P5: ACTION/PROPS="Sighing softly in relief" | TEXT="安心いたしました" P6: ACTION/PROPS="Cheering gently with a small fist" | TEXT="陰ながら応援しております" P7: ACTION/PROPS="Nodding firmly" | TEXT="承知いたしました" P8: ACTION/PROPS="Showing an elegant okay symbol" | TEXT="かしこまりました" P9: ACTION/PROPS="Bowing cleanly" | TEXT="お疲れ様でございます"',
    'P1: ACTION/PROPS="Smiling purely with hands together" | TEXT="おめでとうございます" P2: ACTION/PROPS="Clapping hands softly" | TEXT="お見事でした" P3: ACTION/PROPS="Looking proud and happy for someone" | TEXT="素晴らしいですね" P4: ACTION/PROPS="Looking shy, avoiding eyes slightly" | TEXT="恐縮です" P5: ACTION/PROPS="Shaking head left and right gracefully" | TEXT="とんでもございません" P6: ACTION/PROPS="Looking humble" | TEXT="滅相もございません" P7: ACTION/PROPS="Pointing to a gift neatly wrapped" | TEXT="心ばかりの品です" P8: ACTION/PROPS="Bowing with a wrapped gift" | TEXT="お納めください" P9: ACTION/PROPS="Smiling mysteriously" | TEXT="ご想像にお任せします"',
    'P1: ACTION/PROPS="Tilting head slightly confused" | TEXT="左様でございますか" P2: ACTION/PROPS="Pondering gracefully" | TEXT="いかがいたしましょう" P3: ACTION/PROPS="Looking surprised elegantly" | TEXT="まぁ" P4: ACTION/PROPS="Holding a hand over mouth in subtle shock" | TEXT="存じませんでした" P5: ACTION/PROPS="Tearing up a little" | TEXT="胸がいっぱいです" P6: ACTION/PROPS="Wiping tear politely with a handkerchief" | TEXT="お恥ずかしい" P7: ACTION/PROPS="Smiling happily" | TEXT="おぼしめし感謝します" P8: ACTION/PROPS="Showing empty hands" | TEXT="手ぶらで失礼します" P9: ACTION/PROPS="Offering a supportive touch on shoulder" | TEXT="お気になさらず"',
    'P1: ACTION/PROPS="Looking sleepy gracefully" | TEXT="夜分遅くに失礼します" P2: ACTION/PROPS="Yawning behind a beautiful fan" | TEXT="ふわぁ" P3: ACTION/PROPS="Rubbing eyes gently" | TEXT="おやすみなさいませ" P4: ACTION/PROPS="Looking up refreshed" | TEXT="おはようございます" P5: ACTION/PROPS="Taking a deep breath" | TEXT="よき朝ですね" P6: ACTION/PROPS="Stretching delicately" | TEXT="さぁ、参りましょう" P7: ACTION/PROPS="Waving gently to say goodbye" | TEXT="またお目にかかりましょう" P8: ACTION/PROPS="Looking back affectionately" | TEXT="お気をつけて" P9: ACTION/PROPS="Bowing slowly and deeply" | TEXT="ごめんくださいませ"',
    'P1: ACTION/PROPS="Walking gracefully" | TEXT="お邪魔いたします" P2: ACTION/PROPS="Sitting politely seiza" | TEXT="おじゃまします" P3: ACTION/PROPS="Looking lonely" | TEXT="名残惜しいです" P4: ACTION/PROPS="Panting slightly" | TEXT="お急ぎでしょうか" P5: ACTION/PROPS="Running elegantly" | TEXT="ただいま参ります" P6: ACTION/PROPS="Catching breath" | TEXT="お待たせいたしました" P7: ACTION/PROPS="Holding chest to calm down" | TEXT="失礼いたしました" P8: ACTION/PROPS="Looking out to the raining sky" | TEXT="お足元の悪い中" P9: ACTION/PROPS="Smiling softly in quiet reflection" | TEXT="では、また"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ季節の挨拶と丁寧な言葉', theme14_data)

# --- Theme 15: 和服美人ｘ春を感じるｘ卒業と新しい門出 ---
theme15_data = [
    'P1: ACTION/PROPS="Wearing a hakama and smiling brightly" | TEXT="卒業しました" P2: ACTION/PROPS="Holding a graduation diploma tube" | TEXT="ありがとうございます" P3: ACTION/PROPS="Throwing a small flower petal celebration" | TEXT="おめでとう！" P4: ACTION/PROPS="Crying softly out of joy" | TEXT="胸がいっぱいです" P5: ACTION/PROPS="Wiping tears with a beautiful handkerchief" | TEXT="泣かないって決めたのに" P6: ACTION/PROPS="Holding hands with a friend" | TEXT="ずっと友だち" P7: ACTION/PROPS="Looking straight ahead determined" | TEXT="がんばります" P8: ACTION/PROPS="Waving with both hands" | TEXT="また会おうね！" P9: ACTION/PROPS="Smiling purely towards the future" | TEXT="いってきます"',
    'P1: ACTION/PROPS="Holding a beautiful bouquet of flowers" | TEXT="花束プレゼント" P2: ACTION/PROPS="Looking touched by the flowers" | TEXT="とても綺麗" P3: ACTION/PROPS="Clapping hands loudly" | TEXT="パチパチパチ" P4: ACTION/PROPS="Pointing forward gracefully" | TEXT="前へ進もう" P5: ACTION/PROPS="Nodding enthusiastically" | TEXT="うんっ" P6: ACTION/PROPS="Looking surprised" | TEXT="ほんとに？" P7: ACTION/PROPS="Giving a high five playfully" | TEXT="イェイ" P8: ACTION/PROPS="Showing a peace sign" | TEXT="ピース" P9: ACTION/PROPS="Looking a bit embarrassed" | TEXT="恥ずかしいなぁ"',
    'P1: ACTION/PROPS="Sighing at parting" | TEXT="さみしくなるね" P2: ACTION/PROPS="Looking down sadly" | TEXT="うう…" P3: ACTION/PROPS="Patting on the shoulder reassuringly" | TEXT="大丈夫" P4: ACTION/PROPS="Giving a thumbs up" | TEXT="絶対やれるよ" P5: ACTION/PROPS="Showing an OK sign" | TEXT="オッケー" P6: ACTION/PROPS="Doing a fighting pose gently" | TEXT="ファイト！" P7: ACTION/PROPS="Bowing deeply" | TEXT="お世話になりました" P8: ACTION/PROPS="Smiling apologetically" | TEXT="迷惑かけてごめんね" P9: ACTION/PROPS="Looking up gratefully" | TEXT="感謝しかないです"',
    'P1: ACTION/PROPS="Running gracefully holding hakama" | TEXT="急ごう" P2: ACTION/PROPS="Looking out of breath" | TEXT="間に合った！" P3: ACTION/PROPS="Pouting slightly" | TEXT="遅いよー" P4: ACTION/PROPS="Laughing playfully" | TEXT="あははは" P5: ACTION/PROPS="Thinking carefully with finger on chin" | TEXT="これからどうしようか" P6: ACTION/PROPS="Eyes sparkling with ideas" | TEXT="わくわくする" P7: ACTION/PROPS="Looking confused" | TEXT="難しいな" P8: ACTION/PROPS="Sticking tongue out playfully" | TEXT="てへ" P9: ACTION/PROPS="Covering mouth with sleeve" | TEXT="内緒"',
    'P1: ACTION/PROPS="Writing in a yearbook/message board" | TEXT="寄せ書きだよ" P2: ACTION/PROPS="Giving the board to someone" | TEXT="書いてっ" P3: ACTION/PROPS="Reading a message affectionately" | TEXT="一生の宝物" P4: ACTION/PROPS="Taking a selfie" | TEXT="最後に一枚！" P5: ACTION/PROPS="Looking sleepy from emotions" | TEXT="疲れちゃった" P6: ACTION/PROPS="Yawning gracefully" | TEXT="ふわぁ" P7: ACTION/PROPS="Stretching nicely" | TEXT="よし！" P8: ACTION/PROPS="Sleeping happily leaning on bag" | TEXT="すやすや" P9: ACTION/PROPS="Waking up smiling" | TEXT="あっ！"',
    'P1: ACTION/PROPS="Standing under a blooming cherry tree" | TEXT="春だね" P2: ACTION/PROPS="Looking back affectionately" | TEXT="忘れないでね" P3: ACTION/PROPS="Holding onto a sleeve playfully" | TEXT="行かないで" P4: ACTION/PROPS="Letting go with a smile" | TEXT="冗談だよ" P5: ACTION/PROPS="Blowing a gentle kiss" | TEXT="ちゅっ" P6: ACTION/PROPS="Wiping forehead nervously" | TEXT="どきどき" P7: ACTION/PROPS="Taking a deep breath" | TEXT="深呼吸" P8: ACTION/PROPS="Opening the door cleanly" | TEXT="新しい扉" P9: ACTION/PROPS="Waving goodbye warmly until out of sight" | TEXT="バイバイ"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ卒業と新しい門出', theme15_data)

# --- Theme 16: 和服美人ｘ春を感じるｘ柳の芽吹きと水辺の散歩 ---
theme16_data = [
    'P1: ACTION/PROPS="Walking gracefully near a willow tree" | TEXT="柳が青々として" P2: ACTION/PROPS="Looking at the river gently" | TEXT="水面がキラキラ" P3: ACTION/PROPS="Holding a wagasa (traditional umbrella) lightly" | TEXT="お散歩日和" P4: ACTION/PROPS="Smiling softly at a passing boat" | TEXT="風情がありますね" P5: ACTION/PROPS="Pointing to a small fish in the water" | TEXT="お魚いた！" P6: ACTION/PROPS="Standing gracefully on a stone bridge" | TEXT="ここで一枚" P7: ACTION/PROPS="Taking a photo on the bridge" | TEXT="はいチーズ" P8: ACTION/PROPS="Looking satisfied with the photo" | TEXT="よく撮れた" P9: ACTION/PROPS="Waving warmly" | TEXT="こっちにおいで"',
    'P1: ACTION/PROPS="Stopping to tie kimono footwear (geta)" | TEXT="鼻緒が…" P2: ACTION/PROPS="Looking apologetic" | TEXT="待たせてごめんね" P3: ACTION/PROPS="Holding out a hand for balance" | TEXT="つかまらせて" P4: ACTION/PROPS="Smiling purely" | TEXT="ありがとう" P5: ACTION/PROPS="Looking up at the clear sky" | TEXT="雲一つない" P6: ACTION/PROPS="Taking a deep breath of fresh air" | TEXT="すぅーっ" P7: ACTION/PROPS="Nodding enthusiastically" | TEXT="いい気持ち" P8: ACTION/PROPS="Patting stomach gently" | TEXT="お腹すいた" P9: ACTION/PROPS="Pointing towards a teahouse" | TEXT="あっちに行こう"',
    'P1: ACTION/PROPS="Looking surprised at a sudden gust of wind" | TEXT="おっと" P2: ACTION/PROPS="Holding down kimono hem/sleeves" | TEXT="風が強いね" P3: ACTION/PROPS="Laughing it off" | TEXT="ふふっ" P4: ACTION/PROPS="Looking slightly confused, losing way" | TEXT="ここどこ？" P5: ACTION/PROPS="Looking at a map on phone" | TEXT="調べてみる" P6: ACTION/PROPS="Giving a thumbs up" | TEXT="わかった！" P7: ACTION/PROPS="Walking briskly with confidence" | TEXT="ついてきて" P8: ACTION/PROPS="Turning back with a wink" | TEXT="迷子にならないでね" P9: ACTION/PROPS="Showing an OK sign" | TEXT="任せて"',
    'P1: ACTION/PROPS="Sighing softly looking at the water" | TEXT="落ち着く" P2: ACTION/PROPS="Looking a bit melancholy" | TEXT="色々あるよね" P3: ACTION/PROPS="Pouting slightly" | TEXT="むー" P4: ACTION/PROPS="Shaking head left and right" | TEXT="忘れよう" P5: ACTION/PROPS="Slapping cheeks lightly to cheer up" | TEXT="よしっ" P6: ACTION/PROPS="Smiling brightly" | TEXT="元気出た！" P7: ACTION/PROPS="Offering a gentle encouraging smile" | TEXT="一緒にがんばろ" P8: ACTION/PROPS="Clapping hands once" | TEXT="さぁ！" P9: ACTION/PROPS="Waving happily" | TEXT="行こう！"',
    'P1: ACTION/PROPS="Looking sleepy sitting on a bench" | TEXT="歩き疲れた" P2: ACTION/PROPS="Yawning gracefully" | TEXT="ふわぁ" P3: ACTION/PROPS="Stretching shoulders softly" | TEXT="うーん" P4: ACTION/PROPS="Looking apologetic" | TEXT="少し休んでいい？" P5: ACTION/PROPS="Sleeping happily on partner\'s shoulder" | TEXT="すやすや" P6: ACTION/PROPS="Waking up blushing" | TEXT="ごめん、寝てた" P7: ACTION/PROPS="Rubbing eyes" | TEXT="ねむねむ" P8: ACTION/PROPS="Sticking tongue out playfully" | TEXT="てへへ" P9: ACTION/PROPS="Bowing gratefully" | TEXT="ありがとう"',
    'P1: ACTION/PROPS="Walking hand in hand" | TEXT="楽しいね" P2: ACTION/PROPS="Looking back warmly" | TEXT="ずっと一緒" P3: ACTION/PROPS="Smiling affectionately" | TEXT="好き" P4: ACTION/PROPS="Blowing a gentle kiss" | TEXT="ちゅっ" P5: ACTION/PROPS="Blushing furiously and hiding face" | TEXT="きゃー" P6: ACTION/PROPS="Peeking through fingers" | TEXT="内緒だよ" P7: ACTION/PROPS="Bowing deeply as parting" | TEXT="今日はありがとう" P8: ACTION/PROPS="Waving goodbye until out of sight" | TEXT="ばいばーい" P9: ACTION/PROPS="Looking extremely happy" | TEXT="最高の時間"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ柳の芽吹きと水辺の散歩', theme16_data)

# --- Theme 17: 和服美人ｘ春を感じるｘ読書と春の日差し ---
theme17_data = [
    'P1: ACTION/PROPS="Sitting by window with a book" | TEXT="読書の時間" P2: ACTION/PROPS="Turning page gently" | TEXT="ふむふむ" P3: ACTION/PROPS="Looking amazed by the story" | TEXT="えっ！" P4: ACTION/PROPS="Crying softly at a sad scene" | TEXT="泣ける…" P5: ACTION/PROPS="Wiping tears with handkerchief" | TEXT="ぐすっ" P6: ACTION/PROPS="Holding book to chest warmly" | TEXT="いいお話" P7: ACTION/PROPS="Closing book with satisfaction" | TEXT="読み終わった" P8: ACTION/PROPS="Looking up at the sun smiling" | TEXT="ポカポカ" P9: ACTION/PROPS="Stretching happily" | TEXT="清々しい"',
    'P1: ACTION/PROPS="Pondering deeply with book" | TEXT="難しいなぁ" P2: ACTION/PROPS="Tilting head confused" | TEXT="どういうこと？" P3: ACTION/PROPS="Looking at dictionary/phone" | TEXT="調べてみる" P4: ACTION/PROPS="Nodding with understanding" | TEXT="なるほど！" P5: ACTION/PROPS="Giving a thumbs up" | TEXT="スッキリ" P6: ACTION/PROPS="Looking proud" | TEXT="賢くなった" P7: ACTION/PROPS="Offering a book playfully" | TEXT="貸してあげよっか" P8: ACTION/PROPS="Winking happily" | TEXT="おすすめだよ" P9: ACTION/PROPS="Clapping hands gently" | TEXT="素晴らしい"',
    'P1: ACTION/PROPS="Looking sleepy, words blurring" | TEXT="文字が…" P2: ACTION/PROPS="Yawning gracefully behind book" | TEXT="ふわぁ" P3: ACTION/PROPS="Rubbing tired eyes" | TEXT="しょぼしょぼ" P4: ACTION/PROPS="Laying head on open book" | TEXT="ちょっとだけ" P5: ACTION/PROPS="Sleeping peacefully" | TEXT="スヤァ…" P6: ACTION/PROPS="Waking up startled" | TEXT="はっ！" P7: ACTION/PROPS="Looking embarrassed" | TEXT="寝ちゃってた" P8: ACTION/PROPS="Laughing awkwardly" | TEXT="あはは…" P9: ACTION/PROPS="Sticking tongue out" | TEXT="てへぺろ"',
    'P1: ACTION/PROPS="Sipping tea while reading" | TEXT="至福の時" P2: ACTION/PROPS="Looking out to the garden" | TEXT="いい天気" P3: ACTION/PROPS="Stopping to watch a butterfly" | TEXT="蝶々だ" P4: ACTION/PROPS="Smiling softly at nature" | TEXT="春だなぁ" P5: ACTION/PROPS="Pouting slightly at an interruption" | TEXT="どうしたの？" P6: ACTION/PROPS="Putting a beautiful bookmark" | TEXT="しおり" P7: ACTION/PROPS="Closing book elegantly" | TEXT="後で読む" P8: ACTION/PROPS="Offering full attention" | TEXT="なぁに？" P9: ACTION/PROPS="Nodding encouragingly" | TEXT="うんうん"',
    'P1: ACTION/PROPS="Carrying a stack of books" | TEXT="たくさん借りた" P2: ACTION/PROPS="Walking slightly unsteadily" | TEXT="重いよー" P3: ACTION/PROPS="Looking relieved as someone helps" | TEXT="助かった" P4: ACTION/PROPS="Smiling purely and gratefully" | TEXT="ありがとう" P5: ACTION/PROPS="Bowing politely" | TEXT="感謝します" P6: ACTION/PROPS="Looking excited, pointing to a book" | TEXT="これ読みたいの" P7: ACTION/PROPS="Holding hands in joy" | TEXT="楽しみ！" P8: ACTION/PROPS="Showing an OK sign" | TEXT="ばっちり" P9: ACTION/PROPS="Waving happily" | TEXT="じゃあね"',
    'P1: ACTION/PROPS="Looking deeply moved" | TEXT="感銘を受けました" P2: ACTION/PROPS="Hand on chest sincerely" | TEXT="胸に響く" P3: ACTION/PROPS="Sighing deeply with emotion" | TEXT="はぁ…" P4: ACTION/PROPS="Looking determined" | TEXT="私も頑張らなきゃ" P5: ACTION/PROPS="Doing a small fist pump" | TEXT="やるぞ！" P6: ACTION/PROPS="Looking up confidently" | TEXT="一歩前へ" P7: ACTION/PROPS="Bowing deeply" | TEXT="ありがとうございました" P8: ACTION/PROPS="Smiling warmly at camera" | TEXT="良い一日を" P9: ACTION/PROPS="Waving goodbye gently" | TEXT="また明日ね"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ読書と春の日差し', theme17_data)

# --- Theme 18: 和服美人ｘ春を感じるｘ花言葉に込めた想い ---
theme18_data = [
    'P1: ACTION/PROPS="Holding a single tulip gently" | TEXT="思いやり" P2: ACTION/PROPS="Holding a pink rose gracefully" | TEXT="温かい心" P3: ACTION/PROPS="Holding sweet pea softy" | TEXT="優しい思い出" P4: ACTION/PROPS="Looking affectionately at cherry blossoms" | TEXT="精神の美" P5: ACTION/PROPS="Holding anemone with a slight sad smile" | TEXT="あなたを信じて待つ" P6: ACTION/PROPS="Smiling with a ranunculus" | TEXT="晴れやかな魅力" P7: ACTION/PROPS="Holding freesia warmly" | TEXT="純潔" P8: ACTION/PROPS="Touching mimosa playfully" | TEXT="友情" P9: ACTION/PROPS="Offering a small bouquet" | TEXT="あなたへ"',
    'P1: ACTION/PROPS="Blushing fiercely holding a red tulip" | TEXT="愛の告白" P2: ACTION/PROPS="Looking shy and looking down" | TEXT="恥ずかしい" P3: ACTION/PROPS="Hiding face behind the bouquet" | TEXT="見ないで…" P4: ACTION/PROPS="Peeking through flowers playfully" | TEXT="ちらっ" P5: ACTION/PROPS="Smiling brightly with relief" | TEXT="よかった" P6: ACTION/PROPS="Tearing up a little" | TEXT="うれしい" P7: ACTION/PROPS="Nodding enthusiastically" | TEXT="うんっ！" P8: ACTION/PROPS="Wiping a happy tear" | TEXT="幸せです" P9: ACTION/PROPS="Hugging bouquet gently" | TEXT="宝物にします"',
    'P1: ACTION/PROPS="Looking slightly melancholic with yellow tulip" | TEXT="望みのない恋" P2: ACTION/PROPS="Sighing softly" | TEXT="はぁ…" P3: ACTION/PROPS="Looking down sadly" | TEXT="仕方ないね" P4: ACTION/PROPS="Shaking head left and right" | TEXT="諦めよう" P5: ACTION/PROPS="Looking up bravely" | TEXT="前を向く" P6: ACTION/PROPS="Slapping cheeks lightly" | TEXT="元気出そっ" P7: ACTION/PROPS="Showing an OK sign" | TEXT="大丈夫！" P8: ACTION/PROPS="Smiling forcefully but warmly" | TEXT="私は平気" P9: ACTION/PROPS="Waving dismissively" | TEXT="気にしないで"',
    'P1: ACTION/PROPS="Looking confused by a mysterious flower" | TEXT="この花言葉は？" P2: ACTION/PROPS="Tilting head cute" | TEXT="なんだろう" P3: ACTION/PROPS="Looking it up in a book" | TEXT="辞書で引く" P4: ACTION/PROPS="Looking surprised at the meaning" | TEXT="えっ！そうだったの" P5: ACTION/PROPS="Laughing awkwardly" | TEXT="勘違いしてた" P6: ACTION/PROPS="Sticking tongue out" | TEXT="てへへ" P7: ACTION/PROPS="Pouting cheeks slightly" | TEXT="教えてよー" P8: ACTION/PROPS="Winking happily" | TEXT="まあいっか" P9: ACTION/PROPS="Offering a gentle smile" | TEXT="ありがとう"',
    'P1: ACTION/PROPS="Arranging flowers in a vase" | TEXT="生け花" P2: ACTION/PROPS="Looking serious and focused" | TEXT="真剣です" P3: ACTION/PROPS="Adjusting a stem softly" | TEXT="もうちょっとこっち" P4: ACTION/PROPS="Clapping hands quietly in satisfaction" | TEXT="できた！" P5: ACTION/PROPS="Looking proud of the arrangement" | TEXT="我ながら完璧" P6: ACTION/PROPS="Bowing slightly" | TEXT="いかがでしょう" P7: ACTION/PROPS="Smiling broadly" | TEXT="春の訪れ" P8: ACTION/PROPS="Looking sleepy, yawning" | TEXT="ふわぁ" P9: ACTION/PROPS="Stretching elegantly" | TEXT="疲れたぁ"',
    'P1: ACTION/PROPS="Walking gracefully holding a single flower" | TEXT="会いに行く" P2: ACTION/PROPS="Looking excited and nervous" | TEXT="どきどき" P3: ACTION/PROPS="Waving brightly from afar" | TEXT="おーい" P4: ACTION/PROPS="Running a few steps elegantly" | TEXT="お待たせ！" P5: ACTION/PROPS="Breathing heavily with a smile" | TEXT="急いじゃった" P6: ACTION/PROPS="Offering the flower hands straight out" | TEXT="これ！" P7: ACTION/PROPS="Looking up affectionately" | TEXT="いつもありがとう" P8: ACTION/PROPS="Bowing deeply" | TEXT="これからもよろしくね" P9: ACTION/PROPS="Smiling purely" | TEXT="大好き"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ花言葉に込めた想い', theme18_data)

# --- Theme 19: 和服美人ｘ春を感じるｘそよ風と揺れる袂 ---
theme19_data = [
    'P1: ACTION/PROPS="Standing as spring breeze flutters kimono sleeves" | TEXT="風が気持ちいい" P2: ACTION/PROPS="Closing eyes, feeling the breeze" | TEXT="そよ風" P3: ACTION/PROPS="Holding down gently fluttering sleeves" | TEXT="ひらひら" P4: ACTION/PROPS="Smiling softly looking into the wind" | TEXT="春の匂い" P5: ACTION/PROPS="Looking up as hair softly blows" | TEXT="爽やか" P6: ACTION/PROPS="Holding a wagasa against the gentle wind" | TEXT="いいお天気" P7: ACTION/PROPS="Looking back elegantly" | TEXT="行きましょうか" P8: ACTION/PROPS="Walking gracefully" | TEXT="足取りも軽く" P9: ACTION/PROPS="Waving warmly" | TEXT="こっちよ"',
    'P1: ACTION/PROPS="Surprised by a sudden stronger gust" | TEXT="わっ！" P2: ACTION/PROPS="Holding hair and kimono desperately" | TEXT="大変！" P3: ACTION/PROPS="Laughing helplessly as wind messes hair" | TEXT="あははは" P4: ACTION/PROPS="Looking embarrassed fixing hair" | TEXT="乱れちゃった" P5: ACTION/PROPS="Pouting slightly" | TEXT="風のいたずら" P6: ACTION/PROPS="Sighing softly" | TEXT="もうっ" P7: ACTION/PROPS="Giving a thumbs up" | TEXT="直った！" P8: ACTION/PROPS="Smiling playfully" | TEXT="大丈夫" P9: ACTION/PROPS="Winking happily" | TEXT="気にしない"',
    'P1: ACTION/PROPS="Shivering as the breeze is slightly cold" | TEXT="ちょっと寒いかも" P2: ACTION/PROPS="Rubbing shoulders gently" | TEXT="ぶるっ" P3: ACTION/PROPS="Sneezing delicately" | TEXT="くしゅんっ" P4: ACTION/PROPS="Looking apologetic" | TEXT="ごめんなさい" P5: ACTION/PROPS="Wrapping a beautiful shawl" | TEXT="これで平気" P6: ACTION/PROPS="Smiling in relief" | TEXT="あったかい" P7: ACTION/PROPS="Showing an OK sign" | TEXT="ご心配なく" P8: ACTION/PROPS="Nodding encouragingly" | TEXT="さぁ、続きを" P9: ACTION/PROPS="Clapping hands once" | TEXT="よしっ！"',
    'P1: ACTION/PROPS="Pondering looking at a wind chime" | TEXT="ちりんちりん" P2: ACTION/PROPS="Tilting head gracefully" | TEXT="いい音色" P3: ACTION/PROPS="Looking melancholic in the breeze" | TEXT="少し寂しい" P4: ACTION/PROPS="Sighing deeply" | TEXT="はぁ…" P5: ACTION/PROPS="Shaking head gently" | TEXT="なんてね" P6: ACTION/PROPS="Smiling forcefully" | TEXT="元気出さなきゃ" P7: ACTION/PROPS="Patting own cheeks completely gently" | TEXT="ぱんぱんっ" P8: ACTION/PROPS="A bright smile returning" | TEXT="よし！" P9: ACTION/PROPS="Pointing forward" | TEXT="あそこに行こう"',
    'P1: ACTION/PROPS="Sitting gracefully on a bench in the breeze" | TEXT="ひと休み" P2: ACTION/PROPS="Looking sleepy as the breeze continues" | TEXT="ぽかぽかする" P3: ACTION/PROPS="Yawning gracefully" | TEXT="ふわぁ" P4: ACTION/PROPS="Rubbing eyes" | TEXT="眠くなってきた" P5: ACTION/PROPS="Sleeping happily leaning slightly" | TEXT="ウトウト" P6: ACTION/PROPS="Waking up blushing" | TEXT="あっ！" P7: ACTION/PROPS="Hiding face with sleeve" | TEXT="恥ずかしい" P8: ACTION/PROPS="Looking extremely apologetic" | TEXT="寝てました" P9: ACTION/PROPS="Sticking tongue out playfully" | TEXT="てへぇ"',
    'P1: ACTION/PROPS="Holding hands in the breeze" | TEXT="手つなごっ" P2: ACTION/PROPS="Looking deeply into eyes" | TEXT="見惚れちゃった" P3: ACTION/PROPS="Turning away blushing" | TEXT="嘘です" P4: ACTION/PROPS="Laughing purely" | TEXT="うふふ" P5: ACTION/PROPS="Waving goodbye warmly" | TEXT="また明日ね" P6: ACTION/PROPS="Blowing a gentle kiss" | TEXT="ちゅっ" P7: ACTION/PROPS="Running away gracefully" | TEXT="きゃー" P8: ACTION/PROPS="Stopping to turn back and wave" | TEXT="バイバイ！" P9: ACTION/PROPS="Smiling completely happily" | TEXT="大好き"'
]
generate_theme_csv('和服美人ｘ春を感じるｘそよ風と揺れる袂', theme19_data)

# --- Theme 20: 和服美人ｘ春を感じるｘ現代のカフェと和装 ---
theme20_data = [
    'P1: ACTION/PROPS="Sitting elegantly in a modern cafe" | TEXT="素敵なカフェ" P2: ACTION/PROPS="Looking at menu excitedly" | TEXT="どれにしようかな" P3: ACTION/PROPS="Ordering with a smile" | TEXT="これお願いします" P4: ACTION/PROPS="Holding a latte art happily" | TEXT="可愛い！" P5: ACTION/PROPS="Taking a photo of the drink" | TEXT="写真撮ろっと" P6: ACTION/PROPS="Drinking delicately" | TEXT="美味しい" P7: ACTION/PROPS="Sighing contentedly" | TEXT="落ち着く" P8: ACTION/PROPS="Eating a slice of cake" | TEXT="甘くて幸せ" P9: ACTION/PROPS="Wiping lips with a napkin gracefully" | TEXT="ごちそうさま"',
    'P1: ACTION/PROPS="Looking surprised by huge pancake" | TEXT="おおっ！" P2: ACTION/PROPS="Eyes sparkling" | TEXT="美味しそう" P3: ACTION/PROPS="Offering a bite playfully" | TEXT="一口食べる？" P4: ACTION/PROPS="Pouting slightly when refused" | TEXT="むー" P5: ACTION/PROPS="Laughing playfully" | TEXT="全部食べちゃうよ" P6: ACTION/PROPS="Looking guilty full stomach" | TEXT="食べすぎた…" P7: ACTION/PROPS="Patting stomach" | TEXT="ぽんぽこりん" P8: ACTION/PROPS="Showing an OK sign" | TEXT="でも後悔なし！" P9: ACTION/PROPS="Giving a thumbs up" | TEXT="大満足"',
    'P1: ACTION/PROPS="Working gracefully on a laptop in cafe" | TEXT="作業中" P2: ACTION/PROPS="Looking tired, rubbing neck" | TEXT="疲れたな" P3: ACTION/PROPS="Stretching arms out" | TEXT="うーんっ" P4: ACTION/PROPS="Sipping coffee to wake up" | TEXT="シャキッと！" P5: ACTION/PROPS="Typing quickly" | TEXT="あと少し" P6: ACTION/PROPS="Looking proud of finished work" | TEXT="終わった！" P7: ACTION/PROPS="Clapping hands gently" | TEXT="お疲れ様" P8: ACTION/PROPS="Closing laptop neatly" | TEXT="帰ろう" P9: ACTION/PROPS="Waving politely" | TEXT="またね"',
    'P1: ACTION/PROPS="Looking around confused" | TEXT="ここはどこ？" P2: ACTION/PROPS="Checking map on phone" | TEXT="迷ったみたい" P3: ACTION/PROPS="Looking apologetic" | TEXT="ごめん、遅れそう" P4: ACTION/PROPS="Hands together in prayer" | TEXT="本当にごめん！" P5: ACTION/PROPS="Sighing softly" | TEXT="はぁ…" P6: ACTION/PROPS="Looking relieved seeing friend" | TEXT="あっ！いた！" P7: ACTION/PROPS="Running elegantly but quickly" | TEXT="お待たせー！" P8: ACTION/PROPS="Catching breath" | TEXT="ふーふー" P9: ACTION/PROPS="Smiling purely" | TEXT="会えてよかった"',
    'P1: ACTION/PROPS="Looking sadly at a rainy cafe window" | TEXT="雨ですね" P2: ACTION/PROPS="Resting chin on hand" | TEXT="退屈だなぁ" P3: ACTION/PROPS="Yawning gracefully" | TEXT="ふわぁ" P4: ACTION/PROPS="Looking sleepy" | TEXT="眠くなってきた" P5: ACTION/PROPS="Sleeping lightly on the table" | TEXT="うとうと…" P6: ACTION/PROPS="Waking up surprised" | TEXT="はっ！" P7: ACTION/PROPS="Wiping drool playfully" | TEXT="ヨダレ拭かなきゃ" P8: ACTION/PROPS="Laughing awkwardly" | TEXT="あはは…" P9: ACTION/PROPS="Sticking tongue out" | TEXT="てへぺろ"',
    'P1: ACTION/PROPS="Laughing heartily with a friend" | TEXT="あははは！" P2: ACTION/PROPS="Covering mouth gracefully while laughing" | TEXT="面白すぎる" P3: ACTION/PROPS="Nodding enthusiastically" | TEXT="わかるわかる！" P4: ACTION/PROPS="Clapping hands in agreement" | TEXT="それな！" P5: ACTION/PROPS="Looking warmly at friend" | TEXT="ずっと話していたい" P6: ACTION/PROPS="Looking sad at the time" | TEXT="もう帰る時間" P7: ACTION/PROPS="Pouting slightly" | TEXT="帰りたくないな" P8: ACTION/PROPS="Bowing to say goodbye" | TEXT="今日はありがとう" P9: ACTION/PROPS="Waving happily" | TEXT="またカフェ行こうね"'
]
generate_theme_csv('和服美人ｘ春を感じるｘ現代のカフェと和装', theme20_data)

# >>>END_OF_SCRIPT<<<
