import os
import csv

os.makedirs('outputs/prompts', exist_ok=True)

rows = [
    'P1: ACTION/PROPS=\"A beautiful woman in a kimono bowing politely softly\" | TEXT=\"おはよう\" P2: ACTION/PROPS=\"A beautiful woman in a kimono sleepy rubbing eyes\" | TEXT=\"ふぁあ\" P3: ACTION/PROPS=\"A beautiful woman in a kimono drinking hot tea from a cup\" | TEXT=\"ほっ\" P4: ACTION/PROPS=\"A beautiful woman in a kimono fixing her hairpin looking at mirror\" | TEXT=\"よしっ\" P5: ACTION/PROPS=\"A beautiful woman in a kimono turning back smiling\" | TEXT=\"いってきまーす\" P6: ACTION/PROPS=\"A beautiful woman in a kimono waving hand gently\" | TEXT=\"いってらっしゃい\" P7: ACTION/PROPS=\"A beautiful woman in a kimono tilting head question mark\" | TEXT=\"ん？\" P8: ACTION/PROPS=\"A beautiful woman in a kimono walking fast holding hem\" | TEXT=\"あわわわ\" P9: ACTION/PROPS=\"A beautiful woman in a kimono making a peace sign happily\" | TEXT=\"ばっちり\"',
    'P1: ACTION/PROPS=\"A beautiful woman in a kimono working on a laptop seriously\" | TEXT=\"作業中\" P2: ACTION/PROPS=\"A beautiful woman in a kimono holding a phone looking surprised\" | TEXT=\"えっ\" P3: ACTION/PROPS=\"A beautiful woman in a kimono nodding firmly with crossed arms\" | TEXT=\"なるほど\" P4: ACTION/PROPS=\"A beautiful woman in a kimono raising hand brightly\" | TEXT=\"はーい\" P5: ACTION/PROPS=\"A beautiful woman in a kimono bowing deeply in apology\" | TEXT=\"ごめんなさい\" P6: ACTION/PROPS=\"A beautiful woman in a kimono holding hands together pleading\" | TEXT=\"おねがい\" P7: ACTION/PROPS=\"A beautiful woman in a kimono clapping hands joyfully\" | TEXT=\"さすが\" P8: ACTION/PROPS=\"A beautiful woman in a kimono sweating nervously wiping forehead\" | TEXT=\"あせあせ\" P9: ACTION/PROPS=\"A beautiful woman in a kimono putting a hand on chest relieved\" | TEXT=\"よかった\"',
    'P1: ACTION/PROPS=\"A beautiful woman in a kimono holding a traditional umbrella walking\" | TEXT=\"おでかけ\" P2: ACTION/PROPS=\"A beautiful woman in a kimono looking excitedly at a cake\" | TEXT=\"わぁぁ\" P3: ACTION/PROPS=\"A beautiful woman in a kimono eating dango holding a skewer\" | TEXT=\"もぐもぐ\" P4: ACTION/PROPS=\"A beautiful woman in a kimono holding a shopping bag smiling\" | TEXT=\"かいました\" P5: ACTION/PROPS=\"A beautiful woman in a kimono looking at a map confused\" | TEXT=\"まよった\" P6: ACTION/PROPS=\"A beautiful woman in a kimono pointing finger like discovering something\" | TEXT=\"あった\" P7: ACTION/PROPS=\"A beautiful woman in a kimono walking tiredly looking exhausted\" | TEXT=\"つかれた\" P8: ACTION/PROPS=\"A beautiful woman in a kimono sitting on a bench resting\" | TEXT=\"きゅうけい\" P9: ACTION/PROPS=\"A beautiful woman in a kimono holding a smartphone taking photo\" | TEXT=\"パシャ\"',
    'P1: ACTION/PROPS=\"A beautiful woman in a kimono laughing elegantly covering mouth\" | TEXT=\"ふふふ\" P2: ACTION/PROPS=\"A beautiful woman in a kimono big smile jumping happily\" | TEXT=\"やったー\" P3: ACTION/PROPS=\"A beautiful woman in a kimono puffing cheeks angrily\" | TEXT=\"むっ\" P4: ACTION/PROPS=\"A beautiful woman in a kimono looking sad tearing up\" | TEXT=\"ぐすん\" P5: ACTION/PROPS=\"A beautiful woman in a kimono shocked pale face\" | TEXT=\"ガーン\" P6: ACTION/PROPS=\"A beautiful woman in a kimono eyes sparkling with excitement\" | TEXT=\"きゅん\" P7: ACTION/PROPS=\"A beautiful woman in a kimono sighing heavily looking down\" | TEXT=\"はぁ\" P8: ACTION/PROPS=\"A beautiful woman in a kimono blushing holding cheeks\" | TEXT=\"てれる\" P9: ACTION/PROPS=\"A beautiful woman in a kimono winking cutely pointing\" | TEXT=\"ないしょ\"',
    'P1: ACTION/PROPS=\"A beautiful woman in a kimono holding a sake cup smiling\" | TEXT=\"かんぱい\" P2: ACTION/PROPS=\"A beautiful woman in a kimono drinking beer happily\" | TEXT=\"ぷはー\" P3: ACTION/PROPS=\"A beautiful woman in a kimono slightly drunk red face laughing\" | TEXT=\"えへへ\" P4: ACTION/PROPS=\"A beautiful woman in a kimono resting head on table sleepily\" | TEXT=\"うとうと\" P5: ACTION/PROPS=\"A beautiful woman in a kimono looking at the moon elegantly\" | TEXT=\"きれーい\" P6: ACTION/PROPS=\"A beautiful woman in a kimono stretching shoulders relaxed\" | TEXT=\"のびー\" P7: ACTION/PROPS=\"A beautiful woman in a kimono lying on tatami rolling\" | TEXT=\"ごろごろ\" P8: ACTION/PROPS=\"A beautiful woman in a kimono waving hand lightly saying bye\" | TEXT=\"またね\" P9: ACTION/PROPS=\"A beautiful woman in a kimono sleeping peacefully in futon\" | TEXT=\"おやすみ\"',
    'P1: ACTION/PROPS=\"A beautiful woman in a kimono giving an OK sign with fingers\" | TEXT=\"りょうかい\" P2: ACTION/PROPS=\"A beautiful woman in a kimono crossing arms making an X sign\" | TEXT=\"だめ\" P3: ACTION/PROPS=\"A beautiful woman in a kimono thumbs up smiling confidently\" | TEXT=\"いいね\" P4: ACTION/PROPS=\"A beautiful woman in a kimono holding a fan covering face coyly\" | TEXT=\"うふふ\" P5: ACTION/PROPS=\"A beautiful woman in a kimono peeking from behind a folding screen\" | TEXT=\"じーっ\" P6: ACTION/PROPS=\"A beautiful woman in a kimono pointing a finger directly\" | TEXT=\"それな\" P7: ACTION/PROPS=\"A beautiful woman in a kimono clapping hands lightly\" | TEXT=\"パチパチ\" P8: ACTION/PROPS=\"A beautiful woman in a kimono bowing slightly formal\" | TEXT=\"かしこまりました\" P9: ACTION/PROPS=\"A beautiful woman in a kimono smiling brightly waving both hands\" | TEXT=\"ありがとう\"'
]

file_path = 'outputs/prompts/和服美人の日常_prompts.csv'

with open(file_path, 'w', encoding='utf-8-sig', newline='') as f:
    writer = csv.writer(f)
    for row in rows:
        writer.writerow([row])
