import os
import csv

def save_csv(theme_name, data_rows):
    os.makedirs('outputs/prompts', exist_ok=True)
    filename = f'outputs/prompts/{theme_name}_prompts.csv'
    with open(filename, 'w', encoding='utf-8-sig', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['prompt'])
        for row in data_rows:
            writer.writerow([row])
    print(f"Saved: {filename}")

def generate_all():
    # 1. 必死すぎる擬態
    theme1 = [
        # Set 1-6 each 9 prompts... (Truncated for readability but fully implemented in actual logic)
        'P1: ACTION/PROPS="man in full-body suit pretending to be a houseplant" | TEXT="どこにいるでしょう" P2: ACTION/PROPS="man in suit flattened against a wall" | TEXT="壁です" P3: ACTION/PROPS="man in suit posing as a wooden chair" | TEXT="どうぞお座りください" P4: ACTION/PROPS="man in suit curled up like a stone" | TEXT="ただの石です" P5: ACTION/PROPS="man in suit hiding behind a slim curtain" | TEXT="見えてないよね" P6: ACTION/PROPS="man in suit pretending to be a banana" | TEXT="バナナのふり" P7: ACTION/PROPS="man in suit trying to look like a coat rack" | TEXT="服かけられます" P8: ACTION/PROPS="man in suit blending into shadows" | TEXT="闇に紛れる" P9: ACTION/PROPS="man in suit acting as a pillow on a sofa" | TEXT="ふかふかですよ"',
        'P1: ACTION/PROPS="man in suit sticking to the ceiling" | TEXT="上を見て" P2: ACTION/PROPS="man in suit disguised as a trash can" | TEXT="ゴミ箱です" P3: ACTION/PROPS="man in suit pretending to be a carpet" | TEXT="踏まないで" P4: ACTION/PROPS="man in suit acting like a bookshelf" | TEXT="知識の宝庫" P5: ACTION/PROPS="man in suit mimicking a desk lamp" | TEXT="明るく照らします" P6: ACTION/PROPS="man in suit posing as a toaster" | TEXT="こんがり焼けます" P7: ACTION/PROPS="man in suit disguised as a pile of laundry" | TEXT="洗濯して" P8: ACTION/PROPS="man in suit pretending to be a window frame" | TEXT="景色はどう？" P9: ACTION/PROPS="man in suit acting like a robot vacuum" | TEXT="お掃除中"',
        'P1: ACTION/PROPS="man in suit blending into a brick wall pattern" | TEXT="同化中" P2: ACTION/PROPS="man in suit posing as a decorative vase" | TEXT="美を愛でて" P3: ACTION/PROPS="man in suit mimicking a wall clock" | TEXT="今は何時？" P4: ACTION/PROPS="man in suit disguised as a refrigerator" | TEXT="キンキンに冷えてます" P5: ACTION/PROPS="man in suit acting as a door mat" | TEXT="いらっしゃい" P6: ACTION/PROPS="man in suit pretending to be a bicycle" | TEXT="移動しましょう" P7: ACTION/PROPS="man in suit mimicking a large TV screen" | TEXT="番組放送中" P8: ACTION/PROPS="man in suit disguised as a bookshelf corner" | TEXT="密かに存在" P9: ACTION/PROPS="man in suit acting like a ceiling fan" | TEXT="回ります"',
        'P1: ACTION/PROPS="man in suit disguised as a giant bag of chips" | TEXT="美味しそう？" P2: ACTION/PROPS="man in suit pretending to be a shoe rack" | TEXT="整理整頓" P3: ACTION/PROPS="man in suit acting as a door handle" | TEXT="回して" P4: ACTION/PROPS="man in suit mimicking a fireplace" | TEXT="あったかいね" P5: ACTION/PROPS="man in suit disguised as a bathroom tile" | TEXT="清潔感" P6: ACTION/PROPS="man in suit pretending to be a umbrella stand" | TEXT="雨ですね" P7: ACTION/PROPS="man in suit acting as a wall-mounted mirror" | TEXT="鏡よ鏡" P8: ACTION/PROPS="man in suit mimicking a piano" | TEXT="奏でてみて" P9: ACTION/PROPS="man in suit disguised as a giant cactus" | TEXT="刺さるよ"',
        'P1: ACTION/PROPS="man in suit blending into a polka dot wall" | TEXT="目が回る" P2: ACTION/PROPS="man in suit pretending to be a laptop" | TEXT="作業中" P3: ACTION/PROPS="man in suit acting as a staircase step" | TEXT="一段ずつどうぞ" P4: ACTION/PROPS="man in suit mimicking a post box" | TEXT="手紙待ってます" P5: ACTION/PROPS="man in suit disguised as a garden gnome" | TEXT="庭の守り神" P6: ACTION/PROPS="man in suit pretending to be a swing" | TEXT="揺られてみて" P7: ACTION/PROPS="man in suit acting as a teapot" | TEXT="注ぎます" P8: ACTION/PROPS="man in suit mimicking a telescope" | TEXT="星が綺麗" P9: ACTION/PROPS="man in suit disguised as a fire extinguisher" | TEXT="非常事態！"',
        'P1: ACTION/PROPS="man in suit blending into a zebra crossing" | TEXT="渡りましょう" P2: ACTION/PROPS="man in suit pretending to be a sandbag" | TEXT="受け止めます" P3: ACTION/PROPS="man in suit acting as a scarecrow" | TEXT="鳥除け" P4: ACTION/PROPS="man in suit mimicking a traffic light" | TEXT="止まれ！" P5: ACTION/PROPS="man in suit disguised as a vending machine" | TEXT="どれにします？" P6: ACTION/PROPS="man in suit pretending to be a bench" | TEXT="休んでいって" P7: ACTION/PROPS="man in suit acting as a statue in a park" | TEXT="芸術です" P8: ACTION/PROPS="man in suit mimicking a street lamp" | TEXT="夜道のお供" P9: ACTION/PROPS="man in suit disguised as a manhole cover" | TEXT="足元に注意"'
    ]
    save_csv('必死すぎる擬態', theme1)

    # 2. 無駄にキレのある丁寧な暮らし
    theme2 = [
        'P1: ACTION/PROPS="man in suit elegantly brewing drip coffee" | TEXT="至福の一杯" P2: ACTION/PROPS="man in suit vacuuming with a magnificent pose" | TEXT="塵一つ残さない" P3: ACTION/PROPS="man in suit gracefully arranging flowers" | TEXT="心が整う" P4: ACTION/PROPS="man in suit wiping a window with high speed" | TEXT="ピカピカですよ" P5: ACTION/PROPS="man in suit reading a book with a dramatic posture" | TEXT="読書の秋" P6: ACTION/PROPS="man in suit ironing a shirt with focus" | TEXT="シワは許さない" P7: ACTION/PROPS="man in suit seasoning food with a flourish" | TEXT="隠し味は愛情" P8: ACTION/PROPS="man in suit folding laundry with precision" | TEXT="几帳面ですから" P9: ACTION/PROPS="man in suit meditating in a garden" | TEXT="整いました"',
        'P1: ACTION/PROPS="man in suit elegantly baking bread" | TEXT="香ばしい朝" P2: ACTION/PROPS="man in suit polishing shoes with intensity" | TEXT="鏡面仕上げ" P3: ACTION/PROPS="man in suit watering plants dramatically" | TEXT="潤いをどうぞ" P4: ACTION/PROPS="man in suit calligraphy with a full-body movement" | TEXT="渾身の一筆" P5: ACTION/PROPS="man in suit organizing a drawer with Zen focus" | TEXT="無の境地" P6: ACTION/PROPS="man in suit setting a table like a five-star waiter" | TEXT="準備完了" P7: ACTION/PROPS="man in suit choosing an outfit with extreme seriousness" | TEXT="今日の勝負服" P8: ACTION/PROPS="man in suit sweeping the porch with a dance-like rhythm" | TEXT="清々しいね" P9: ACTION/PROPS="man in suit enjoying a tea ceremony pose" | TEXT="結構なお点前で"',
        'P1: ACTION/PROPS="man in suit elegantly dusting a shelf" | TEXT="埃を許しません" P2: ACTION/PROPS="man in suit preparing a bento box with artistic flair" | TEXT="彩り豊かに" P3: ACTION/PROPS="man in suit smelling a candle with an ecstatic face" | TEXT="香りに癒されて" P4: ACTION/PROPS="man in suit writing a journal with a feather pen" | TEXT="今日に感謝" P5: ACTION/PROPS="man in suit hanging laundry with sharp coordination" | TEXT="お日様の香り" P6: ACTION/PROPS="man in suit washing dishes with sparkling precision" | TEXT="水も滴るおじさん" P7: ACTION/PROPS="man in suit stretching in the morning light" | TEXT="目覚めスッキリ" P8: ACTION/PROPS="man in suit choosing coffee beans with a loupe" | TEXT="究極の選定" P9: ACTION/PROPS="man in suit enjoying a bubble bath elegantly" | TEXT="優雅なひととき"',
        'P1: ACTION/PROPS="man in suit kneading dough with passion" | TEXT="粘り強く" P2: ACTION/PROPS="man in suit sharpening a kitchen knife intensely" | TEXT="キレキレです" P3: ACTION/PROPS="man in suit organizing books by color" | TEXT="視覚的調和" P4: ACTION/PROPS="man in suit tying shoe laces with a heroic pose" | TEXT="一歩踏み出す" P5: ACTION/PROPS="man in suit checking the expiration dates with a magnifying glass" | TEXT="鮮度第一" P6: ACTION/PROPS="man in suit making a bed with military precision" | TEXT="快眠を約束" P7: ACTION/PROPS="man in suit trimming a bonsai tree" | TEXT="無駄を削ぎ落とす" P8: ACTION/PROPS="man in suit making high-quality ice cubes" | TEXT="氷の世界" P9: ACTION/PROPS="man in suit listening to classical music with closed eyes" | TEXT="至高の旋律"',
        'P1: ACTION/PROPS="man in suit using a silk cloth to polish a smartphone" | TEXT="指紋ゼロ" P2: ACTION/PROPS="man in suit decanting wine with a professional look" | TEXT="熟成の極み" P3: ACTION/PROPS="man in suit sorting trash with deep concentration" | TEXT="地球に優しく" P4: ACTION/PROPS="man in suit folding an origami crane perfectly" | TEXT="祈りを込めて" P5: ACTION/PROPS="man in suit polishing a door knob until it glows" | TEXT="福を呼び込む" P6: ACTION/PROPS="man in suit making fresh pasta from scratch" | TEXT="手打ちの味" P7: ACTION/PROPS="man in suit using a lint roller on the suit" | TEXT="身だしなみチェック" P8: ACTION/PROPS="man in suit drinking mineral water strictly" | TEXT="身体の浄化" P9: ACTION/PROPS="man in suit looking at a sunrise with hands behind back" | TEXT="良き日の始まり"',
        'P1: ACTION/PROPS="man in suit elegantly peeling an apple in one go" | TEXT="職人技" P2: ACTION/PROPS="man in suit folding a silk handkerchief" | TEXT="紳士の嗜み" P3: ACTION/PROPS="man in suit organizing digital folders" | TEXT="整理の極み" P4: ACTION/PROPS="man in suit cleaning a pair of glasses with focus" | TEXT="視界良好" P5: ACTION/PROPS="man in suit arranging shoes in the entrance" | TEXT="お帰りを待つ心" P6: ACTION/PROPS="man in suit checking the weather forecast seriously" | TEXT="備えあれば憂いなし" P7: ACTION/PROPS="man in suit using a fountain pen to write a card" | TEXT="心を込めて" P8: ACTION/PROPS="man in suit making a perfectly round rice ball" | TEXT="おむすびの魂" P9: ACTION/PROPS="man in suit enjoying the scent of fresh rain" | TEXT="自然の恵み"'
    ]
    save_csv('無駄にキレのある丁寧な暮らし', theme2)

    # 3. 物理法則を無視した人間離れな土下座
    theme3 = [
        'P1: ACTION/PROPS="man in suit bent backwards in impossible dogeza" | TEXT="逆土下座" P2: ACTION/PROPS="man in suit floating in mid-air in dogeza" | TEXT="空中土下座" P3: ACTION/PROPS="man in suit stretched out intensely long" | TEXT="土下座スライディング" P4: ACTION/PROPS="man in suit rotated 360 degrees in dogeza" | TEXT="全方位謝罪" P5: ACTION/PROPS="man in suit head buried deep into floor" | TEXT="穴があったら入りたい" P6: ACTION/PROPS="man in suit standing on hands in dogeza" | TEXT="逆立ち土下座" P7: ACTION/PROPS="man in suit folded into a tiny cube" | TEXT="身を縮めて謝ります" P8: ACTION/PROPS="man in suit limbs tangled in apology" | TEXT="平謝り" P9: ACTION/PROPS="man in suit splitting into ghostly images in dogeza" | TEXT="分身土下座"',
        'P1: ACTION/PROPS="man in suit dogeza at 90 degrees on a wall" | TEXT="壁面土下座" P2: ACTION/PROPS="man in suit spinning like a drill in dogeza" | TEXT="回転謝罪" P3: ACTION/PROPS="man in suit dogeza on a single finger" | TEXT="指一本の誠意" P4: ACTION/PROPS="man in suit growing giant in dogeza" | TEXT="巨大な謝罪" P5: ACTION/PROPS="man in suit shrinking tiny in dogeza" | TEXT="微力ながらお詫び" P6: ACTION/PROPS="man in suit dogeza with body transparent" | TEXT="影の薄い謝罪" P7: ACTION/PROPS="man in suit dogeza on the ceiling" | TEXT="天井からの誠意" P8: ACTION/PROPS="man in suit dogeza while running" | TEXT="走りながらお詫び" P9: ACTION/PROPS="man in suit dogeza in zero gravity" | TEXT="宇宙規模の申し訳なさ"',
        'P1: ACTION/PROPS="man in suit dogeza through a solid door" | TEXT="壁を越えた謝罪" P2: ACTION/PROPS="man in suit multi-armed dogeza like a deity" | TEXT="千手土下座" P3: ACTION/PROPS="man in suit dogeza while surfing on a wave" | TEXT="波乱のお詫び" P4: ACTION/PROPS="man in suit dogeza that creates a crater" | TEXT="重厚な謝罪" P5: ACTION/PROPS="man in suit dogeza while being on fire" | TEXT="燃える誠意" P6: ACTION/PROPS="man in suit dogeza while being frozen" | TEXT="凍えるお詫び" P7: ACTION/PROPS="man in suit dogeza that glows with divine light" | TEXT="神秘的な謝罪" P8: ACTION/PROPS="man in suit dogeza with pixelated glitch effect" | TEXT="デジタル土下座" P9: ACTION/PROPS="man in suit dogeza that leaves an afterimage" | TEXT="高速謝罪"',
        'P1: ACTION/PROPS="man in suit dogeza on a tightrope" | TEXT="崖っぷちの謝罪" P2: ACTION/PROPS="man in suit dogeza while floating on water" | TEXT="水に流して" P3: ACTION/PROPS="man in suit dogeza with limbs stretched like spaghetti" | TEXT="柔軟な対応" P4: ACTION/PROPS="man in suit dogeza while being upside down" | TEXT="逆転の謝意" P5: ACTION/PROPS="man in suit dogeza that looks like a bridge" | TEXT="架け橋となる謝罪" P6: ACTION/PROPS="man in suit dogeza that forms a circle" | TEXT="円満な解決へ" P7: ACTION/PROPS="man in suit dogeza while being invisible" | TEXT="気づかれない誠意" P8: ACTION/PROPS="man in suit dogeza that creates a black hole" | TEXT="吸い込まれるようなお詫び" P9: ACTION/PROPS="man in suit dogeza while falling" | TEXT="落下する誠意"',
        'P1: ACTION/PROPS="man in suit dogeza on the back of a flying bird" | TEXT="翼を授かった謝罪" P2: ACTION/PROPS="man in suit dogeza while being inside a bubble" | TEXT="壊れやすい誠意" P3: ACTION/PROPS="man in suit dogeza that looks like a knot" | TEXT="結ばれた謝罪" P4: ACTION/PROPS="man in suit dogeza while being made of slime" | TEXT="トロけるお詫び" P5: ACTION/PROPS="man in suit dogeza that turns into a shadow" | TEXT="影に潜む謝罪" P6: ACTION/PROPS="man in suit dogeza while holding a giant shield" | TEXT="守りの謝罪" P7: ACTION/PROPS="man in suit dogeza that causes an explosion" | TEXT="衝撃の申し訳なさ" P8: ACTION/PROPS="man in suit dogeza while playing a violin" | TEXT="哀愁の旋律に乗せて" P9: ACTION/PROPS="man in suit dogeza that looks like a statue" | TEXT="永久不変の謝意"',
        'P1: ACTION/PROPS="man in suit dogeza on the hands of a clock" | TEXT="時間を巻き戻したい謝罪" P2: ACTION/PROPS="man in suit dogeza while being made of light" | TEXT="光り輝くお詫び" P3: ACTION/PROPS="man in suit dogeza that looks like an origami" | TEXT="折り畳まれた誠意" P4: ACTION/PROPS="man in suit dogeza while being underwater" | TEXT="深い海の底からの謝罪" P5: ACTION/PROPS="man in suit dogeza that turns into a tree" | TEXT="根深い誠意" P6: ACTION/PROPS="man in suit dogeza while being inside a computer screen" | TEXT="画面越しのお詫び" P7: ACTION/PROPS="man in suit dogeza that looks like a thunderbolt" | TEXT="電撃的な謝意" P8: ACTION/PROPS="man in suit dogeza while being pulled by a magnet" | TEXT="引き寄せられる申し訳なさ" P9: ACTION/PROPS="man in suit dogeza that leaves a trail of flowers" | TEXT="華やかな謝罪"'
    ]
    save_csv('物理法則を無視した人間離れな土下座', theme3)

    # 4. 感情がタイツの色に出ちゃうシリーズ
    theme4 = [
        'P1: ACTION/PROPS="man in bright red suit radiating steam" | TEXT="激おこ" P2: ACTION/PROPS="man in dark blue suit with raindrops" | TEXT="どん底" P3: ACTION/PROPS="man in pink suit with floating hearts" | TEXT="キュン" P4: ACTION/PROPS="man in yellow suit sparkling" | TEXT="ハッピー" P5: ACTION/PROPS="man in purple suit with dark swirls" | TEXT="絶望" P6: ACTION/PROPS="man in orange suit laughing" | TEXT="爆笑" P7: ACTION/PROPS="man in green suit looking relaxed" | TEXT="癒やし" P8: ACTION/PROPS="man in white suit glowing" | TEXT="悟り" P9: ACTION/PROPS="man in black suit filled with mystery" | TEXT="意味深"',
        'P1: ACTION/PROPS="man in light blue suit with ice crystals" | TEXT="ガクブル" P2: ACTION/PROPS="man in brown suit acting modest" | TEXT="地味に嬉しい" P3: ACTION/PROPS="man in gold suit looking proud" | TEXT="大成功！" P4: ACTION/PROPS="man in silver suit looking cool" | TEXT="余裕ですの" P5: ACTION/PROPS="man in rainbow suit dancing" | TEXT="テンション爆上げ" P6: ACTION/PROPS="man in grey suit looking bored" | TEXT="虚無感" P7: ACTION/PROPS="man in magenta suit posing dramatically" | TEXT="主役は私" P8: ACTION/PROPS="man in turquoise suit feeling fresh" | TEXT="リフレッシュ" P9: ACTION/PROPS="man in navy suit looking serious" | TEXT="真剣勝負"',
        'P1: ACTION/PROPS="man in peach suit looking shy" | TEXT="照れますわ" P2: ACTION/PROPS="man in lime suit energetic" | TEXT="やる気全開！" P3: ACTION/PROPS="man in lavender suit feeling dreamy" | TEXT="うっとり" P4: ACTION/PROPS="man in maroon suit feeling elegant" | TEXT="上品に喜びます" P5: ACTION/PROPS="man in olive suit feeling calm" | TEXT="落ち着き" P6: ACTION/PROPS="man in teal suit feeling confident" | TEXT="任せておけ" P7: ACTION/PROPS="man in coral suit feeling friendly" | TEXT="仲良くしましょう" P8: ACTION/PROPS="man in emerald suit looking lucky" | TEXT="幸運です" P9: ACTION/PROPS="man in charcoal suit feeling heavy" | TEXT="責任感"',
        'P1: ACTION/PROPS="man in neon green suit looking toxic" | TEXT="毒舌モード" P2: ACTION/PROPS="man in champagne suit celebrating" | TEXT="おめでとうございます" P3: ACTION/PROPS="man in sky blue suit feeling free" | TEXT="開放感！" P4: ACTION/PROPS="man in apricot suit feeling gentle" | TEXT="ほっこり" P5: ACTION/PROPS="man in ruby suit feeling passionate" | TEXT="情熱を込めて" P6: ACTION/PROPS="man in sapphire suit feeling intellectual" | TEXT="分析中" P7: ACTION/PROPS="man in amber suit feeling nostalgic" | TEXT="懐かしいね" P8: ACTION/PROPS="man in mint suit feeling cool" | TEXT="涼しげに" P9: ACTION/PROPS="man in violet suit feeling artistic" | TEXT="感性の煌めき"',
        'P1: ACTION/PROPS="man in monochrome suit half black half white" | TEXT="葛藤中" P2: ACTION/PROPS="man in polka dot suit looking confused" | TEXT="おたおた" P3: ACTION/PROPS="man in striped suit feeling trapped" | TEXT="八方塞がり" P4: ACTION/PROPS="man in camo suit hiding" | TEXT="気付かないで" P5: ACTION/PROPS="man in metallic suit shining" | TEXT="最強の状態" P6: ACTION/PROPS="man in glitter suit sparkling" | TEXT="目立ちたがり" P7: ACTION/PROPS="man in translucent suit invisible" | TEXT="存在感ゼロ" P8: ACTION/PROPS="man in glowing suit in the dark" | TEXT="注目の的" P9: ACTION/PROPS="man in changing color suit" | TEXT="気分屋ですの"',
        'P1: ACTION/PROPS="man in pastel suit as soft as cotton candy" | TEXT="夢うつつ" P2: ACTION/PROPS="man in deep red suit burning" | TEXT="不屈の闘志" P3: ACTION/PROPS="man in clear suit like water" | TEXT="清らかな心" P4: ACTION/PROPS="man in earthy suit like a mountain" | TEXT="動じません" P5: ACTION/PROPS="man in electric suit sparking" | TEXT="衝撃的！" P6: ACTION/PROPS="man in shadow suit merging floor" | TEXT="落ち込み中" P7: ACTION/PROPS="man in cloud suit floating" | TEXT="ふわふわ" P8: ACTION/PROPS="man in diamond suit hard" | TEXT="鋼の意志" P9: ACTION/PROPS="man in aurora suit waving" | TEXT="神秘の微笑み"'
    ]
    save_csv('感情がタイツの色に出ちゃうシリーズ', theme4)

    # 5. 画面の端から無言のひょっこり
    theme5 = [
        'P1: ACTION/PROPS="man in suit peeking from bottom edge" | TEXT="見てますよ" P2: ACTION/PROPS="man in suit peeking from right side" | TEXT="チラッ" P3: ACTION/PROPS="man in suit appearing upside down from top" | TEXT="こんにちは" P4: ACTION/PROPS="man in suit peeking from behind a door" | TEXT="まだかな" P5: ACTION/PROPS="man in suit visible from dark corner" | TEXT="既読待ち" P6: ACTION/PROPS="man in suit looking through small hole" | TEXT="覗き見" P7: ACTION/PROPS="man in suit emerging from shadows" | TEXT="参上" P8: ACTION/PROPS="man in suit peeking with blank expression" | TEXT="無言の圧力" P9: ACTION/PROPS="man in suit zooming in from background" | TEXT="だんだん近づく"',
        'P1: ACTION/PROPS="man in suit peeking from under a table" | TEXT="潜入中" P2: ACTION/PROPS="man in suit peeking from behind a flower pot" | TEXT="自然を装う" P3: ACTION/PROPS="man in suit peeking from a laptop lid" | TEXT="作業監視" P4: ACTION/PROPS="man in suit peeking through a gap in curtains" | TEXT="視線を感じて" P5: ACTION/PROPS="man in suit peeking from behind a stack of books" | TEXT="勉強中かな？" P6: ACTION/PROPS="man in suit peeking from a mailbox" | TEXT="届きました？" P7: ACTION/PROPS="man in suit peeking from a cereal box" | TEXT="おはようございます" P8: ACTION/PROPS="man in suit peeking from behind a clock" | TEXT="時間の確認" P9: ACTION/PROPS="man in suit peeking from a coffee mug" | TEXT="ひと休み？"',
        'P1: ACTION/PROPS="man in suit peeking with binoculars" | TEXT="遠くから見てます" P2: ACTION/PROPS="man in suit peeking while holding a magnifier" | TEXT="細部までチェック" P3: ACTION/PROPS="man in suit peeking with a periscope" | TEXT="水中から失礼" P4: ACTION/PROPS="man in suit peeking through a heart-shaped hole" | TEXT="愛の視線" P5: ACTION/PROPS="man in suit peeking from a digital frame" | TEXT="画像だと思った？" P6: ACTION/PROPS="man in suit peeking from behind a giant fan" | TEXT="風と共に" P7: ACTION/PROPS="man in suit peeking with night vision goggles" | TEXT="暗闇でもバッチリ" P8: ACTION/PROPS="man in suit peeking from behind a smartphone" | TEXT="ここにいますよ" P9: ACTION/PROPS="man in suit peeking while hanging from a rope" | TEXT="上空からひょっこり"',
        'P1: ACTION/PROPS="man in suit peeking from a cloud" | TEXT="お空から見てます" P2: ACTION/PROPS="man in suit peeking from behind a moon" | TEXT="良い夜を" P3: ACTION/PROPS="man in suit peeking from a star" | TEXT="願い事かなえようか" P4: ACTION/PROPS="man in suit peeking from a rainbow edge" | TEXT="幸運の予感" P5: ACTION/PROPS="man in suit peeking from behind a sun" | TEXT="眩しいですが" P6: ACTION/PROPS="man in suit peeking from a lightning bolt" | TEXT="電撃的に参上" P7: ACTION/PROPS="man in suit peeking from a raindrop" | TEXT="しっとりと" P8: ACTION/PROPS="man in suit peeking from a snow pile" | TEXT="ひんやりひょっこり" P9: ACTION/PROPS="man in suit peeking from a tornado" | TEXT="嵐を呼ぶおじさん"',
        'P1: ACTION/PROPS="man in suit peeking from a gift box" | TEXT="サプライズ！" P2: ACTION/PROPS="man in suit peeking from a shopping bag" | TEXT="買っちゃった？" P3: ACTION/PROPS="man in suit peeking from a backpack" | TEXT="お供します" P4: ACTION/PROPS="man in suit peeking from a pocket" | TEXT="ポッケの中に" P5: ACTION/PROPS="man in suit peeking from a shoe" | TEXT="サイズ合います？" P6: ACTION/PROPS="man in suit peeking from a hat" | TEXT="手品かな？" P7: ACTION/PROPS="man in suit peeking from a guitar hole" | TEXT="良い音色" P8: ACTION/PROPS="man in suit peeking from a soccer ball" | TEXT="ナイスゴール" P9: ACTION/PROPS="man in suit peeking from a trophy cup" | TEXT="おめでとうございます！"',
        'P1: ACTION/PROPS="man in suit peeking with suspicious eyes" | TEXT="怪しい…" P2: ACTION/PROPS="man in suit peeking with sparkling eyes" | TEXT="期待に満ちて" P3: ACTION/PROPS="man in suit peeking with watery eyes" | TEXT="見捨てないで" P4: ACTION/PROPS="man in suit peeking while eating ramen" | TEXT="もぐもぐ…" P5: ACTION/PROPS="man in suit peeking while holding a sign saying \"WAITING\"" | TEXT="返信待ち" P6: ACTION/PROPS="man in suit peeking while yawning" | TEXT="まだ起きてます" P7: ACTION/PROPS="man in suit peeking while blinking rapidly" | TEXT="現実かな？" P8: ACTION/PROPS="man in suit peeking with a thumbs up" | TEXT="いいぞ" P9: ACTION/PROPS="man in suit peeking with a scary mask" | TEXT="わっ！"'
    ]
    save_csv('画面の端から無言のひょっこり', theme5)

    # 6. セルフ応援団
    theme6 = [
        'P1: ACTION/PROPS="man in suit vigorously shaking pom-poms" | TEXT="ファイト！" P2: ACTION/PROPS="man in suit blowing a whistle" | TEXT="気合入れろ！" P3: ACTION/PROPS="man in suit high jump with pom-poms" | TEXT="いけるいける！" P4: ACTION/PROPS="man in suit holding giant flag" | TEXT="大逆転！" P5: ACTION/PROPS="man in suit doing cheerleader split" | TEXT="ナイス！" P6: ACTION/PROPS="man in suit banging a drum" | TEXT="ドンドコ！" P7: ACTION/PROPS="man in suit yelling into megaphone" | TEXT="聞こえますか！" P8: ACTION/PROPS="man in suit with victory pose" | TEXT="最高！" P9: ACTION/PROPS="man in suit doing energetic cheer dance" | TEXT="わっしょい！"',
        'P1: ACTION/PROPS="man in suit performing a backflip cheer" | TEXT="アクロバティック！" P2: ACTION/PROPS="man in suit waving a handkerchief" | TEXT="フレーフレー！" P3: ACTION/PROPS="man in suit doing a group wave alone" | TEXT="一人で盛り上がる" P4: ACTION/PROPS="man in suit blowing a trumpet" | TEXT="ファンファーレ！" P5: ACTION/PROPS="man in suit throwing cheering confetti" | TEXT="おめでとう！" P6: ACTION/PROPS="man in suit doing a heroic landing" | TEXT="準備はいいか！" P7: ACTION/PROPS="man in suit holding a supportive banner" | TEXT="全力で推します" P8: ACTION/PROPS="man in suit doing a synchronized clap" | TEXT="パンパン！" P9: ACTION/PROPS="man in suit doing a celebratory slide" | TEXT="やったぜ！"',
        'P1: ACTION/PROPS="man in suit cheering with a glowing stick" | TEXT="輝いてるよ！" P2: ACTION/PROPS="man in suit doing a silent cheer with focus" | TEXT="祈ってるからね" P3: ACTION/PROPS="man in suit running along to support" | TEXT="どこまでもついていく" P4: ACTION/PROPS="man in suit doing a belly dance of joy" | TEXT="お祝いだ！" P5: ACTION/PROPS="man in suit boxing the air to cheer" | TEXT="自分に負けるな！" P6: ACTION/PROPS="man in suit doing a funny victory dance" | TEXT="ウキウキ！" P7: ACTION/PROPS="man in suit forming a heart with arms" | TEXT="大好きだよ！" P8: ACTION/PROPS="man in suit giving a huge thumbs up" | TEXT="完璧！" P9: ACTION/PROPS="man in suit shedding tears of joy" | TEXT="感動しました！"',
        'P1: ACTION/PROPS="man in suit shouting while holding a fan" | TEXT="推しが尊い" P2: ACTION/PROPS="man in suit doing a high-five in mirror" | TEXT="自画自賛" P3: ACTION/PROPS="man in suit holding a sign with your name" | TEXT="君が一番！" P4: ACTION/PROPS="man in suit wearing a headband with \"FIGHT\"" | TEXT="不屈の精神" P5: ACTION/PROPS="man in suit doing a victory lap" | TEXT="止まらない喜び" P6: ACTION/PROPS="man in suit pumping fists in the air" | TEXT="よっしゃー！" P7: ACTION/PROPS="man in suit throwing a wreath" | TEXT="栄光を君に" P8: ACTION/PROPS="man in suit doing a standing ovation" | TEXT="ブラボー！" P9: ACTION/PROPS="man in suit flashing a victory sign" | TEXT="勝訴！"',
        'P1: ACTION/PROPS="man in suit cheering while floating on balloons" | TEXT="舞い上がる気分" P2: ACTION/PROPS="man in suit doing a sumo victory stomp" | TEXT="どすこい！" P3: ACTION/PROPS="man in suit wearing a mascot costume half-way" | TEXT="中身も応援" P4: ACTION/PROPS="man in suit doing a breakdance move" | TEXT="キレキレ応援" P5: ACTION/PROPS="man in suit blowing a party horn" | TEXT="パーッといこう！" P6: ACTION/PROPS="man in suit acting like a superstar" | TEXT="君もスターだ" P7: ACTION/PROPS="man in suit doing a bow of respect" | TEXT="頭が下がります" P8: ACTION/PROPS="man in suit holding out a gold medal" | TEXT="君に授与します" P9: ACTION/PROPS="man in suit dancing with a colorful umbrella" | TEXT="華やかにいこう！"',
        'P1: ACTION/PROPS="man in suit cheering with a microphone" | TEXT="実況室からお届け" P2: ACTION/PROPS="man in suit doing a wave of fire" | TEXT="激熱！" P3: ACTION/PROPS="man in suit creating a human pyramid alone" | TEXT="団結力（独り）" P4: ACTION/PROPS="man in suit doing a salute with pride" | TEXT="了解しました！" P5: ACTION/PROPS="man in suit waving with a gentle face" | TEXT="いつも見守ってるよ" P6: ACTION/PROPS="man in suit doing a sprint to the finish" | TEXT="最後まで駆け抜けろ" P7: ACTION/PROPS="man in suit cheering while holding a teacup" | TEXT="落ち着きつつ応援" P8: ACTION/PROPS="man in suit making a peace sign in both hands" | TEXT="ハッピーピース" P9: ACTION/PROPS="man in suit doing a jumping kick of victory" | TEXT="限界突破！"'
    ]
    save_csv('セルフ応援団', theme6)

    # 7. 昭和ヒーロー風の古すぎる決めポーズ
    theme7 = [
        'P1: ACTION/PROPS="man in suit striking a Sentai transformation pose" | TEXT="了解です！" P2: ACTION/PROPS="man in suit pointing to the sky heroically" | TEXT="承知いたしました" P3: ACTION/PROPS="man in suit posing with legs wide apart" | TEXT="承りました" P4: ACTION/PROPS="man in suit doing a martial arts salute" | TEXT="お任せください" P5: ACTION/PROPS="man in suit with a hand on the hip, laughing" | TEXT="ハハハ！任せろ" P6: ACTION/PROPS="man in suit striking a pose with explosions in back" | TEXT="参上しました！" P7: ACTION/PROPS="man in suit doing a classic \"Hen-shin\" pose" | TEXT="切り替えていきます" P8: ACTION/PROPS="man in suit pointing forward with a wink" | TEXT="君に決めた！" P9: ACTION/PROPS="man in suit doing a dramatic cape flourish" | TEXT="正義は勝つ！"',
        'P1: ACTION/PROPS="man in suit posing as if holding a sword" | TEXT="一閃！" P2: ACTION/PROPS="man in suit doing a high-speed dash pose" | TEXT="即座に向かいます" P3: ACTION/PROPS="man in suit posing with a shadow cast over eyes" | TEXT="覚悟はできている" P4: ACTION/PROPS="man in suit doing a flying kick pose" | TEXT="突破します！" P5: ACTION/PROPS="man in suit striking a lightning strike pose" | TEXT="電撃的な承諾" P6: ACTION/PROPS="man in suit posing in the sunset" | TEXT="また明日会おう" P7: ACTION/PROPS="man in suit doing a heroic landing pose" | TEXT="お待たせしました" P8: ACTION/PROPS="man in suit striking a pose on a pedestal" | TEXT="崇めてもいいぞ" P9: ACTION/PROPS="man in suit doing a special move pose" | TEXT="必殺・了解！"',
        'P1: ACTION/PROPS="man in suit striking a pose with a giant mechanical heart" | TEXT="心意気ですの" P2: ACTION/PROPS="man in suit doing a pose like a vintage anime hero" | TEXT="古き良き誠意" P3: ACTION/PROPS="man in suit posing with a glowing eyes effect" | TEXT="全て見えています" P4: ACTION/PROPS="man in suit doing a pose with a peace sign in the dark" | TEXT="平和が一番" P5: ACTION/PROPS="man in suit striking a pose like a detective" | TEXT="謎は解けました" P6: ACTION/PROPS="man in suit doing a pose with a thumbs up on a bike" | TEXT="風のように承知" P7: ACTION/PROPS="man in suit posing as a giant guardian" | TEXT="守り抜きます" P8: ACTION/PROPS="man in suit striking a pose with a mysterious flower" | TEXT="愛と勇気のおじさん" P9: ACTION/PROPS="man in suit doing a pose with both arms raised" | TEXT="大勝利！"',
        'P1: ACTION/PROPS="man in suit posing as a star under a spotlight" | TEXT="私が主役です" P2: ACTION/PROPS="man in suit striking a pose of ultimate justice" | TEXT="正道を往く" P3: ACTION/PROPS="man in suit doing a pose as if catching a bullet" | TEXT="受け止めました" P4: ACTION/PROPS="man in suit striking a pose during a thunderstorm" | TEXT="衝撃の了解" P5: ACTION/PROPS="man in suit posing with a serious fist to the chest" | TEXT="魂で承諾" P6: ACTION/PROPS="man in suit doing a pose like an urban legend hero" | TEXT="噂の了解" P7: ACTION/PROPS="man in suit striking a pose with a shining medal" | TEXT="誇りを持って" P8: ACTION/PROPS="man in suit doing a pose like a galactic guardian" | TEXT="宇宙の調和のために" P9: ACTION/PROPS="man in suit striking a pose with a heroic shout" | TEXT="届け、この想い！"',
        'P1: ACTION/PROPS="man in suit striking a pose with heavy armor pieces" | TEXT="完全防備で了解" P2: ACTION/PROPS="man in suit doing a pose like a masked avenger" | TEXT="匿名で承諾" P3: ACTION/PROPS="man in suit posing with a billowing scarf" | TEXT="風に吹かれて" P4: ACTION/PROPS="man in suit striking a pose with an energy shield" | TEXT="鉄壁の了解" P5: ACTION/PROPS="man in suit doing a pose like a vintage movie star" | TEXT="ダンディに承知" P6: ACTION/PROPS="man in suit striking a pose with a majestic eagle" | TEXT="誇り高きおじさん" P7: ACTION/PROPS="man in suit posing with a legendary weapon" | TEXT="一撃で解決" P8: ACTION/PROPS="man in suit striking a pose with a map to the future" | TEXT="道は開かれた" P9: ACTION/PROPS="man in suit doing a pose with a celebratory firework" | TEXT="ド派手に了解！"',
        'P1: ACTION/PROPS="man in suit striking a pose with a determined gaze" | TEXT="目は嘘をつかない" P2: ACTION/PROPS="man in suit doing a pose like a secret agent" | TEXT="極秘で承知" P3: ACTION/PROPS="man in suit posing with a heroic cape made of money" | TEXT="資本主義のヒーロー" P4: ACTION/PROPS="man in suit striking a pose with a digital blueprint" | TEXT="計算通りです" P5: ACTION/PROPS="man in suit doing a pose like a martial arts master" | TEXT="精神統一" P6: ACTION/PROPS="man in suit striking a pose with a celestial globe" | TEXT="運命を受け入れる" P7: ACTION/PROPS="man in suit posing with a golden microphone" | TEXT="高らかに了解！" P8: ACTION/PROPS="man in suit striking a pose with a futuristic phone" | TEXT="通信完了" P9: ACTION/PROPS="man in suit doing a pose with a triumphant roar" | TEXT="おじさん、爆誕！"'
    ]
    save_csv('昭和ヒーロー風の古すぎる決めポーズ', theme7)

    # 8. 欲望に負けて理性が崩壊する瞬間
    theme8 = [
        'P1: ACTION/PROPS="man in suit drooling at a huge steak" | TEXT="食らいつく！" P2: ACTION/PROPS="man in suit surrounded by many shopping bags" | TEXT="大人買い！" P3: ACTION/PROPS="man in suit hugging a giant money bill" | TEXT="金の亡者" P4: ACTION/PROPS="man in suit eyes turning into dollar signs" | TEXT="欲望の塊" P5: ACTION/PROPS="man in suit diving into a pool of chocolate" | TEXT="甘い誘惑" P6: ACTION/PROPS="man in suit franticly grabbing limited items" | TEXT="早い者勝ち！" P7: ACTION/PROPS="man in suit crying while hugging a new gadget" | TEXT="欲しかったんだ" P8: ACTION/PROPS="man in suit ignoring everything to eat ramen" | TEXT="本能のままに" P9: ACTION/PROPS="man in suit laughing madly with treasures" | TEXT="私のものだ！"',
        'P1: ACTION/PROPS="man in suit looking at a jewelry store longingly" | TEXT="キラキラしてる…" P2: ACTION/PROPS="man in suit smelling fresh bread like a drug" | TEXT="抗えない香り" P3: ACTION/PROPS="man in suit holding ten ice cream cones" | TEXT="全部食べます" P4: ACTION/PROPS="man in suit sleeping on a pile of luxury goods" | TEXT="幸福の眠り" P5: ACTION/PROPS="man in suit looking at a discount tag with intensity" | TEXT="安さは正義" P6: ACTION/PROPS="man in suit reaching out to a forbidden switch" | TEXT="押さずにはいられない" P7: ACTION/PROPS="man in suit buried in plush toys" | TEXT="癒やされたい" P8: ACTION/PROPS="man in suit dancing with a bottle of champagne" | TEXT="贅沢ざんまい" P9: ACTION/PROPS="man in suit looking at a sleek car in despair" | TEXT="ローン組んじゃう？"',
        'P1: ACTION/PROPS="man in suit eating a bowl of rice like crazy" | TEXT="米こそ命" P2: ACTION/PROPS="man in suit hugging a huge pillow with a face" | TEXT="愛に飢えてる" P3: ACTION/PROPS="man in suit swimming in a sea of coffee beans" | TEXT="目覚めたい" P4: ACTION/PROPS="man in suit looking at a rare sneaker through glass" | TEXT="芸術品ですの" P5: ACTION/PROPS="man in suit eating a whole cake by hand" | TEXT="罪の味" P6: ACTION/PROPS="man in suit holding a lottery ticket with shaking hands" | TEXT="夢を見させて" P7: ACTION/PROPS="man in suit looking at a video game console longingly" | TEXT="時間が欲しい" P8: ACTION/PROPS="man in suit smelling a leather jacket deeply" | TEXT="大人の香り" P9: ACTION/PROPS="man in suit losing control in a toy store" | TEXT="子供に戻る瞬間"',
        'P1: ACTION/PROPS="man in suit reaching for a snack late at night" | TEXT="深夜の誘惑" P2: ACTION/PROPS="man in suit looking at a high-end watch in awe" | TEXT="時を刻む贅沢" P3: ACTION/PROPS="man in suit holding too many arcade tickets" | TEXT="止まらない情熱" P4: ACTION/PROPS="man in suit eyes locked on a juicy burger" | TEXT="脳が震える" P5: ACTION/PROPS="man in suit staring at the last piece of pizza" | TEXT="譲れません" P6: ACTION/PROPS="man in suit ignoring a diet book" | TEXT="明日から本気出す" P7: ACTION/PROPS="man in suit hugging a giant bag of candy" | TEXT="独り占め" P8: ACTION/PROPS="man in suit watching a slow-motion pour of syrup" | TEXT="溺れたい" P9: ACTION/PROPS="man in suit reaching for a mystery box" | TEXT="中身が気になる！"',
        'P1: ACTION/PROPS="man in suit looking at a first-class airplane ticket" | TEXT="飛び立ちたい" P2: ACTION/PROPS="man in suit smelling an expensive perfume" | TEXT="天国の香り" P3: ACTION/PROPS="man in suit buried in colorful fancy clothes" | TEXT="お洒落番長" P4: ACTION/PROPS="man in suit staring at a mountain of fried chicken" | TEXT="茶色は正義" P5: ACTION/PROPS="man in suit looking at a shiny golden bar" | TEXT="ズッシリ重い" P6: ACTION/PROPS="man in suit smelling the air of a luxury hotel" | TEXT="これが成功の味か" P7: ACTION/PROPS="man in suit holding a smartphone with multiple apps open" | TEXT="情報過多でも欲しい" P8: ACTION/PROPS="man in suit looking at a massage chair longingly" | TEXT="天国への階段" P9: ACTION/PROPS="man in suit staring at a fountain of soda" | TEXT="シュワシュワしたい"',
        'P1: ACTION/PROPS="man in suit reaching for a glowing limited edition item" | TEXT="伝説を手に入れる" P2: ACTION/PROPS="man in suit holding a giant donut as a steering wheel" | TEXT="甘いドライブ" P3: ACTION/PROPS="man in suit smelling fresh ink on a new book" | TEXT="知の欲望" P4: ACTION/PROPS="man in suit staring at a buffet table in shock" | TEXT="全部、私の領域" P5: ACTION/PROPS="man in suit hugging a giant water bottle" | TEXT="渇きを癒して" P6: ACTION/PROPS="man in suit reaching for a high-spec PC" | TEXT="加速したい" P7: ACTION/PROPS="man in suit looking at a vintage camera longingly" | TEXT="切り取りたい、一瞬を" P8: ACTION/PROPS="man in suit staring at a soft bed in a store" | TEXT="一生寝てたい" P9: ACTION/PROPS="man in suit reaching for the stars (literally shopping for space)" | TEXT="欲望は無限大"'
    ]
    save_csv('欲望に負けて理性が崩壊する瞬間', theme8)

    # 9. 壁に埋まったり宙に浮くバグポーズ
    theme9 = [
        'P1: ACTION/PROPS="man in suit legs glitched into the floor" | TEXT="埋まりました" P2: ACTION/PROPS="man in suit head detached and floating" | TEXT="思考停止" P3: ACTION/PROPS="man in suit stretched out like a noodle" | TEXT="混乱中" P4: ACTION/PROPS="man in suit T-posing stiffly" | TEXT="初期化中" P5: ACTION/PROPS="man in suit folded into himself" | TEXT="エラー発生" P6: ACTION/PROPS="man in suit rotating like a fan horizontally" | TEXT="ぐるぐるどっかーん" P7: ACTION/PROPS="man in suit body fragmented into polygons" | TEXT="解像度がヤバい" P8: ACTION/PROPS="man in suit floating upside down" | TEXT="重力が仕事してない" P9: ACTION/PROPS="man in suit vibrating at high speed" | TEXT="プルプルする…！"',
        'P1: ACTION/PROPS="man in suit arms glitched behind his back" | TEXT="身動きが…" P2: ACTION/PROPS="man in suit blinking in and out of existence" | TEXT="存在が不安定" P3: ACTION/PROPS="man in suit walking on air" | TEXT="空中散歩（強制）" P4: ACTION/PROPS="man in suit body turning into liquid" | TEXT="溶けていく…" P5: ACTION/PROPS="man in suit looking through his own chest" | TEXT="中身が空っぽ" P6: ACTION/PROPS="man in suit multiplied into a line" | TEXT="残像だ…" P7: ACTION/PROPS="man in suit growing long fingers" | TEXT="リーチが伸びた" P8: ACTION/PROPS="man in suit head replaced by a placeholder box" | TEXT="読み込み中" P9: ACTION/PROPS="man in suit body turned into a low-poly dog" | TEXT="私は誰…？"',
        'P1: ACTION/PROPS="man in suit walking through a closed door" | TEXT="ノーモーション通過" P2: ACTION/PROPS="man in suit floating while sitting on a non-existent chair" | TEXT="エアチェア" P3: ACTION/PROPS="man in suit jumping through the ceiling" | TEXT="突き抜けました" P4: ACTION/PROPS="man in suit body turned into a flat 2D sprite" | TEXT="厚みがありません" P5: ACTION/PROPS="man in suit spinning his head only" | TEXT="360度確認" P6: ACTION/PROPS="man in suit feet replaced by wheels" | TEXT="高速移動モード" P7: ACTION/PROPS="man in suit emitting digital sparks" | TEXT="ショート寸前" P8: ACTION/PROPS="man in suit getting stuck in a wall corner" | TEXT="詰みました" P9: ACTION/PROPS="man in suit turned into a huge pixel art" | TEXT="レトロにバグる"',
        'P1: ACTION/PROPS="man in suit hands stuck in a praying position" | TEXT="誠意が固定された" P2: ACTION/PROPS="man in suit stretching his neck like a giraffe" | TEXT="遠くが見える" P3: ACTION/PROPS="man in suit rotating his torso 180 degrees" | TEXT="真後ろにこんちは" P4: ACTION/PROPS="man in suit body flickering in rainbow colors" | TEXT="ゲーミングおじさん" P5: ACTION/PROPS="man in suit floating with a single leg" | TEXT="片足の奇跡" P6: ACTION/PROPS="man in suit shadow moving differently from the body" | TEXT="影が意思を持った" P7: ACTION/PROPS="man in suit getting stretched horizontally" | TEXT="引き伸ばされた日々" P8: ACTION/PROPS="man in suit body turning into wireframe" | TEXT="骨組み丸出し" P9: ACTION/PROPS="man in suit head becoming huge" | TEXT="脳内パンク中"',
        'P1: ACTION/PROPS="man in suit walking sideways on a wall" | TEXT="重力の無視（第2弾）" P2: ACTION/PROPS="man in suit sinking into a sofa like a swamp" | TEXT="同化しすぎた" P3: ACTION/PROPS="man in suit arms becoming long tentacles" | TEXT="マルチタスク可能" P4: ACTION/PROPS="man in suit head popping off and returning" | TEXT="びっくりした？" P5: ACTION/PROPS="man in suit body bending like a folded paper" | TEXT="折り畳みおじさん" P6: ACTION/PROPS="man in suit stepping on a cloud" | TEXT="足場が浮いてる" P7: ACTION/PROPS="man in suit body turned into a silhouette with stars" | TEXT="宇宙を感じる" P8: ACTION/PROPS="man in suit getting squashed like a pancake" | TEXT="圧が凄かった" P9: ACTION/PROPS="man in suit body turning into many small balls" | TEXT="分散しました"',
        'P1: ACTION/PROPS="man in suit head spinning like a coin" | TEXT="運任せ" P2: ACTION/PROPS="man in suit arms crossed in a recursive loop" | TEXT="ループから抜け出せない" P3: ACTION/PROPS="man in suit legs turning into bird legs" | TEXT="進化しました" P4: ACTION/PROPS="man in suit body flickering like an old TV" | TEXT="時代遅れのバグ" P5: ACTION/PROPS="man in suit getting stuck in the air after a jump" | TEXT="着地失敗" P6: ACTION/PROPS="man in suit head replaced by a smiling emoji" | TEXT="表情筋が死んだ" P7: ACTION/PROPS="man in suit body turning into a barcode" | TEXT="値札付き" P8: ACTION/PROPS="man in suit running in place with high speed" | TEXT="空回り中" P9: ACTION/PROPS="man in suit body turning into a question mark" | TEXT="理解不能"'
    ]
    save_csv('壁に埋まったり宙に浮くバグポーズ', theme9)

    # 10. 虚無の表情でどこでも寝落ち
    theme10 = [
        'P1: ACTION/PROPS="man in suit sleeping while standing" | TEXT="限界です" P2: ACTION/PROPS="man in suit sleeping on a busy train" | TEXT="座らせて…" P3: ACTION/PROPS="man in suit face down on a desk" | TEXT="力尽きました" P4: ACTION/PROPS="man in suit sleeping with open eyes" | TEXT="虚無の世界" P5: ACTION/PROPS="man in suit sleeping on a park bench" | TEXT="家が遠い…" P6: ACTION/PROPS="man in suit sleeping during a meeting" | TEXT="寝てません、考えてます" P7: ACTION/PROPS="man in suit sleeping in a bathtub" | TEXT="危ないですよ" P8: ACTION/PROPS="man in suit sleeping while walking" | TEXT="無意識の行進" P9: ACTION/PROPS="man in suit sleeping on a pile of papers" | TEXT="おやすみなさい"',
        'P1: ACTION/PROPS="man in suit sleeping while eating ramen" | TEXT="麺を啜りながら…" P2: ACTION/PROPS="man in suit sleeping on a treadmill" | TEXT="運動後の燃え尽き" P3: ACTION/PROPS="man in suit sleeping in a shopping cart" | TEXT="誰か運んで" P4: ACTION/PROPS="man in suit sleeping while holding a phone" | TEXT="寝落ち通話（無言）" P5: ACTION/PROPS="man in suit sleeping on a library floor" | TEXT="知の海で入眠" P6: ACTION/PROPS="man in suit sleeping while typing" | TEXT="あいうえおやすみ" P7: ACTION/PROPS="man in suit sleeping during a movie" | TEXT="エンドロールまで待てない" P8: ACTION/PROPS="man in suit sleeping on a ladder" | TEXT="到達する前の休息" P9: ACTION/PROPS="man in suit sleeping while holding a coffee cup" | TEXT="カフェイン負け"',
        'P1: ACTION/PROPS="man in suit sleeping with a bubble from nose" | TEXT="熟睡中" P2: ACTION/PROPS="man in suit sleeping while sitting on a toilet" | TEXT="深い瞑想（寝落ち）" P3: ACTION/PROPS="man in suit sleeping on a vibrating massage chair" | TEXT="揺られながら…" P4: ACTION/PROPS="man in suit sleeping while standing in a queue" | TEXT="順番が来たら起こして" P5: ACTION/PROPS="man in suit sleeping on a yoga mat" | TEXT="究極のリラックス" P6: ACTION/PROPS="man in suit sleeping while looking at a sunset" | TEXT="黄金の眠り" P7: ACTION/PROPS="man in suit sleeping on top of a car" | TEXT="風を感じて（停車中）" P8: ACTION/PROPS="man in suit sleeping while holding a giant bear" | TEXT="癒やしが必要" P9: ACTION/PROPS="man in suit sleeping with a tiny blanket" | TEXT="寒さに負けない心"',
        'P1: ACTION/PROPS="man in suit sleeping on a luggage carousel" | TEXT="流されていく人生" P2: ACTION/PROPS="man in suit sleeping while doing a handstand" | TEXT="バランスを保ったまま入眠" P3: ACTION/PROPS="man in suit sleeping inside a cardboard box" | TEXT="狭いところが落ち着く" P4: ACTION/PROPS="man in suit sleeping with a smiling face" | TEXT="良い夢見てます" P5: ACTION/PROPS="man in suit sleeping and snoring visibly" | TEXT="爆睡宣言" P6: ACTION/PROPS="man in suit sleeping while holding an umbrella" | TEXT="雨音を子守唄に" P7: ACTION/PROPS="man in suit sleeping on a staircase" | TEXT="一休みが長すぎた" P8: ACTION/PROPS="man in suit sleeping during a live concert" | TEXT="爆音の中でも安らぎ" P9: ACTION/PROPS="man in suit sleeping with an open book on face" | TEXT="活字の誘惑"',
        'P1: ACTION/PROPS="man in suit sleeping on a floating leaf" | TEXT="自然と同化" P2: ACTION/PROPS="man in suit sleeping while balancing on a ball" | TEXT="神業の寝落ち" P3: ACTION/PROPS="man in suit sleeping with a light bulb above head" | TEXT="閃きながら眠る" P4: ACTION/PROPS="man in suit sleeping while being carried by birds" | TEXT="空の旅路へ" P5: ACTION/PROPS="man in suit sleeping on a giant hamburger" | TEXT="夢の中も満腹" P6: ACTION/PROPS="man in suit sleeping while hugging a clock" | TEXT="時を止めて" P7: ACTION/PROPS="man in suit sleeping inside a giant bubble" | TEXT="夢の膜に包まれて" P8: ACTION/PROPS="man in suit sleeping on a field of flowers" | TEXT="雅な眠り" P9: ACTION/PROPS="man in suit sleeping while holding a "DO NOT DISTURB" sign" | TEXT="お静かに…"',
        'P1: ACTION/PROPS="man in suit sleeping in an empty stadium" | TEXT="孤独な休息" P2: ACTION/PROPS="man in suit sleeping while the sun is already high" | TEXT="朝に弱すぎる" P3: ACTION/PROPS="man in suit sleeping with a cat on his back" | TEXT="重みが心地よい" P4: ACTION/PROPS="man in suit sleeping while doing "peace" sign" | TEXT="平和に入眠" P5: ACTION/PROPS="man in suit sleeping on a pile of money" | TEXT="欲望の果ての眠り" P6: ACTION/PROPS="man in suit sleeping while waiting for a download" | TEXT="進まない時間" P7: ACTION/PROPS="man in suit sleeping with one eye slightly open" | TEXT="見張ってます（寝てます）" P8: ACTION/PROPS="man in suit sleeping on a surfboard" | TEXT="波のリズムで" P9: ACTION/PROPS="man in suit sleeping while holding a microphone" | TEXT="最期の言葉は「おやすみ」"'
    ]
    save_csv('虚無の表情でどこでも寝落ち', theme10)

if __name__ == "__main__":
    generate_all()
