import csv

rows = [
    'P1: ACTION/PROPS="A person in a green full-body tight suit with face exposed and bowing politely with a serious face" | TEXT="おはよう" P2: ACTION/PROPS="A person in a yellow full-body tight suit waving both hands energetically" | TEXT="おつかれさま！" P3: ACTION/PROPS="A person in a red full-body tight suit saluting sharply" | TEXT="了解です！" P4: ACTION/PROPS="A person in a blue full-body tight suit pressing hands together in a deep apology" | TEXT="ごめんなさい！" P5: ACTION/PROPS="A person in a pink full-body tight suit giving a thumbs up with a sparkling wink" | TEXT="ありがとう！" P6: ACTION/PROPS="A person in a black full-body tight suit lying on a futon and sleeping peacefully" | TEXT="おやすみ" P7: ACTION/PROPS="A person in a white full-body tight suit peeking out from a cardboard box" | TEXT="よっ" P8: ACTION/PROPS="A person in a purple full-body tight suit doing a polite dogeza on the floor" | TEXT="お願いします！" P9: ACTION/PROPS="A person in an orange full-body tight suit holding a teacup and sitting on a cushion" | TEXT="ひとやすみ"',
    'P1: ACTION/PROPS="A person in a full-body tight suit jumping high with a huge joyful smile" | TEXT="最高！" P2: ACTION/PROPS="A person in a full-body tight suit dancing weirdly with a totally straight face" | TEXT="イェーイ" P3: ACTION/PROPS="A person in a full-body tight suit throwing confetti with an ecstatic expression" | TEXT="おめでとう！" P4: ACTION/PROPS="A person in a full-body tight suit holding a massive gold trophy while crying tears of joy" | TEXT="勝訴" P5: ACTION/PROPS="A person in a full-body tight suit spinning rapidly like a top" | TEXT="キター！" P6: ACTION/PROPS="A person in a full-body tight suit laughing out loud while pointing at something" | TEXT="草" P7: ACTION/PROPS="A person in a full-body tight suit clapping aggressively with a super intense face" | TEXT="天才！" P8: ACTION/PROPS="A person in a full-body tight suit doing a flawless split on the floor with a proud face" | TEXT="余裕です" P9: ACTION/PROPS="A person in a full-body tight suit flying through the sky like Superman" | TEXT="向かってます！"',
    'P1: ACTION/PROPS="A person in a full-body tight suit sitting on the floor hugging knees and looking depressed" | TEXT="スン…" P2: ACTION/PROPS="A person in a full-body tight suit lying face down on the ground like a dried-up fish" | TEXT="もうダメだ" P3: ACTION/PROPS="A person in a full-body tight suit fading away into dust with a sad smile" | TEXT="さようなら" P4: ACTION/PROPS="A person in a full-body tight suit crying violently like a waterfall" | TEXT="ぴえん" P5: ACTION/PROPS="A person in a full-body tight suit holding a broken heart shape prop and looking devastated" | TEXT="傷ついた" P6: ACTION/PROPS="A person in a full-body tight suit turning completely pale and frozen like a statue" | TEXT="終わった" P7: ACTION/PROPS="A person in a full-body tight suit standing under a heavy rain cloud with no umbrella" | TEXT="どんまい" P8: ACTION/PROPS="A person in a full-body tight suit shivering violently in cold wind" | TEXT="無理…" P9: ACTION/PROPS="A person in a full-body tight suit slowly sinking into a swamp" | TEXT="沈む"',
    'P1: ACTION/PROPS="A person in a full-body tight suit slamming a desk aggressively" | TEXT="なんでやねん！" P2: ACTION/PROPS="A person in a full-body tight suit exhaling fire like a dragon with an angry face" | TEXT="激おこ" P3: ACTION/PROPS="A person in a full-body tight suit holding a giant megaphone and shouting" | TEXT="聞けー！" P4: ACTION/PROPS="A person in a full-body tight suit glaring intensely with glowing red eyes" | TEXT="は？" P5: ACTION/PROPS="A person in a full-body tight suit biting a handkerchief in sheer frustration" | TEXT="悔しい！" P6: ACTION/PROPS="A person in a full-body tight suit throwing a small table upside down" | TEXT="やってられん！" P7: ACTION/PROPS="A person in a full-body tight suit holding up a red card like a soccer referee" | TEXT="アウト！" P8: ACTION/PROPS="A person in a full-body tight suit crossing arms tightly to make a big X" | TEXT="ダメ絶対" P9: ACTION/PROPS="A person in a full-body tight suit pointing a finger directly at the viewer menacingly" | TEXT="お前だ"',
    'P1: ACTION/PROPS="A person in a full-body tight suit with eyeballs popping out in extreme shock" | TEXT="マジで！？" P2: ACTION/PROPS="A person in a full-body tight suit with cold sweat pouring down a pale face" | TEXT="ヤバい" P3: ACTION/PROPS="A person in a full-body tight suit running frantically in circles" | TEXT="どうしよう！" P4: ACTION/PROPS="A person in a full-body tight suit dropping a smartphone and looking horrified" | TEXT="あっ" P5: ACTION/PROPS="A person in a full-body tight suit hiding half their body behind a telephone pole and trembling" | TEXT="こわい" P6: ACTION/PROPS="A person in a full-body tight suit pretending to not see anything by covering eyes" | TEXT="見なかったことに" P7: ACTION/PROPS="A person in a full-body tight suit holding their head with both hands like The Scream" | TEXT="嘘でしょ" P8: ACTION/PROPS="A person in a full-body tight suit blowing away in a strong wind like a piece of paper" | TEXT="飛んでく" P9: ACTION/PROPS="A person in a full-body tight suit sliding backwards gracefully to escape" | TEXT="退散"',
    'P1: ACTION/PROPS="A person in a full-body tight suit meditating while floating in mid-air" | TEXT="無" P2: ACTION/PROPS="A person in a full-body tight suit doing a muscular bodybuilder pose with a super shiny body" | TEXT="仕上がってるよ" P3: ACTION/PROPS="A person in a full-body tight suit disguised as a potted plant" | TEXT="気配を消します" P4: ACTION/PROPS="A person in a full-body tight suit holding a glowing magical staff like a wizard" | TEXT="魔法をかけます" P5: ACTION/PROPS="A person in a full-body tight suit riding a tiny tricycle with a straight face" | TEXT="お迎えに上がります" P6: ACTION/PROPS="A person in a full-body tight suit slowly emerging from a trash can" | TEXT="呼んだ？" P7: ACTION/PROPS="A person in a full-body tight suit wearing cool sunglasses and holding a bouquet of roses" | TEXT="迎えに来たぜ" P8: ACTION/PROPS="A person in a full-body tight suit staring completely blankly at a wall" | TEXT="虚無" P9: ACTION/PROPS="A person in a full-body tight suit giving a high five to an alien" | TEXT="宇宙規模の賛成"',
]

filepath = '頭頂部までの顔出し全身タイツ_prompts.csv'

with open(filepath, 'w', encoding='utf-8-sig', newline='') as f:
    writer = csv.writer(f)
    for row in rows:
        writer.writerow([row])

print('Done. Lines:', len(rows))
